// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_cliente;


/**
 * "BajaCliente" Adaptive Web Service Model implementation
 * Copyright (c) 2005-2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class BajaCliente extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel
{
  private static final String DESIGN_TIME_WSDL_URL = "http://desagvqg.bue.quilmes.com.ar/wsd/wsmdm/servlet/abajacliente?wsdl"; 
  private static final String METADATA_DESTINATION = ""; 
  private static final String DEFAULT_EXECUTION_DESTINATION = ""; 
  private static final String INTERFACE_QNAME_NAMESPACE = "http://tempuri.org/action/"; 
  private static final String INTERFACE_QNAME_LOCALPART = "BajaClienteSoapPort"; 
  private static final String NAMESPACE_MAPPING_AS_STRING = "http%3A%2F%2Fsap.com%2Ftc%2Fwebdynpro%2Fmodel%2Fwebservice,,http%3A%2F%2Ftempuri.org%2Faction%2F,,quilmes,"; 

  private static final javax.xml.namespace.QName interfaceQName = 
    (INTERFACE_QNAME_LOCALPART == null || "".equals(INTERFACE_QNAME_LOCALPART)) ?
        null : new javax.xml.namespace.QName(INTERFACE_QNAME_NAMESPACE, INTERFACE_QNAME_LOCALPART);

  //model class renaming
  private static final java.util.Map MC_NAME_MAPPING = new java.util.HashMap();
  //typed model info reference
  private static final com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelInfo TYPED_MODEL_INFO = createTypedModelInfo();
  
  static {
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("quilmes", "Mensajes.MensajesItem"), "MensajesMensajesItem");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("quilmes", "Mensajes"), "Mensajes");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("http://tempuri.org/action/", "/definitions/types/schema[2]/element[2]/complexType"), "BajaCliente_ExecuteResponse");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("http://sap.com/tc/webdynpro/model/webservice", "Response_Execute"), "Response_Execute");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("http://tempuri.org/action/", "/definitions/types/schema[2]/element[1]/complexType"), "BajaCliente_Execute");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("http://sap.com/tc/webdynpro/model/webservice", "Request_Execute"), "RequestB_Execute");

    TYPED_MODEL_INFO.registerModelClass(MensajesMensajesItem.createModelClassFactory(), "MensajesMensajesItem");
    TYPED_MODEL_INFO.registerModelClass(Mensajes.createModelClassFactory(), "Mensajes");
    TYPED_MODEL_INFO.registerModelClass(BajaCliente_ExecuteResponse.createModelClassFactory(), "BajaCliente_ExecuteResponse");
    TYPED_MODEL_INFO.registerModelClass(Response_Execute.createModelClassFactory(), "Response_Execute");
    TYPED_MODEL_INFO.registerModelClass(BajaCliente_Execute.createModelClassFactory(), "BajaCliente_Execute");
    TYPED_MODEL_INFO.registerModelClass(RequestB_Execute.createModelClassFactory(), "RequestB_Execute");
  }  

  public BajaCliente() {
    super(DESIGN_TIME_WSDL_URL, 
          METADATA_DESTINATION, interfaceQName, 
          NAMESPACE_MAPPING_AS_STRING, MC_NAME_MAPPING, 
          DEFAULT_EXECUTION_DESTINATION, TYPED_MODEL_INFO);
  }
}