// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_cliente;


/**
 * "RequestB_Execute" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class RequestB_Execute extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClassExecutable
{
  public RequestB_Execute(BajaCliente modelInstance) {
    super(modelInstance, "RequestB_Execute");
  }

  public BajaCliente getModelInstance() {
    return (BajaCliente) this.associatedModel();
  }
  
  private RequestB_Execute(BajaCliente modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new RequestB_Execute((BajaCliente)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> BajaClienteExecute
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> BajaClienteExecute 
   *  @return value of ModelAttribute BajaClienteExecute */
  public com.quilmes.baja_cliente.BajaCliente_Execute getBajaClienteExecute() {
    return (com.quilmes.baja_cliente.BajaCliente_Execute)getRelatedModelObject("BajaClienteExecute");
  }
  
  /** setter for 1:1 Relation Role -> BajaClienteExecute 
   *  @param value new value for 1:1 Relation Role  BajaClienteExecute */
  public void setBajaClienteExecute(com.quilmes.baja_cliente.BajaCliente_Execute value) {
    setRelatedModelObject("BajaClienteExecute",value);
  }
  /****************************************************************************
   * 1:1 Relation -> Response
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Response 
   *  @return value of ModelAttribute Response */
  public com.quilmes.baja_cliente.Response_Execute getResponse() {
    return (com.quilmes.baja_cliente.Response_Execute)getRelatedModelObject("Response");
  }
  
  /** setter for 1:1 Relation Role -> Response 
   *  @param value new value for 1:1 Relation Role  Response */
  public void setResponse(com.quilmes.baja_cliente.Response_Execute value) {
    setRelatedModelObject("Response",value);
  }

}

