// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_cliente;


/**
 * "Response_Execute" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class Response_Execute extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public Response_Execute(BajaCliente modelInstance) {
    super(modelInstance, "Response_Execute");
  }

  public BajaCliente getModelInstance() {
    return (BajaCliente) this.associatedModel();
  }
  
  private Response_Execute(BajaCliente modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new Response_Execute((BajaCliente)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> BajaClienteExecuteResponse
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> BajaClienteExecuteResponse 
   *  @return value of ModelAttribute BajaClienteExecuteResponse */
  public com.quilmes.baja_cliente.BajaCliente_ExecuteResponse getBajaClienteExecuteResponse() {
    return (com.quilmes.baja_cliente.BajaCliente_ExecuteResponse)getRelatedModelObject("BajaClienteExecuteResponse");
  }
  
  /** setter for 1:1 Relation Role -> BajaClienteExecuteResponse 
   *  @param value new value for 1:1 Relation Role  BajaClienteExecuteResponse */
  public void setBajaClienteExecuteResponse(com.quilmes.baja_cliente.BajaCliente_ExecuteResponse value) {
    setRelatedModelObject("BajaClienteExecuteResponse",value);
  }

}

