// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja.consultaclientes;


/**
 * "ArrayOfFrecuencia" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class ArrayOfFrecuencia extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public ArrayOfFrecuencia(ConsultaClientes modelInstance) {
    super(modelInstance, "ArrayOfFrecuencia");
  }

  public ConsultaClientes getModelInstance() {
    return (ConsultaClientes) this.associatedModel();
  }
  
  private ArrayOfFrecuencia(ConsultaClientes modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new ArrayOfFrecuencia((ConsultaClientes)typedModel, genericModelClass);
      }
    };
  }  

  /****************************************************************************
   *  1:n Relation -> Frecuencia
   ***************************************************************************/

  /** getter for 1:n Relation Role -> Frecuencia 
   *  @return java.util.List containing elements of 1:n Relation Role Frecuencia */
  public java.util.List getFrecuencia() {
    return (java.util.List)getRelatedModelObjects("Frecuencia");
  }

  /** setter for 1:n Relation Role -> Frecuencia 
   *  @param newList java.util.List replaces previous List of elements of 1:n Relation Role Frecuencia */
  public void setFrecuencia(java.util.List list) {
    setRelatedModelObjects("Frecuencia", list);
  }

  /** adds an element to the 1:n Relation Role -> Frecuencia 
   *  @param o object to be added to List of elements of 1:n Relation Role Frecuencia
   *  @return true if element was added */
  public boolean addFrecuencia(com.quilmes.baja.consultaclientes.Frecuencia o) {
    return addRelatedModelObject("Frecuencia", o);
  }

  /** removes the given element from the 1:n Relation Role -> Frecuencia 
   *  @param o object to be removed from List of elements of 1:n Relation Role Frecuencia 
   *  @return true if element existed and was removed */
  public boolean removeFrecuencia(com.quilmes.baja.consultaclientes.Frecuencia o)  {
    return removeRelatedModelObject("Frecuencia", o);
  }


}

