// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja.consultaclientes;


/**
 * "DatosCliente" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class DatosCliente extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public DatosCliente(ConsultaClientes modelInstance) {
    super(modelInstance, "DatosCliente");
  }

  public ConsultaClientes getModelInstance() {
    return (ConsultaClientes) this.associatedModel();
  }
  
  private DatosCliente(ConsultaClientes modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new DatosCliente((ConsultaClientes)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> Territorios
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Territorios 
   *  @return value of ModelAttribute Territorios */
  public com.quilmes.baja.consultaclientes.ArrayOfTerriClien getTerritorios() {
    return (com.quilmes.baja.consultaclientes.ArrayOfTerriClien)getRelatedModelObject("Territorios");
  }
  
  /** setter for 1:1 Relation Role -> Territorios 
   *  @param value new value for 1:1 Relation Role  Territorios */
  public void setTerritorios(com.quilmes.baja.consultaclientes.ArrayOfTerriClien value) {
    setRelatedModelObject("Territorios",value);
  }

  /* ***************************************************************************
   *  ModelAttribute -> AceptaDesUniPed
   * **************************************************************************/
  /** getter for ModelAttribute -> AceptaDesUniPed 
   *  @return value of ModelAttribute AceptaDesUniPed */
  public java.lang.String getAceptaDesUniPed() {
    return (java.lang.String)super.getAttributeValue("AceptaDesUniPed");
  }
  /** setter for ModelAttribute -> AceptaDesUniPed 
   *  @param value new value for ModelAttribute AceptaDesUniPed */
  public void setAceptaDesUniPed(java.lang.String value) {
    super.setAttributeValue("AceptaDesUniPed", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> AgrupaComercial
   * **************************************************************************/
  /** getter for ModelAttribute -> AgrupaComercial 
   *  @return value of ModelAttribute AgrupaComercial */
  public int getAgrupaComercial() {
    return super.getAttributeValueAsInt("AgrupaComercial");
  }
  /** setter for ModelAttribute -> AgrupaComercial 
   *  @param value new value for ModelAttribute AgrupaComercial */
  public void setAgrupaComercial(int value) {
    super.setAttributeValueAsInt("AgrupaComercial", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> AsignacionSTK
   * **************************************************************************/
  /** getter for ModelAttribute -> AsignacionSTK 
   *  @return value of ModelAttribute AsignacionSTK */
  public short getAsignacionSTK() {
    return super.getAttributeValueAsShort("AsignacionSTK");
  }
  /** setter for ModelAttribute -> AsignacionSTK 
   *  @param value new value for ModelAttribute AsignacionSTK */
  public void setAsignacionSTK(short value) {
    super.setAttributeValueAsShort("AsignacionSTK", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> AutVtaAlcohol
   * **************************************************************************/
  /** getter for ModelAttribute -> AutVtaAlcohol 
   *  @return value of ModelAttribute AutVtaAlcohol */
  public java.lang.String getAutVtaAlcohol() {
    return (java.lang.String)super.getAttributeValue("AutVtaAlcohol");
  }
  /** setter for ModelAttribute -> AutVtaAlcohol 
   *  @param value new value for ModelAttribute AutVtaAlcohol */
  public void setAutVtaAlcohol(java.lang.String value) {
    super.setAttributeValue("AutVtaAlcohol", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Banco
   * **************************************************************************/
  /** getter for ModelAttribute -> Banco 
   *  @return value of ModelAttribute Banco */
  public short getBanco() {
    return super.getAttributeValueAsShort("Banco");
  }
  /** setter for ModelAttribute -> Banco 
   *  @param value new value for ModelAttribute Banco */
  public void setBanco(short value) {
    super.setAttributeValueAsShort("Banco", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> CP
   * **************************************************************************/
  /** getter for ModelAttribute -> CP 
   *  @return value of ModelAttribute CP */
  public java.lang.String getCP() {
    return (java.lang.String)super.getAttributeValue("CP");
  }
  /** setter for ModelAttribute -> CP 
   *  @param value new value for ModelAttribute CP */
  public void setCP(java.lang.String value) {
    super.setAttributeValue("CP", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Categoria
   * **************************************************************************/
  /** getter for ModelAttribute -> Categoria 
   *  @return value of ModelAttribute Categoria */
  public java.lang.String getCategoria() {
    return (java.lang.String)super.getAttributeValue("Categoria");
  }
  /** setter for ModelAttribute -> Categoria 
   *  @param value new value for ModelAttribute Categoria */
  public void setCategoria(java.lang.String value) {
    super.setAttributeValue("Categoria", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> ClienteExportacion
   * **************************************************************************/
  /** getter for ModelAttribute -> ClienteExportacion 
   *  @return value of ModelAttribute ClienteExportacion */
  public java.lang.String getClienteExportacion() {
    return (java.lang.String)super.getAttributeValue("ClienteExportacion");
  }
  /** setter for ModelAttribute -> ClienteExportacion 
   *  @param value new value for ModelAttribute ClienteExportacion */
  public void setClienteExportacion(java.lang.String value) {
    super.setAttributeValue("ClienteExportacion", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Cobrador
   * **************************************************************************/
  /** getter for ModelAttribute -> Cobrador 
   *  @return value of ModelAttribute Cobrador */
  public java.lang.String getCobrador() {
    return (java.lang.String)super.getAttributeValue("Cobrador");
  }
  /** setter for ModelAttribute -> Cobrador 
   *  @param value new value for ModelAttribute Cobrador */
  public void setCobrador(java.lang.String value) {
    super.setAttributeValue("Cobrador", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> CodCliente
   * **************************************************************************/
  /** getter for ModelAttribute -> CodCliente 
   *  @return value of ModelAttribute CodCliente */
  public int getCodCliente() {
    return super.getAttributeValueAsInt("CodCliente");
  }
  /** setter for ModelAttribute -> CodCliente 
   *  @param value new value for ModelAttribute CodCliente */
  public void setCodCliente(int value) {
    super.setAttributeValueAsInt("CodCliente", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Comprador
   * **************************************************************************/
  /** getter for ModelAttribute -> Comprador 
   *  @return value of ModelAttribute Comprador */
  public java.lang.String getComprador() {
    return (java.lang.String)super.getAttributeValue("Comprador");
  }
  /** setter for ModelAttribute -> Comprador 
   *  @param value new value for ModelAttribute Comprador */
  public void setComprador(java.lang.String value) {
    super.setAttributeValue("Comprador", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> CoordenadaX
   * **************************************************************************/
  /** getter for ModelAttribute -> CoordenadaX 
   *  @return value of ModelAttribute CoordenadaX */
  public java.lang.String getCoordenadaX() {
    return (java.lang.String)super.getAttributeValue("CoordenadaX");
  }
  /** setter for ModelAttribute -> CoordenadaX 
   *  @param value new value for ModelAttribute CoordenadaX */
  public void setCoordenadaX(java.lang.String value) {
    super.setAttributeValue("CoordenadaX", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> CoordenadaY
   * **************************************************************************/
  /** getter for ModelAttribute -> CoordenadaY 
   *  @return value of ModelAttribute CoordenadaY */
  public java.lang.String getCoordenadaY() {
    return (java.lang.String)super.getAttributeValue("CoordenadaY");
  }
  /** setter for ModelAttribute -> CoordenadaY 
   *  @param value new value for ModelAttribute CoordenadaY */
  public void setCoordenadaY(java.lang.String value) {
    super.setAttributeValue("CoordenadaY", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> CuentaCorrExterna
   * **************************************************************************/
  /** getter for ModelAttribute -> CuentaCorrExterna 
   *  @return value of ModelAttribute CuentaCorrExterna */
  public java.lang.String getCuentaCorrExterna() {
    return (java.lang.String)super.getAttributeValue("CuentaCorrExterna");
  }
  /** setter for ModelAttribute -> CuentaCorrExterna 
   *  @param value new value for ModelAttribute CuentaCorrExterna */
  public void setCuentaCorrExterna(java.lang.String value) {
    super.setAttributeValue("CuentaCorrExterna", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> CuentaMadre
   * **************************************************************************/
  /** getter for ModelAttribute -> CuentaMadre 
   *  @return value of ModelAttribute CuentaMadre */
  public int getCuentaMadre() {
    return super.getAttributeValueAsInt("CuentaMadre");
  }
  /** setter for ModelAttribute -> CuentaMadre 
   *  @param value new value for ModelAttribute CuentaMadre */
  public void setCuentaMadre(int value) {
    super.setAttributeValueAsInt("CuentaMadre", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Departamento
   * **************************************************************************/
  /** getter for ModelAttribute -> Departamento 
   *  @return value of ModelAttribute Departamento */
  public short getDepartamento() {
    return super.getAttributeValueAsShort("Departamento");
  }
  /** setter for ModelAttribute -> Departamento 
   *  @param value new value for ModelAttribute Departamento */
  public void setDepartamento(short value) {
    super.setAttributeValueAsShort("Departamento", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Domicilio
   * **************************************************************************/
  /** getter for ModelAttribute -> Domicilio 
   *  @return value of ModelAttribute Domicilio */
  public java.lang.String getDomicilio() {
    return (java.lang.String)super.getAttributeValue("Domicilio");
  }
  /** setter for ModelAttribute -> Domicilio 
   *  @param value new value for ModelAttribute Domicilio */
  public void setDomicilio(java.lang.String value) {
    super.setAttributeValue("Domicilio", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Email
   * **************************************************************************/
  /** getter for ModelAttribute -> Email 
   *  @return value of ModelAttribute Email */
  public java.lang.String getEmail() {
    return (java.lang.String)super.getAttributeValue("Email");
  }
  /** setter for ModelAttribute -> Email 
   *  @param value new value for ModelAttribute Email */
  public void setEmail(java.lang.String value) {
    super.setAttributeValue("Email", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> EsExclusivo
   * **************************************************************************/
  /** getter for ModelAttribute -> EsExclusivo 
   *  @return value of ModelAttribute EsExclusivo */
  public java.lang.String getEsExclusivo() {
    return (java.lang.String)super.getAttributeValue("EsExclusivo");
  }
  /** setter for ModelAttribute -> EsExclusivo 
   *  @param value new value for ModelAttribute EsExclusivo */
  public void setEsExclusivo(java.lang.String value) {
    super.setAttributeValue("EsExclusivo", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> FechaAniversario
   * **************************************************************************/
  /** getter for ModelAttribute -> FechaAniversario 
   *  @return value of ModelAttribute FechaAniversario */
  public java.sql.Date getFechaAniversario() {
    return (java.sql.Date)super.getAttributeValue("FechaAniversario");
  }
  /** setter for ModelAttribute -> FechaAniversario 
   *  @param value new value for ModelAttribute FechaAniversario */
  public void setFechaAniversario(java.sql.Date value) {
    super.setAttributeValue("FechaAniversario", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> FechaUltVerifiCons
   * **************************************************************************/
  /** getter for ModelAttribute -> FechaUltVerifiCons 
   *  @return value of ModelAttribute FechaUltVerifiCons */
  public java.sql.Date getFechaUltVerifiCons() {
    return (java.sql.Date)super.getAttributeValue("FechaUltVerifiCons");
  }
  /** setter for ModelAttribute -> FechaUltVerifiCons 
   *  @param value new value for ModelAttribute FechaUltVerifiCons */
  public void setFechaUltVerifiCons(java.sql.Date value) {
    super.setAttributeValue("FechaUltVerifiCons", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> FechaVencLicencia
   * **************************************************************************/
  /** getter for ModelAttribute -> FechaVencLicencia 
   *  @return value of ModelAttribute FechaVencLicencia */
  public java.sql.Date getFechaVencLicencia() {
    return (java.sql.Date)super.getAttributeValue("FechaVencLicencia");
  }
  /** setter for ModelAttribute -> FechaVencLicencia 
   *  @param value new value for ModelAttribute FechaVencLicencia */
  public void setFechaVencLicencia(java.sql.Date value) {
    super.setAttributeValue("FechaVencLicencia", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> FormaAtencion
   * **************************************************************************/
  /** getter for ModelAttribute -> FormaAtencion 
   *  @return value of ModelAttribute FormaAtencion */
  public int getFormaAtencion() {
    return super.getAttributeValueAsInt("FormaAtencion");
  }
  /** setter for ModelAttribute -> FormaAtencion 
   *  @param value new value for ModelAttribute FormaAtencion */
  public void setFormaAtencion(int value) {
    super.setAttributeValueAsInt("FormaAtencion", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> FormaPago
   * **************************************************************************/
  /** getter for ModelAttribute -> FormaPago 
   *  @return value of ModelAttribute FormaPago */
  public short getFormaPago() {
    return super.getAttributeValueAsShort("FormaPago");
  }
  /** setter for ModelAttribute -> FormaPago 
   *  @param value new value for ModelAttribute FormaPago */
  public void setFormaPago(short value) {
    super.setAttributeValueAsShort("FormaPago", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> FrmEntregaCtaCte
   * **************************************************************************/
  /** getter for ModelAttribute -> FrmEntregaCtaCte 
   *  @return value of ModelAttribute FrmEntregaCtaCte */
  public java.lang.String getFrmEntregaCtaCte() {
    return (java.lang.String)super.getAttributeValue("FrmEntregaCtaCte");
  }
  /** setter for ModelAttribute -> FrmEntregaCtaCte 
   *  @param value new value for ModelAttribute FrmEntregaCtaCte */
  public void setFrmEntregaCtaCte(java.lang.String value) {
    super.setAttributeValue("FrmEntregaCtaCte", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> FueCensado
   * **************************************************************************/
  /** getter for ModelAttribute -> FueCensado 
   *  @return value of ModelAttribute FueCensado */
  public java.lang.String getFueCensado() {
    return (java.lang.String)super.getAttributeValue("FueCensado");
  }
  /** setter for ModelAttribute -> FueCensado 
   *  @param value new value for ModelAttribute FueCensado */
  public void setFueCensado(java.lang.String value) {
    super.setAttributeValue("FueCensado", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> IIBBFchDesde
   * **************************************************************************/
  /** getter for ModelAttribute -> IIBBFchDesde 
   *  @return value of ModelAttribute IIBBFchDesde */
  public java.sql.Date getIIBBFchDesde() {
    return (java.sql.Date)super.getAttributeValue("IIBBFchDesde");
  }
  /** setter for ModelAttribute -> IIBBFchDesde 
   *  @param value new value for ModelAttribute IIBBFchDesde */
  public void setIIBBFchDesde(java.sql.Date value) {
    super.setAttributeValue("IIBBFchDesde", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> IIBBFchHasta
   * **************************************************************************/
  /** getter for ModelAttribute -> IIBBFchHasta 
   *  @return value of ModelAttribute IIBBFchHasta */
  public java.sql.Date getIIBBFchHasta() {
    return (java.sql.Date)super.getAttributeValue("IIBBFchHasta");
  }
  /** setter for ModelAttribute -> IIBBFchHasta 
   *  @param value new value for ModelAttribute IIBBFchHasta */
  public void setIIBBFchHasta(java.sql.Date value) {
    super.setAttributeValue("IIBBFchHasta", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> IdMensajeFact
   * **************************************************************************/
  /** getter for ModelAttribute -> IdMensajeFact 
   *  @return value of ModelAttribute IdMensajeFact */
  public short getIdMensajeFact() {
    return super.getAttributeValueAsShort("IdMensajeFact");
  }
  /** setter for ModelAttribute -> IdMensajeFact 
   *  @param value new value for ModelAttribute IdMensajeFact */
  public void setIdMensajeFact(short value) {
    super.setAttributeValueAsShort("IdMensajeFact", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> IdentificacionJuridica
   * **************************************************************************/
  /** getter for ModelAttribute -> IdentificacionJuridica 
   *  @return value of ModelAttribute IdentificacionJuridica */
  public java.lang.String getIdentificacionJuridica() {
    return (java.lang.String)super.getAttributeValue("IdentificacionJuridica");
  }
  /** setter for ModelAttribute -> IdentificacionJuridica 
   *  @param value new value for ModelAttribute IdentificacionJuridica */
  public void setIdentificacionJuridica(java.lang.String value) {
    super.setAttributeValue("IdentificacionJuridica", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> ImprimeRemito
   * **************************************************************************/
  /** getter for ModelAttribute -> ImprimeRemito 
   *  @return value of ModelAttribute ImprimeRemito */
  public java.lang.String getImprimeRemito() {
    return (java.lang.String)super.getAttributeValue("ImprimeRemito");
  }
  /** setter for ModelAttribute -> ImprimeRemito 
   *  @param value new value for ModelAttribute ImprimeRemito */
  public void setImprimeRemito(java.lang.String value) {
    super.setAttributeValue("ImprimeRemito", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> IvaFchDesde
   * **************************************************************************/
  /** getter for ModelAttribute -> IvaFchDesde 
   *  @return value of ModelAttribute IvaFchDesde */
  public java.sql.Date getIvaFchDesde() {
    return (java.sql.Date)super.getAttributeValue("IvaFchDesde");
  }
  /** setter for ModelAttribute -> IvaFchDesde 
   *  @param value new value for ModelAttribute IvaFchDesde */
  public void setIvaFchDesde(java.sql.Date value) {
    super.setAttributeValue("IvaFchDesde", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> IvaFchHasta
   * **************************************************************************/
  /** getter for ModelAttribute -> IvaFchHasta 
   *  @return value of ModelAttribute IvaFchHasta */
  public java.sql.Date getIvaFchHasta() {
    return (java.sql.Date)super.getAttributeValue("IvaFchHasta");
  }
  /** setter for ModelAttribute -> IvaFchHasta 
   *  @param value new value for ModelAttribute IvaFchHasta */
  public void setIvaFchHasta(java.sql.Date value) {
    super.setAttributeValue("IvaFchHasta", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> ListaPrcBasico
   * **************************************************************************/
  /** getter for ModelAttribute -> ListaPrcBasico 
   *  @return value of ModelAttribute ListaPrcBasico */
  public short getListaPrcBasico() {
    return super.getAttributeValueAsShort("ListaPrcBasico");
  }
  /** setter for ModelAttribute -> ListaPrcBasico 
   *  @param value new value for ModelAttribute ListaPrcBasico */
  public void setListaPrcBasico(short value) {
    super.setAttributeValueAsShort("ListaPrcBasico", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> ListaPrcMaxima
   * **************************************************************************/
  /** getter for ModelAttribute -> ListaPrcMaxima 
   *  @return value of ModelAttribute ListaPrcMaxima */
  public short getListaPrcMaxima() {
    return super.getAttributeValueAsShort("ListaPrcMaxima");
  }
  /** setter for ModelAttribute -> ListaPrcMaxima 
   *  @param value new value for ModelAttribute ListaPrcMaxima */
  public void setListaPrcMaxima(short value) {
    super.setAttributeValueAsShort("ListaPrcMaxima", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Localidad
   * **************************************************************************/
  /** getter for ModelAttribute -> Localidad 
   *  @return value of ModelAttribute Localidad */
  public java.lang.String getLocalidad() {
    return (java.lang.String)super.getAttributeValue("Localidad");
  }
  /** setter for ModelAttribute -> Localidad 
   *  @param value new value for ModelAttribute Localidad */
  public void setLocalidad(java.lang.String value) {
    super.setAttributeValue("Localidad", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> MensajeFactura
   * **************************************************************************/
  /** getter for ModelAttribute -> MensajeFactura 
   *  @return value of ModelAttribute MensajeFactura */
  public java.lang.String getMensajeFactura() {
    return (java.lang.String)super.getAttributeValue("MensajeFactura");
  }
  /** setter for ModelAttribute -> MensajeFactura 
   *  @param value new value for ModelAttribute MensajeFactura */
  public void setMensajeFactura(java.lang.String value) {
    super.setAttributeValue("MensajeFactura", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Moneda
   * **************************************************************************/
  /** getter for ModelAttribute -> Moneda 
   *  @return value of ModelAttribute Moneda */
  public java.lang.String getMoneda() {
    return (java.lang.String)super.getAttributeValue("Moneda");
  }
  /** setter for ModelAttribute -> Moneda 
   *  @param value new value for ModelAttribute Moneda */
  public void setMoneda(java.lang.String value) {
    super.setAttributeValue("Moneda", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> NombreFant
   * **************************************************************************/
  /** getter for ModelAttribute -> NombreFant 
   *  @return value of ModelAttribute NombreFant */
  public java.lang.String getNombreFant() {
    return (java.lang.String)super.getAttributeValue("NombreFant");
  }
  /** setter for ModelAttribute -> NombreFant 
   *  @param value new value for ModelAttribute NombreFant */
  public void setNombreFant(java.lang.String value) {
    super.setAttributeValue("NombreFant", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> NroDocumento
   * **************************************************************************/
  /** getter for ModelAttribute -> NroDocumento 
   *  @return value of ModelAttribute NroDocumento */
  public java.lang.String getNroDocumento() {
    return (java.lang.String)super.getAttributeValue("NroDocumento");
  }
  /** setter for ModelAttribute -> NroDocumento 
   *  @param value new value for ModelAttribute NroDocumento */
  public void setNroDocumento(java.lang.String value) {
    super.setAttributeValue("NroDocumento", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> NroIIBB
   * **************************************************************************/
  /** getter for ModelAttribute -> NroIIBB 
   *  @return value of ModelAttribute NroIIBB */
  public java.lang.String getNroIIBB() {
    return (java.lang.String)super.getAttributeValue("NroIIBB");
  }
  /** setter for ModelAttribute -> NroIIBB 
   *  @param value new value for ModelAttribute NroIIBB */
  public void setNroIIBB(java.lang.String value) {
    super.setAttributeValue("NroIIBB", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> NroImpInternos
   * **************************************************************************/
  /** getter for ModelAttribute -> NroImpInternos 
   *  @return value of ModelAttribute NroImpInternos */
  public java.lang.String getNroImpInternos() {
    return (java.lang.String)super.getAttributeValue("NroImpInternos");
  }
  /** setter for ModelAttribute -> NroImpInternos 
   *  @param value new value for ModelAttribute NroImpInternos */
  public void setNroImpInternos(java.lang.String value) {
    super.setAttributeValue("NroImpInternos", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> NroLicVtaAlcohol
   * **************************************************************************/
  /** getter for ModelAttribute -> NroLicVtaAlcohol 
   *  @return value of ModelAttribute NroLicVtaAlcohol */
  public java.lang.String getNroLicVtaAlcohol() {
    return (java.lang.String)super.getAttributeValue("NroLicVtaAlcohol");
  }
  /** setter for ModelAttribute -> NroLicVtaAlcohol 
   *  @param value new value for ModelAttribute NroLicVtaAlcohol */
  public void setNroLicVtaAlcohol(java.lang.String value) {
    super.setAttributeValue("NroLicVtaAlcohol", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> NroTicket
   * **************************************************************************/
  /** getter for ModelAttribute -> NroTicket 
   *  @return value of ModelAttribute NroTicket */
  public java.lang.String getNroTicket() {
    return (java.lang.String)super.getAttributeValue("NroTicket");
  }
  /** setter for ModelAttribute -> NroTicket 
   *  @param value new value for ModelAttribute NroTicket */
  public void setNroTicket(java.lang.String value) {
    super.setAttributeValue("NroTicket", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Numero
   * **************************************************************************/
  /** getter for ModelAttribute -> Numero 
   *  @return value of ModelAttribute Numero */
  public java.lang.String getNumero() {
    return (java.lang.String)super.getAttributeValue("Numero");
  }
  /** setter for ModelAttribute -> Numero 
   *  @param value new value for ModelAttribute Numero */
  public void setNumero(java.lang.String value) {
    super.setAttributeValue("Numero", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PagaSeguro
   * **************************************************************************/
  /** getter for ModelAttribute -> PagaSeguro 
   *  @return value of ModelAttribute PagaSeguro */
  public java.lang.String getPagaSeguro() {
    return (java.lang.String)super.getAttributeValue("PagaSeguro");
  }
  /** setter for ModelAttribute -> PagaSeguro 
   *  @param value new value for ModelAttribute PagaSeguro */
  public void setPagaSeguro(java.lang.String value) {
    super.setAttributeValue("PagaSeguro", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PerfilCliente
   * **************************************************************************/
  /** getter for ModelAttribute -> PerfilCliente 
   *  @return value of ModelAttribute PerfilCliente */
  public java.lang.String getPerfilCliente() {
    return (java.lang.String)super.getAttributeValue("PerfilCliente");
  }
  /** setter for ModelAttribute -> PerfilCliente 
   *  @param value new value for ModelAttribute PerfilCliente */
  public void setPerfilCliente(java.lang.String value) {
    super.setAttributeValue("PerfilCliente", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PerfilImpositivo
   * **************************************************************************/
  /** getter for ModelAttribute -> PerfilImpositivo 
   *  @return value of ModelAttribute PerfilImpositivo */
  public short getPerfilImpositivo() {
    return super.getAttributeValueAsShort("PerfilImpositivo");
  }
  /** setter for ModelAttribute -> PerfilImpositivo 
   *  @param value new value for ModelAttribute PerfilImpositivo */
  public void setPerfilImpositivo(short value) {
    super.setAttributeValueAsShort("PerfilImpositivo", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PersoneriaJuridica
   * **************************************************************************/
  /** getter for ModelAttribute -> PersoneriaJuridica 
   *  @return value of ModelAttribute PersoneriaJuridica */
  public java.lang.String getPersoneriaJuridica() {
    return (java.lang.String)super.getAttributeValue("PersoneriaJuridica");
  }
  /** setter for ModelAttribute -> PersoneriaJuridica 
   *  @param value new value for ModelAttribute PersoneriaJuridica */
  public void setPersoneriaJuridica(java.lang.String value) {
    super.setAttributeValue("PersoneriaJuridica", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PolVtaCal1
   * **************************************************************************/
  /** getter for ModelAttribute -> PolVtaCal1 
   *  @return value of ModelAttribute PolVtaCal1 */
  public short getPolVtaCal1() {
    return super.getAttributeValueAsShort("PolVtaCal1");
  }
  /** setter for ModelAttribute -> PolVtaCal1 
   *  @param value new value for ModelAttribute PolVtaCal1 */
  public void setPolVtaCal1(short value) {
    super.setAttributeValueAsShort("PolVtaCal1", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PolVtaCal2
   * **************************************************************************/
  /** getter for ModelAttribute -> PolVtaCal2 
   *  @return value of ModelAttribute PolVtaCal2 */
  public short getPolVtaCal2() {
    return super.getAttributeValueAsShort("PolVtaCal2");
  }
  /** setter for ModelAttribute -> PolVtaCal2 
   *  @param value new value for ModelAttribute PolVtaCal2 */
  public void setPolVtaCal2(short value) {
    super.setAttributeValueAsShort("PolVtaCal2", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PolVtaCal3
   * **************************************************************************/
  /** getter for ModelAttribute -> PolVtaCal3 
   *  @return value of ModelAttribute PolVtaCal3 */
  public short getPolVtaCal3() {
    return super.getAttributeValueAsShort("PolVtaCal3");
  }
  /** setter for ModelAttribute -> PolVtaCal3 
   *  @param value new value for ModelAttribute PolVtaCal3 */
  public void setPolVtaCal3(short value) {
    super.setAttributeValueAsShort("PolVtaCal3", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PrjExcepcionIIBB
   * **************************************************************************/
  /** getter for ModelAttribute -> PrjExcepcionIIBB 
   *  @return value of ModelAttribute PrjExcepcionIIBB */
  public float getPrjExcepcionIIBB() {
    return super.getAttributeValueAsFloat("PrjExcepcionIIBB");
  }
  /** setter for ModelAttribute -> PrjExcepcionIIBB 
   *  @param value new value for ModelAttribute PrjExcepcionIIBB */
  public void setPrjExcepcionIIBB(float value) {
    super.setAttributeValueAsFloat("PrjExcepcionIIBB", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> PrjPersepcionIva
   * **************************************************************************/
  /** getter for ModelAttribute -> PrjPersepcionIva 
   *  @return value of ModelAttribute PrjPersepcionIva */
  public float getPrjPersepcionIva() {
    return super.getAttributeValueAsFloat("PrjPersepcionIva");
  }
  /** setter for ModelAttribute -> PrjPersepcionIva 
   *  @param value new value for ModelAttribute PrjPersepcionIva */
  public void setPrjPersepcionIva(float value) {
    super.setAttributeValueAsFloat("PrjPersepcionIva", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Ramo
   * **************************************************************************/
  /** getter for ModelAttribute -> Ramo 
   *  @return value of ModelAttribute Ramo */
  public short getRamo() {
    return super.getAttributeValueAsShort("Ramo");
  }
  /** setter for ModelAttribute -> Ramo 
   *  @param value new value for ModelAttribute Ramo */
  public void setRamo(short value) {
    super.setAttributeValueAsShort("Ramo", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> RazonABV
   * **************************************************************************/
  /** getter for ModelAttribute -> RazonABV 
   *  @return value of ModelAttribute RazonABV */
  public java.lang.String getRazonABV() {
    return (java.lang.String)super.getAttributeValue("RazonABV");
  }
  /** setter for ModelAttribute -> RazonABV 
   *  @param value new value for ModelAttribute RazonABV */
  public void setRazonABV(java.lang.String value) {
    super.setAttributeValue("RazonABV", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> RazonSocial
   * **************************************************************************/
  /** getter for ModelAttribute -> RazonSocial 
   *  @return value of ModelAttribute RazonSocial */
  public java.lang.String getRazonSocial() {
    return (java.lang.String)super.getAttributeValue("RazonSocial");
  }
  /** setter for ModelAttribute -> RazonSocial 
   *  @param value new value for ModelAttribute RazonSocial */
  public void setRazonSocial(java.lang.String value) {
    super.setAttributeValue("RazonSocial", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SubCanalMkt
   * **************************************************************************/
  /** getter for ModelAttribute -> SubCanalMkt 
   *  @return value of ModelAttribute SubCanalMkt */
  public short getSubCanalMkt() {
    return super.getAttributeValueAsShort("SubCanalMkt");
  }
  /** setter for ModelAttribute -> SubCanalMkt 
   *  @param value new value for ModelAttribute SubCanalMkt */
  public void setSubCanalMkt(short value) {
    super.setAttributeValueAsShort("SubCanalMkt", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Telefono
   * **************************************************************************/
  /** getter for ModelAttribute -> Telefono 
   *  @return value of ModelAttribute Telefono */
  public java.lang.String getTelefono() {
    return (java.lang.String)super.getAttributeValue("Telefono");
  }
  /** setter for ModelAttribute -> Telefono 
   *  @param value new value for ModelAttribute Telefono */
  public void setTelefono(java.lang.String value) {
    super.setAttributeValue("Telefono", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TienePromocion
   * **************************************************************************/
  /** getter for ModelAttribute -> TienePromocion 
   *  @return value of ModelAttribute TienePromocion */
  public java.lang.String getTienePromocion() {
    return (java.lang.String)super.getAttributeValue("TienePromocion");
  }
  /** setter for ModelAttribute -> TienePromocion 
   *  @param value new value for ModelAttribute TienePromocion */
  public void setTienePromocion(java.lang.String value) {
    super.setAttributeValue("TienePromocion", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TipoDeCobranza
   * **************************************************************************/
  /** getter for ModelAttribute -> TipoDeCobranza 
   *  @return value of ModelAttribute TipoDeCobranza */
  public short getTipoDeCobranza() {
    return super.getAttributeValueAsShort("TipoDeCobranza");
  }
  /** setter for ModelAttribute -> TipoDeCobranza 
   *  @param value new value for ModelAttribute TipoDeCobranza */
  public void setTipoDeCobranza(short value) {
    super.setAttributeValueAsShort("TipoDeCobranza", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TipoDocumento
   * **************************************************************************/
  /** getter for ModelAttribute -> TipoDocumento 
   *  @return value of ModelAttribute TipoDocumento */
  public short getTipoDocumento() {
    return super.getAttributeValueAsShort("TipoDocumento");
  }
  /** setter for ModelAttribute -> TipoDocumento 
   *  @param value new value for ModelAttribute TipoDocumento */
  public void setTipoDocumento(short value) {
    super.setAttributeValueAsShort("TipoDocumento", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TipoIIBB
   * **************************************************************************/
  /** getter for ModelAttribute -> TipoIIBB 
   *  @return value of ModelAttribute TipoIIBB */
  public java.lang.String getTipoIIBB() {
    return (java.lang.String)super.getAttributeValue("TipoIIBB");
  }
  /** setter for ModelAttribute -> TipoIIBB 
   *  @param value new value for ModelAttribute TipoIIBB */
  public void setTipoIIBB(java.lang.String value) {
    super.setAttributeValue("TipoIIBB", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TpoCliComisiones
   * **************************************************************************/
  /** getter for ModelAttribute -> TpoCliComisiones 
   *  @return value of ModelAttribute TpoCliComisiones */
  public short getTpoCliComisiones() {
    return super.getAttributeValueAsShort("TpoCliComisiones");
  }
  /** setter for ModelAttribute -> TpoCliComisiones 
   *  @param value new value for ModelAttribute TpoCliComisiones */
  public void setTpoCliComisiones(short value) {
    super.setAttributeValueAsShort("TpoCliComisiones", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TpoCliCondicionVta
   * **************************************************************************/
  /** getter for ModelAttribute -> TpoCliCondicionVta 
   *  @return value of ModelAttribute TpoCliCondicionVta */
  public int getTpoCliCondicionVta() {
    return super.getAttributeValueAsInt("TpoCliCondicionVta");
  }
  /** setter for ModelAttribute -> TpoCliCondicionVta 
   *  @param value new value for ModelAttribute TpoCliCondicionVta */
  public void setTpoCliCondicionVta(int value) {
    super.setAttributeValueAsInt("TpoCliCondicionVta", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TpoClienteContable
   * **************************************************************************/
  /** getter for ModelAttribute -> TpoClienteContable 
   *  @return value of ModelAttribute TpoClienteContable */
  public short getTpoClienteContable() {
    return super.getAttributeValueAsShort("TpoClienteContable");
  }
  /** setter for ModelAttribute -> TpoClienteContable 
   *  @param value new value for ModelAttribute TpoClienteContable */
  public void setTpoClienteContable(short value) {
    super.setAttributeValueAsShort("TpoClienteContable", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TpoEmpresa
   * **************************************************************************/
  /** getter for ModelAttribute -> TpoEmpresa 
   *  @return value of ModelAttribute TpoEmpresa */
  public java.lang.String getTpoEmpresa() {
    return (java.lang.String)super.getAttributeValue("TpoEmpresa");
  }
  /** setter for ModelAttribute -> TpoEmpresa 
   *  @param value new value for ModelAttribute TpoEmpresa */
  public void setTpoEmpresa(java.lang.String value) {
    super.setAttributeValue("TpoEmpresa", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TpoMaquinaVend
   * **************************************************************************/
  /** getter for ModelAttribute -> TpoMaquinaVend 
   *  @return value of ModelAttribute TpoMaquinaVend */
  public java.lang.String getTpoMaquinaVend() {
    return (java.lang.String)super.getAttributeValue("TpoMaquinaVend");
  }
  /** setter for ModelAttribute -> TpoMaquinaVend 
   *  @param value new value for ModelAttribute TpoMaquinaVend */
  public void setTpoMaquinaVend(java.lang.String value) {
    super.setAttributeValue("TpoMaquinaVend", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TpoVtaFSxEnv
   * **************************************************************************/
  /** getter for ModelAttribute -> TpoVtaFSxEnv 
   *  @return value of ModelAttribute TpoVtaFSxEnv */
  public short getTpoVtaFSxEnv() {
    return super.getAttributeValueAsShort("TpoVtaFSxEnv");
  }
  /** setter for ModelAttribute -> TpoVtaFSxEnv 
   *  @param value new value for ModelAttribute TpoVtaFSxEnv */
  public void setTpoVtaFSxEnv(short value) {
    super.setAttributeValueAsShort("TpoVtaFSxEnv", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TpoVtaFSxMerc
   * **************************************************************************/
  /** getter for ModelAttribute -> TpoVtaFSxMerc 
   *  @return value of ModelAttribute TpoVtaFSxMerc */
  public short getTpoVtaFSxMerc() {
    return super.getAttributeValueAsShort("TpoVtaFSxMerc");
  }
  /** setter for ModelAttribute -> TpoVtaFSxMerc 
   *  @param value new value for ModelAttribute TpoVtaFSxMerc */
  public void setTpoVtaFSxMerc(short value) {
    super.setAttributeValueAsShort("TpoVtaFSxMerc", value);
  }
}

