// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja.consultaclientes;


/**
 * "Frecuencia" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class Frecuencia extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public Frecuencia(ConsultaClientes modelInstance) {
    super(modelInstance, "Frecuencia");
  }

  public ConsultaClientes getModelInstance() {
    return (ConsultaClientes) this.associatedModel();
  }
  
  private Frecuencia(ConsultaClientes modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new Frecuencia((ConsultaClientes)typedModel, genericModelClass);
      }
    };
  }  



  /* ***************************************************************************
   *  ModelAttribute -> ClienteVisitaAntes
   * **************************************************************************/
  /** getter for ModelAttribute -> ClienteVisitaAntes 
   *  @return value of ModelAttribute ClienteVisitaAntes */
  public long getClienteVisitaAntes() {
    return super.getAttributeValueAsLong("ClienteVisitaAntes");
  }
  /** setter for ModelAttribute -> ClienteVisitaAntes 
   *  @param value new value for ModelAttribute ClienteVisitaAntes */
  public void setClienteVisitaAntes(long value) {
    super.setAttributeValueAsLong("ClienteVisitaAntes", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> DiaSemana
   * **************************************************************************/
  /** getter for ModelAttribute -> DiaSemana 
   *  @return value of ModelAttribute DiaSemana */
  public byte getDiaSemana() {
    return super.getAttributeValueAsByte("DiaSemana");
  }
  /** setter for ModelAttribute -> DiaSemana 
   *  @param value new value for ModelAttribute DiaSemana */
  public void setDiaSemana(byte value) {
    super.setAttributeValueAsByte("DiaSemana", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> TipoFrecuencia
   * **************************************************************************/
  /** getter for ModelAttribute -> TipoFrecuencia 
   *  @return value of ModelAttribute TipoFrecuencia */
  public java.lang.String getTipoFrecuencia() {
    return (java.lang.String)super.getAttributeValue("TipoFrecuencia");
  }
  /** setter for ModelAttribute -> TipoFrecuencia 
   *  @param value new value for ModelAttribute TipoFrecuencia */
  public void setTipoFrecuencia(java.lang.String value) {
    super.setAttributeValue("TipoFrecuencia", value);
  }
}

