// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja.consultaclientes;


/**
 * "GetDatosCliente_ExecuteResponse" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class GetDatosCliente_ExecuteResponse extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public GetDatosCliente_ExecuteResponse(ConsultaClientes modelInstance) {
    super(modelInstance, "GetDatosCliente_ExecuteResponse");
  }

  public ConsultaClientes getModelInstance() {
    return (ConsultaClientes) this.associatedModel();
  }
  
  private GetDatosCliente_ExecuteResponse(ConsultaClientes modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new GetDatosCliente_ExecuteResponse((ConsultaClientes)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> Datosclientes
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Datosclientes 
   *  @return value of ModelAttribute Datosclientes */
  public com.quilmes.baja.consultaclientes.DatosCliente getDatosclientes() {
    return (com.quilmes.baja.consultaclientes.DatosCliente)getRelatedModelObject("Datosclientes");
  }
  
  /** setter for 1:1 Relation Role -> Datosclientes 
   *  @param value new value for 1:1 Relation Role  Datosclientes */
  public void setDatosclientes(com.quilmes.baja.consultaclientes.DatosCliente value) {
    setRelatedModelObject("Datosclientes",value);
  }
  /****************************************************************************
   * 1:1 Relation -> Mensajes
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Mensajes 
   *  @return value of ModelAttribute Mensajes */
  public com.quilmes.baja.consultaclientes.Mensajes getMensajes() {
    return (com.quilmes.baja.consultaclientes.Mensajes)getRelatedModelObject("Mensajes");
  }
  
  /** setter for 1:1 Relation Role -> Mensajes 
   *  @param value new value for 1:1 Relation Role  Mensajes */
  public void setMensajes(com.quilmes.baja.consultaclientes.Mensajes value) {
    setRelatedModelObject("Mensajes",value);
  }

}

