// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja.consultaclientes;


/**
 * "MensajesMensajesItem" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class MensajesMensajesItem extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public MensajesMensajesItem(ConsultaClientes modelInstance) {
    super(modelInstance, "MensajesMensajesItem");
  }

  public ConsultaClientes getModelInstance() {
    return (ConsultaClientes) this.associatedModel();
  }
  
  private MensajesMensajesItem(ConsultaClientes modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new MensajesMensajesItem((ConsultaClientes)typedModel, genericModelClass);
      }
    };
  }  



  /* ***************************************************************************
   *  ModelAttribute -> MsgErrCode
   * **************************************************************************/
  /** getter for ModelAttribute -> MsgErrCode 
   *  @return value of ModelAttribute MsgErrCode */
  public short getMsgErrCode() {
    return super.getAttributeValueAsShort("MsgErrCode");
  }
  /** setter for ModelAttribute -> MsgErrCode 
   *  @param value new value for ModelAttribute MsgErrCode */
  public void setMsgErrCode(short value) {
    super.setAttributeValueAsShort("MsgErrCode", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> MsgErrDesc
   * **************************************************************************/
  /** getter for ModelAttribute -> MsgErrDesc 
   *  @return value of ModelAttribute MsgErrDesc */
  public java.lang.String getMsgErrDesc() {
    return (java.lang.String)super.getAttributeValue("MsgErrDesc");
  }
  /** setter for ModelAttribute -> MsgErrDesc 
   *  @param value new value for ModelAttribute MsgErrDesc */
  public void setMsgErrDesc(java.lang.String value) {
    super.setAttributeValue("MsgErrDesc", value);
  }
}

