// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja.consultaclientes;


/**
 * "Mensajes" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class Mensajes extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public Mensajes(ConsultaClientes modelInstance) {
    super(modelInstance, "Mensajes");
  }

  public ConsultaClientes getModelInstance() {
    return (ConsultaClientes) this.associatedModel();
  }
  
  private Mensajes(ConsultaClientes modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new Mensajes((ConsultaClientes)typedModel, genericModelClass);
      }
    };
  }  

  /****************************************************************************
   *  1:n Relation -> MensajesMensajesItem
   ***************************************************************************/

  /** getter for 1:n Relation Role -> MensajesMensajesItem 
   *  @return java.util.List containing elements of 1:n Relation Role MensajesMensajesItem */
  public java.util.List getMensajesMensajesItem() {
    return (java.util.List)getRelatedModelObjects("MensajesMensajesItem");
  }

  /** setter for 1:n Relation Role -> MensajesMensajesItem 
   *  @param newList java.util.List replaces previous List of elements of 1:n Relation Role MensajesMensajesItem */
  public void setMensajesMensajesItem(java.util.List list) {
    setRelatedModelObjects("MensajesMensajesItem", list);
  }

  /** adds an element to the 1:n Relation Role -> MensajesMensajesItem 
   *  @param o object to be added to List of elements of 1:n Relation Role MensajesMensajesItem
   *  @return true if element was added */
  public boolean addMensajesMensajesItem(com.quilmes.baja.consultaclientes.MensajesMensajesItem o) {
    return addRelatedModelObject("MensajesMensajesItem", o);
  }

  /** removes the given element from the 1:n Relation Role -> MensajesMensajesItem 
   *  @param o object to be removed from List of elements of 1:n Relation Role MensajesMensajesItem 
   *  @return true if element existed and was removed */
  public boolean removeMensajesMensajesItem(com.quilmes.baja.consultaclientes.MensajesMensajesItem o)  {
    return removeRelatedModelObject("MensajesMensajesItem", o);
  }


}

