// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja.consultaclientes;


/**
 * "Request_Execute" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class Request_Execute extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClassExecutable
{
  public Request_Execute(ConsultaClientes modelInstance) {
    super(modelInstance, "Request_Execute");
  }

  public ConsultaClientes getModelInstance() {
    return (ConsultaClientes) this.associatedModel();
  }
  
  private Request_Execute(ConsultaClientes modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new Request_Execute((ConsultaClientes)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> GetDatosClienteExecute
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> GetDatosClienteExecute 
   *  @return value of ModelAttribute GetDatosClienteExecute */
  public com.quilmes.baja.consultaclientes.GetDatosCliente_Execute getGetDatosClienteExecute() {
    return (com.quilmes.baja.consultaclientes.GetDatosCliente_Execute)getRelatedModelObject("GetDatosClienteExecute");
  }
  
  /** setter for 1:1 Relation Role -> GetDatosClienteExecute 
   *  @param value new value for 1:1 Relation Role  GetDatosClienteExecute */
  public void setGetDatosClienteExecute(com.quilmes.baja.consultaclientes.GetDatosCliente_Execute value) {
    setRelatedModelObject("GetDatosClienteExecute",value);
  }
  /****************************************************************************
   * 1:1 Relation -> Response
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Response 
   *  @return value of ModelAttribute Response */
  public com.quilmes.baja.consultaclientes.Response_Execute getResponse() {
    return (com.quilmes.baja.consultaclientes.Response_Execute)getRelatedModelObject("Response");
  }
  
  /** setter for 1:1 Relation Role -> Response 
   *  @param value new value for 1:1 Relation Role  Response */
  public void setResponse(com.quilmes.baja.consultaclientes.Response_Execute value) {
    setRelatedModelObject("Response",value);
  }

}

