// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja.consultaclientes;


/**
 * "TerriClien" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class TerriClien extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public TerriClien(ConsultaClientes modelInstance) {
    super(modelInstance, "TerriClien");
  }

  public ConsultaClientes getModelInstance() {
    return (ConsultaClientes) this.associatedModel();
  }
  
  private TerriClien(ConsultaClientes modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new TerriClien((ConsultaClientes)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> Frecuencia
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Frecuencia 
   *  @return value of ModelAttribute Frecuencia */
  public com.quilmes.baja.consultaclientes.ArrayOfFrecuencia getFrecuencia() {
    return (com.quilmes.baja.consultaclientes.ArrayOfFrecuencia)getRelatedModelObject("Frecuencia");
  }
  
  /** setter for 1:1 Relation Role -> Frecuencia 
   *  @param value new value for 1:1 Relation Role  Frecuencia */
  public void setFrecuencia(com.quilmes.baja.consultaclientes.ArrayOfFrecuencia value) {
    setRelatedModelObject("Frecuencia",value);
  }

  /* ***************************************************************************
   *  ModelAttribute -> CanalVenta
   * **************************************************************************/
  /** getter for ModelAttribute -> CanalVenta 
   *  @return value of ModelAttribute CanalVenta */
  public short getCanalVenta() {
    return super.getAttributeValueAsShort("CanalVenta");
  }
  /** setter for ModelAttribute -> CanalVenta 
   *  @param value new value for ModelAttribute CanalVenta */
  public void setCanalVenta(short value) {
    super.setAttributeValueAsShort("CanalVenta", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Centrodesp
   * **************************************************************************/
  /** getter for ModelAttribute -> Centrodesp 
   *  @return value of ModelAttribute Centrodesp */
  public java.lang.String getCentrodesp() {
    return (java.lang.String)super.getAttributeValue("Centrodesp");
  }
  /** setter for ModelAttribute -> Centrodesp 
   *  @param value new value for ModelAttribute Centrodesp */
  public void setCentrodesp(java.lang.String value) {
    super.setAttributeValue("Centrodesp", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> CodTerritorio
   * **************************************************************************/
  /** getter for ModelAttribute -> CodTerritorio 
   *  @return value of ModelAttribute CodTerritorio */
  public int getCodTerritorio() {
    return super.getAttributeValueAsInt("CodTerritorio");
  }
  /** setter for ModelAttribute -> CodTerritorio 
   *  @param value new value for ModelAttribute CodTerritorio */
  public void setCodTerritorio(int value) {
    super.setAttributeValueAsInt("CodTerritorio", value);
  }
}

