// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_envases;


/**
 * "Envases" Adaptive Web Service Model implementation
 * Copyright (c) 2005-2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class Envases extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel
{
  private static final String DESIGN_TIME_WSDL_URL = "https://portald2.quinsa.com.ar/wsd/itmedio/servlet/agetsaldoenvases?wsdl"; 
  private static final String METADATA_DESTINATION = "DEFAULT_WS_METADATA_DEST"; 
  private static final String DEFAULT_EXECUTION_DESTINATION = "DEFAULT_WS_EXECUTION_DEST"; 
  private static final String INTERFACE_QNAME_NAMESPACE = "http://tempuri.org/action/"; 
  private static final String INTERFACE_QNAME_LOCALPART = "GetSaldoEnvasesSoapPort"; 
  private static final String NAMESPACE_MAPPING_AS_STRING = "http%3A%2F%2Fsap.com%2Ftc%2Fwebdynpro%2Fmodel%2Fwebservice,,http%3A%2F%2Ftempuri.org%2Faction%2F,,quilmes,"; 

  private static final javax.xml.namespace.QName interfaceQName = 
    (INTERFACE_QNAME_LOCALPART == null || "".equals(INTERFACE_QNAME_LOCALPART)) ?
        null : new javax.xml.namespace.QName(INTERFACE_QNAME_NAMESPACE, INTERFACE_QNAME_LOCALPART);

  //model class renaming
  private static final java.util.Map MC_NAME_MAPPING = new java.util.HashMap();
  //typed model info reference
  private static final com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelInfo TYPED_MODEL_INFO = createTypedModelInfo();
  
  static {
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("http://tempuri.org/action/", "/definitions/types/schema[2]/element[2]/complexType"), "GetSaldoEnvases_ExecuteResponse");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("http://tempuri.org/action/", "/definitions/types/schema[2]/element[1]/complexType"), "GetSaldoEnvases_Execute");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("quilmes", "SalEnvasesItem"), "SalEnvasesItem");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("http://sap.com/tc/webdynpro/model/webservice", "Response_Execute"), "Response_Execute");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("http://sap.com/tc/webdynpro/model/webservice", "Request_Execute"), "RequestE_Execute");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("quilmes", "SaldoEnvases"), "SaldoEnvases");
    MC_NAME_MAPPING.put(new javax.xml.namespace.QName("quilmes", "SalEnvasesItem.SalEnvasesItemItem"), "SalEnvasesItemSalEnvasesItemItem");

    TYPED_MODEL_INFO.registerModelClass(GetSaldoEnvases_ExecuteResponse.createModelClassFactory(), "GetSaldoEnvases_ExecuteResponse");
    TYPED_MODEL_INFO.registerModelClass(GetSaldoEnvases_Execute.createModelClassFactory(), "GetSaldoEnvases_Execute");
    TYPED_MODEL_INFO.registerModelClass(SalEnvasesItem.createModelClassFactory(), "SalEnvasesItem");
    TYPED_MODEL_INFO.registerModelClass(Response_Execute.createModelClassFactory(), "Response_Execute");
    TYPED_MODEL_INFO.registerModelClass(RequestE_Execute.createModelClassFactory(), "RequestE_Execute");
    TYPED_MODEL_INFO.registerModelClass(SaldoEnvases.createModelClassFactory(), "SaldoEnvases");
    TYPED_MODEL_INFO.registerModelClass(SalEnvasesItemSalEnvasesItemItem.createModelClassFactory(), "SalEnvasesItemSalEnvasesItemItem");
  }  

  public Envases() {
    super(DESIGN_TIME_WSDL_URL, 
          METADATA_DESTINATION, interfaceQName, 
          NAMESPACE_MAPPING_AS_STRING, MC_NAME_MAPPING, 
          DEFAULT_EXECUTION_DESTINATION, TYPED_MODEL_INFO);
  }
}