// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_envases;


/**
 * "GetSaldoEnvases_Execute" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class GetSaldoEnvases_Execute extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public GetSaldoEnvases_Execute(Envases modelInstance) {
    super(modelInstance, "GetSaldoEnvases_Execute");
  }

  public Envases getModelInstance() {
    return (Envases) this.associatedModel();
  }
  
  private GetSaldoEnvases_Execute(Envases modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new GetSaldoEnvases_Execute((Envases)typedModel, genericModelClass);
      }
    };
  }  



  /* ***************************************************************************
   *  ModelAttribute -> Distribuidor
   * **************************************************************************/
  /** getter for ModelAttribute -> Distribuidor 
   *  @return value of ModelAttribute Distribuidor */
  public int getDistribuidor() {
    return super.getAttributeValueAsInt("Distribuidor");
  }
  /** setter for ModelAttribute -> Distribuidor 
   *  @param value new value for ModelAttribute Distribuidor */
  public void setDistribuidor(int value) {
    super.setAttributeValueAsInt("Distribuidor", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Fechadesde
   * **************************************************************************/
  /** getter for ModelAttribute -> Fechadesde 
   *  @return value of ModelAttribute Fechadesde */
  public java.sql.Date getFechadesde() {
    return (java.sql.Date)super.getAttributeValue("Fechadesde");
  }
  /** setter for ModelAttribute -> Fechadesde 
   *  @param value new value for ModelAttribute Fechadesde */
  public void setFechadesde(java.sql.Date value) {
    super.setAttributeValue("Fechadesde", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Fechahasta
   * **************************************************************************/
  /** getter for ModelAttribute -> Fechahasta 
   *  @return value of ModelAttribute Fechahasta */
  public java.sql.Date getFechahasta() {
    return (java.sql.Date)super.getAttributeValue("Fechahasta");
  }
  /** setter for ModelAttribute -> Fechahasta 
   *  @param value new value for ModelAttribute Fechahasta */
  public void setFechahasta(java.sql.Date value) {
    super.setAttributeValue("Fechahasta", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Pais
   * **************************************************************************/
  /** getter for ModelAttribute -> Pais 
   *  @return value of ModelAttribute Pais */
  public java.lang.String getPais() {
    return (java.lang.String)super.getAttributeValue("Pais");
  }
  /** setter for ModelAttribute -> Pais 
   *  @param value new value for ModelAttribute Pais */
  public void setPais(java.lang.String value) {
    super.setAttributeValue("Pais", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Parcodenvase
   * **************************************************************************/
  /** getter for ModelAttribute -> Parcodenvase 
   *  @return value of ModelAttribute Parcodenvase */
  public int getParcodenvase() {
    return super.getAttributeValueAsInt("Parcodenvase");
  }
  /** setter for ModelAttribute -> Parcodenvase 
   *  @param value new value for ModelAttribute Parcodenvase */
  public void setParcodenvase(int value) {
    super.setAttributeValueAsInt("Parcodenvase", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Sociedad
   * **************************************************************************/
  /** getter for ModelAttribute -> Sociedad 
   *  @return value of ModelAttribute Sociedad */
  public short getSociedad() {
    return super.getAttributeValueAsShort("Sociedad");
  }
  /** setter for ModelAttribute -> Sociedad 
   *  @param value new value for ModelAttribute Sociedad */
  public void setSociedad(short value) {
    super.setAttributeValueAsShort("Sociedad", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Usuario
   * **************************************************************************/
  /** getter for ModelAttribute -> Usuario 
   *  @return value of ModelAttribute Usuario */
  public java.lang.String getUsuario() {
    return (java.lang.String)super.getAttributeValue("Usuario");
  }
  /** setter for ModelAttribute -> Usuario 
   *  @param value new value for ModelAttribute Usuario */
  public void setUsuario(java.lang.String value) {
    super.setAttributeValue("Usuario", value);
  }
}

