// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_envases;


/**
 * "GetSaldoEnvases_ExecuteResponse" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class GetSaldoEnvases_ExecuteResponse extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public GetSaldoEnvases_ExecuteResponse(Envases modelInstance) {
    super(modelInstance, "GetSaldoEnvases_ExecuteResponse");
  }

  public Envases getModelInstance() {
    return (Envases) this.associatedModel();
  }
  
  private GetSaldoEnvases_ExecuteResponse(Envases modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new GetSaldoEnvases_ExecuteResponse((Envases)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> Saldoenvases
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Saldoenvases 
   *  @return value of ModelAttribute Saldoenvases */
  public com.quilmes.baja_envases.SaldoEnvases getSaldoenvases() {
    return (com.quilmes.baja_envases.SaldoEnvases)getRelatedModelObject("Saldoenvases");
  }
  
  /** setter for 1:1 Relation Role -> Saldoenvases 
   *  @param value new value for 1:1 Relation Role  Saldoenvases */
  public void setSaldoenvases(com.quilmes.baja_envases.SaldoEnvases value) {
    setRelatedModelObject("Saldoenvases",value);
  }

}

