// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_envases;


/**
 * "RequestE_Execute" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class RequestE_Execute extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClassExecutable
{
  public RequestE_Execute(Envases modelInstance) {
    super(modelInstance, "RequestE_Execute");
  }

  public Envases getModelInstance() {
    return (Envases) this.associatedModel();
  }
  
  private RequestE_Execute(Envases modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new RequestE_Execute((Envases)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> GetSaldoEnvasesExecute
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> GetSaldoEnvasesExecute 
   *  @return value of ModelAttribute GetSaldoEnvasesExecute */
  public com.quilmes.baja_envases.GetSaldoEnvases_Execute getGetSaldoEnvasesExecute() {
    return (com.quilmes.baja_envases.GetSaldoEnvases_Execute)getRelatedModelObject("GetSaldoEnvasesExecute");
  }
  
  /** setter for 1:1 Relation Role -> GetSaldoEnvasesExecute 
   *  @param value new value for 1:1 Relation Role  GetSaldoEnvasesExecute */
  public void setGetSaldoEnvasesExecute(com.quilmes.baja_envases.GetSaldoEnvases_Execute value) {
    setRelatedModelObject("GetSaldoEnvasesExecute",value);
  }
  /****************************************************************************
   * 1:1 Relation -> Response
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Response 
   *  @return value of ModelAttribute Response */
  public com.quilmes.baja_envases.Response_Execute getResponse() {
    return (com.quilmes.baja_envases.Response_Execute)getRelatedModelObject("Response");
  }
  
  /** setter for 1:1 Relation Role -> Response 
   *  @param value new value for 1:1 Relation Role  Response */
  public void setResponse(com.quilmes.baja_envases.Response_Execute value) {
    setRelatedModelObject("Response",value);
  }

}

