// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_envases;


/**
 * "Response_Execute" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class Response_Execute extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public Response_Execute(Envases modelInstance) {
    super(modelInstance, "Response_Execute");
  }

  public Envases getModelInstance() {
    return (Envases) this.associatedModel();
  }
  
  private Response_Execute(Envases modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new Response_Execute((Envases)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> GetSaldoEnvasesExecuteResponse
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> GetSaldoEnvasesExecuteResponse 
   *  @return value of ModelAttribute GetSaldoEnvasesExecuteResponse */
  public com.quilmes.baja_envases.GetSaldoEnvases_ExecuteResponse getGetSaldoEnvasesExecuteResponse() {
    return (com.quilmes.baja_envases.GetSaldoEnvases_ExecuteResponse)getRelatedModelObject("GetSaldoEnvasesExecuteResponse");
  }
  
  /** setter for 1:1 Relation Role -> GetSaldoEnvasesExecuteResponse 
   *  @param value new value for 1:1 Relation Role  GetSaldoEnvasesExecuteResponse */
  public void setGetSaldoEnvasesExecuteResponse(com.quilmes.baja_envases.GetSaldoEnvases_ExecuteResponse value) {
    setRelatedModelObject("GetSaldoEnvasesExecuteResponse",value);
  }

}

