// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_envases;


/**
 * "SaldoEnvases" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class SaldoEnvases extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public SaldoEnvases(Envases modelInstance) {
    super(modelInstance, "SaldoEnvases");
  }

  public Envases getModelInstance() {
    return (Envases) this.associatedModel();
  }
  
  private SaldoEnvases(Envases modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new SaldoEnvases((Envases)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> SaldoEnvasesIT
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> SaldoEnvasesIT 
   *  @return value of ModelAttribute SaldoEnvasesIT */
  public com.quilmes.baja_envases.SalEnvasesItem getSaldoEnvasesIT() {
    return (com.quilmes.baja_envases.SalEnvasesItem)getRelatedModelObject("SaldoEnvasesIT");
  }
  
  /** setter for 1:1 Relation Role -> SaldoEnvasesIT 
   *  @param value new value for 1:1 Relation Role  SaldoEnvasesIT */
  public void setSaldoEnvasesIT(com.quilmes.baja_envases.SalEnvasesItem value) {
    setRelatedModelObject("SaldoEnvasesIT",value);
  }

  /* ***************************************************************************
   *  ModelAttribute -> SalEnvFechHora
   * **************************************************************************/
  /** getter for ModelAttribute -> SalEnvFechHora 
   *  @return value of ModelAttribute SalEnvFechHora */
  public java.sql.Timestamp getSalEnvFechHora() {
    return (java.sql.Timestamp)super.getAttributeValue("SalEnvFechHora");
  }
  /** setter for ModelAttribute -> SalEnvFechHora 
   *  @param value new value for ModelAttribute SalEnvFechHora */
  public void setSalEnvFechHora(java.sql.Timestamp value) {
    super.setAttributeValue("SalEnvFechHora", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalTotFin
   * **************************************************************************/
  /** getter for ModelAttribute -> SalTotFin 
   *  @return value of ModelAttribute SalTotFin */
  public double getSalTotFin() {
    return super.getAttributeValueAsDouble("SalTotFin");
  }
  /** setter for ModelAttribute -> SalTotFin 
   *  @param value new value for ModelAttribute SalTotFin */
  public void setSalTotFin(double value) {
    super.setAttributeValueAsDouble("SalTotFin", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalTotIni
   * **************************************************************************/
  /** getter for ModelAttribute -> SalTotIni 
   *  @return value of ModelAttribute SalTotIni */
  public double getSalTotIni() {
    return super.getAttributeValueAsDouble("SalTotIni");
  }
  /** setter for ModelAttribute -> SalTotIni 
   *  @param value new value for ModelAttribute SalTotIni */
  public void setSalTotIni(double value) {
    super.setAttributeValueAsDouble("SalTotIni", value);
  }
}

