// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_envases;


/**
 * "SalEnvasesItem" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class SalEnvasesItem extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public SalEnvasesItem(Envases modelInstance) {
    super(modelInstance, "SalEnvasesItem");
  }

  public Envases getModelInstance() {
    return (Envases) this.associatedModel();
  }
  
  private SalEnvasesItem(Envases modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new SalEnvasesItem((Envases)typedModel, genericModelClass);
      }
    };
  }  

  /****************************************************************************
   *  1:n Relation -> SalEnvasesItemSalEnvasesItemItem
   ***************************************************************************/

  /** getter for 1:n Relation Role -> SalEnvasesItemSalEnvasesItemItem 
   *  @return java.util.List containing elements of 1:n Relation Role SalEnvasesItemSalEnvasesItemItem */
  public java.util.List getSalEnvasesItemSalEnvasesItemItem() {
    return (java.util.List)getRelatedModelObjects("SalEnvasesItemSalEnvasesItemItem");
  }

  /** setter for 1:n Relation Role -> SalEnvasesItemSalEnvasesItemItem 
   *  @param newList java.util.List replaces previous List of elements of 1:n Relation Role SalEnvasesItemSalEnvasesItemItem */
  public void setSalEnvasesItemSalEnvasesItemItem(java.util.List list) {
    setRelatedModelObjects("SalEnvasesItemSalEnvasesItemItem", list);
  }

  /** adds an element to the 1:n Relation Role -> SalEnvasesItemSalEnvasesItemItem 
   *  @param o object to be added to List of elements of 1:n Relation Role SalEnvasesItemSalEnvasesItemItem
   *  @return true if element was added */
  public boolean addSalEnvasesItemSalEnvasesItemItem(com.quilmes.baja_envases.SalEnvasesItemSalEnvasesItemItem o) {
    return addRelatedModelObject("SalEnvasesItemSalEnvasesItemItem", o);
  }

  /** removes the given element from the 1:n Relation Role -> SalEnvasesItemSalEnvasesItemItem 
   *  @param o object to be removed from List of elements of 1:n Relation Role SalEnvasesItemSalEnvasesItemItem 
   *  @return true if element existed and was removed */
  public boolean removeSalEnvasesItemSalEnvasesItemItem(com.quilmes.baja_envases.SalEnvasesItemSalEnvasesItemItem o)  {
    return removeRelatedModelObject("SalEnvasesItemSalEnvasesItemItem", o);
  }


}

