// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_envases;


/**
 * "SalEnvasesItemSalEnvasesItemItem" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class SalEnvasesItemSalEnvasesItemItem extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public SalEnvasesItemSalEnvasesItemItem(Envases modelInstance) {
    super(modelInstance, "SalEnvasesItemSalEnvasesItemItem");
  }

  public Envases getModelInstance() {
    return (Envases) this.associatedModel();
  }
  
  private SalEnvasesItemSalEnvasesItemItem(Envases modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new SalEnvasesItemSalEnvasesItemItem((Envases)typedModel, genericModelClass);
      }
    };
  }  



  /* ***************************************************************************
   *  ModelAttribute -> SalBCreditos
   * **************************************************************************/
  /** getter for ModelAttribute -> SalBCreditos 
   *  @return value of ModelAttribute SalBCreditos */
  public double getSalBCreditos() {
    return super.getAttributeValueAsDouble("SalBCreditos");
  }
  /** setter for ModelAttribute -> SalBCreditos 
   *  @param value new value for ModelAttribute SalBCreditos */
  public void setSalBCreditos(double value) {
    super.setAttributeValueAsDouble("SalBCreditos", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalBDebitos
   * **************************************************************************/
  /** getter for ModelAttribute -> SalBDebitos 
   *  @return value of ModelAttribute SalBDebitos */
  public double getSalBDebitos() {
    return super.getAttributeValueAsDouble("SalBDebitos");
  }
  /** setter for ModelAttribute -> SalBDebitos 
   *  @param value new value for ModelAttribute SalBDebitos */
  public void setSalBDebitos(double value) {
    super.setAttributeValueAsDouble("SalBDebitos", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalBFin
   * **************************************************************************/
  /** getter for ModelAttribute -> SalBFin 
   *  @return value of ModelAttribute SalBFin */
  public double getSalBFin() {
    return super.getAttributeValueAsDouble("SalBFin");
  }
  /** setter for ModelAttribute -> SalBFin 
   *  @param value new value for ModelAttribute SalBFin */
  public void setSalBFin(double value) {
    super.setAttributeValueAsDouble("SalBFin", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalBInicio
   * **************************************************************************/
  /** getter for ModelAttribute -> SalBInicio 
   *  @return value of ModelAttribute SalBInicio */
  public double getSalBInicio() {
    return super.getAttributeValueAsDouble("SalBInicio");
  }
  /** setter for ModelAttribute -> SalBInicio 
   *  @param value new value for ModelAttribute SalBInicio */
  public void setSalBInicio(double value) {
    super.setAttributeValueAsDouble("SalBInicio", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalCodEnv
   * **************************************************************************/
  /** getter for ModelAttribute -> SalCodEnv 
   *  @return value of ModelAttribute SalCodEnv */
  public int getSalCodEnv() {
    return super.getAttributeValueAsInt("SalCodEnv");
  }
  /** setter for ModelAttribute -> SalCodEnv 
   *  @param value new value for ModelAttribute SalCodEnv */
  public void setSalCodEnv(int value) {
    super.setAttributeValueAsInt("SalCodEnv", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalDescrip
   * **************************************************************************/
  /** getter for ModelAttribute -> SalDescrip 
   *  @return value of ModelAttribute SalDescrip */
  public java.lang.String getSalDescrip() {
    return (java.lang.String)super.getAttributeValue("SalDescrip");
  }
  /** setter for ModelAttribute -> SalDescrip 
   *  @param value new value for ModelAttribute SalDescrip */
  public void setSalDescrip(java.lang.String value) {
    super.setAttributeValue("SalDescrip", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalEnvAreaCC
   * **************************************************************************/
  /** getter for ModelAttribute -> SalEnvAreaCC 
   *  @return value of ModelAttribute SalEnvAreaCC */
  public java.lang.String getSalEnvAreaCC() {
    return (java.lang.String)super.getAttributeValue("SalEnvAreaCC");
  }
  /** setter for ModelAttribute -> SalEnvAreaCC 
   *  @param value new value for ModelAttribute SalEnvAreaCC */
  public void setSalEnvAreaCC(java.lang.String value) {
    super.setAttributeValue("SalEnvAreaCC", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalEnvCalCred
   * **************************************************************************/
  /** getter for ModelAttribute -> SalEnvCalCred 
   *  @return value of ModelAttribute SalEnvCalCred */
  public java.lang.String getSalEnvCalCred() {
    return (java.lang.String)super.getAttributeValue("SalEnvCalCred");
  }
  /** setter for ModelAttribute -> SalEnvCalCred 
   *  @param value new value for ModelAttribute SalEnvCalCred */
  public void setSalEnvCalCred(java.lang.String value) {
    super.setAttributeValue("SalEnvCalCred", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalPDebCred
   * **************************************************************************/
  /** getter for ModelAttribute -> SalPDebCred 
   *  @return value of ModelAttribute SalPDebCred */
  public double getSalPDebCred() {
    return super.getAttributeValueAsDouble("SalPDebCred");
  }
  /** setter for ModelAttribute -> SalPDebCred 
   *  @param value new value for ModelAttribute SalPDebCred */
  public void setSalPDebCred(double value) {
    super.setAttributeValueAsDouble("SalPDebCred", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalPFin
   * **************************************************************************/
  /** getter for ModelAttribute -> SalPFin 
   *  @return value of ModelAttribute SalPFin */
  public double getSalPFin() {
    return super.getAttributeValueAsDouble("SalPFin");
  }
  /** setter for ModelAttribute -> SalPFin 
   *  @param value new value for ModelAttribute SalPFin */
  public void setSalPFin(double value) {
    super.setAttributeValueAsDouble("SalPFin", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalPInicio
   * **************************************************************************/
  /** getter for ModelAttribute -> SalPInicio 
   *  @return value of ModelAttribute SalPInicio */
  public double getSalPInicio() {
    return super.getAttributeValueAsDouble("SalPInicio");
  }
  /** setter for ModelAttribute -> SalPInicio 
   *  @param value new value for ModelAttribute SalPInicio */
  public void setSalPInicio(double value) {
    super.setAttributeValueAsDouble("SalPInicio", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> SalPrecio
   * **************************************************************************/
  /** getter for ModelAttribute -> SalPrecio 
   *  @return value of ModelAttribute SalPrecio */
  public double getSalPrecio() {
    return super.getAttributeValueAsDouble("SalPrecio");
  }
  /** setter for ModelAttribute -> SalPrecio 
   *  @param value new value for ModelAttribute SalPrecio */
  public void setSalPrecio(double value) {
    super.setAttributeValueAsDouble("SalPrecio", value);
  }
}

