// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
// ---------------------------------------------------------------------------
package ar.com.quilmes.consulta.wdp;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import com.sap.tc.logging.Location;
import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

public class InternalConsulta_CompView
  implements IPrivateConsulta_CompView, com.sap.tc.webdynpro.progmodel.gci.IGCIViewDelegate
{

  /**
   * Location for this controller.
   */
  private static final Location logger = Location.getLocation(InternalConsulta_CompView.class);

  /**
   * Framework implementation of Controller that delegates to this.
   */
  private final com.sap.tc.webdynpro.progmodel.gci.IGCIView wdAlterEgo;

  /**
   * Delegate that implements application defined logic
   */
  private final ar.com.quilmes.consulta.Consulta_CompView delegate;


  // ---- Context --------------------------------------------------------------

  IGCINodeInfo infoTipoDocumento;
  IGCINodeInfo infoRol;
  IGCINodeInfo infoContext;

  {

    infoTipoDocumento = GCIContext.createMappedNode("TipoDocumento", ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento.class, true, false, false, ".Consulta_Comp.TipoDocumento", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("id", "id", false),
        GCIContext.createMappedAttribute("desc", "desc", false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoRol = GCIContext.createNode("Rol", ar.com.quilmes.bue.mdm_clientes.model.internas.Rol.class, true, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("tipoCobranza", "ddic:com.sap.dictionary.integerObject", null, "tipoCobranza", false, false),
        GCIContext.createAttribute("formaPago", "ddic:com.sap.dictionary.integerObject", null, "formaPago", false, false),
        GCIContext.createAttribute("perfilCliente", "ddic:com.sap.dictionary.string", null, "perfilCliente", false, false),
        GCIContext.createAttribute("segmentoVta", "ddic:com.sap.dictionary.integerObject", null, "segmentoVta", false, false),
        GCIContext.createAttribute("pagaSeguro", "ddic:com.sap.dictionary.string", null, "pagaSeguro", false, false),
        GCIContext.createAttribute("tipoVtaFalSobMerc", "ddic:com.sap.dictionary.integerObject", null, "tipoVtaFalSobMerc", false, false),
        GCIContext.createAttribute("tipoClienteContable", "ddic:com.sap.dictionary.integerObject", null, "tipoClienteContable", false, false),
        GCIContext.createAttribute("tienePromocion", "ddic:com.sap.dictionary.string", null, "tienePromocion", false, false),
        GCIContext.createAttribute("listaPrecioMaximo", "ddic:com.sap.dictionary.integerObject", null, "listaPrecioMaximo", false, false),
        GCIContext.createAttribute("imprimeRemito", "ddic:com.sap.dictionary.string", null, "imprimeRemito", false, false),
        GCIContext.createAttribute("listaPrecioBasico", "ddic:com.sap.dictionary.integerObject", null, "listaPrecioBasico", false, false),
        GCIContext.createAttribute("tipoEmpresa", "ddic:com.sap.dictionary.string", null, "tipoEmpresa", false, false),
        GCIContext.createAttribute("tipoVtaFalSobEnv", "ddic:com.sap.dictionary.integerObject", null, "tipoVtaFalSobEnv", false, false),
        GCIContext.createAttribute("esExclusivo", "ddic:com.sap.dictionary.string", null, "esExclusivo", false, false),
        GCIContext.createAttribute("sociedad", "ddic:com.sap.dictionary.string", null, "sociedad", false, false),
        GCIContext.createAttribute("aceptaDesdUnifPedidos", "ddic:com.sap.dictionary.string", null, "aceptaDesdUnifPedidos", false, false),
        GCIContext.createAttribute("formaEntregaCtaCte", "ddic:com.sap.dictionary.string", null, "formaEntregaCtaCte", false, false),
        GCIContext.createAttribute("canalVenta", "ddic:com.sap.dictionary.integerObject", null, "canalVenta", false, false),
        GCIContext.createAttribute("esquema", "ddic:com.sap.dictionary.string", null, "esquema", false, false),
        GCIContext.createAttribute("formaAtencion", "ddic:com.sap.dictionary.integerObject", null, "formaAtencion", false, false),
        GCIContext.createAttribute("agrupacionComercial", "ddic:com.sap.dictionary.integerObject", null, "agrupacionComercial", false, false),
        GCIContext.createAttribute("polVentaCal1", "ddic:com.sap.dictionary.integerObject", null, "polVentaCal1", false, false),
        GCIContext.createAttribute("ramo", "ddic:com.sap.dictionary.integerObject", null, "ramo", false, false),
        GCIContext.createAttribute("banco", "ddic:com.sap.dictionary.integerObject", null, "banco", false, false),
        GCIContext.createAttribute("ctaCteExterna", "ddic:com.sap.dictionary.string", null, "ctaCteExterna", false, false),
        GCIContext.createAttribute("cobrador", "ddic:com.sap.dictionary.string", null, "cobrador", false, false),
        GCIContext.createAttribute("personeriaJuridica", "ddic:com.sap.dictionary.string", null, "personeriaJuridica", false, false),
        GCIContext.createAttribute("tipoClienteCondVta", "ddic:com.sap.dictionary.integerObject", null, "tipoClienteCondVta", false, false),
        GCIContext.createAttribute("tipoMaqVend", "ddic:com.sap.dictionary.string", null, "tipoMaqVend", false, false),
        GCIContext.createAttribute("polVentaCal3", "ddic:com.sap.dictionary.integerObject", null, "polVentaCal3", false, false),
        GCIContext.createAttribute("identificacionJuridica", "ddic:com.sap.dictionary.string", null, "identificacionJuridica", false, false),
        GCIContext.createAttribute("moneda", "ddic:com.sap.dictionary.string", null, "moneda", false, false),
        GCIContext.createAttribute("tipoCliCom", "ddic:com.sap.dictionary.integerObject", null, "tipoCliCom", false, false),
        GCIContext.createAttribute("nroImpuestoInterno", "ddic:com.sap.dictionary.string", null, "nroImpuestoInterno", false, false),
        GCIContext.createAttribute("asigStock", "ddic:com.sap.dictionary.integerObject", null, "asigStock", false, false),
        GCIContext.createAttribute("comprador", "ddic:com.sap.dictionary.string", null, "comprador", false, false),
        GCIContext.createAttribute("fueCensado", "ddic:com.sap.dictionary.string", null, "fueCensado", false, false),
        GCIContext.createAttribute("polVentaCal2", "ddic:com.sap.dictionary.integerObject", null, "polVentaCal2", false, false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoContext = GCIContext.createNode("Context", null, true, true, false, true, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("nro_cliente", ".Consulta_Comp.nro_cliente", false),
        GCIContext.createMappedAttribute("razon_social", ".Consulta_Comp.razon_social", false),
        GCIContext.createMappedAttribute("nro_documento", ".Consulta_Comp.nro_documento", false),
        GCIContext.createAttribute("Ok", "ddic:com.sap.dictionary.boolean", null, null, false, false),
      },
      new IGCINodeInfo[] {
        infoTipoDocumento,
        infoRol,
      }
    );

  }
  
  private IContextNode contextNode;

  private void wdInitContextNode() {
    contextNode = new IContextNode(this, infoContext, (Node)null);
  }

  public IWDNode wdGetRootNode() {
    return contextNode;
  }

  public IContextNode wdGetContext() {
    return contextNode;
  }


  // ---- Actions --------------------------------------------------------------

  /**
   * Returns the action with name <code>buscar</code>.
   */
  public IWDAction wdGetBuscarAction() {
    return wdAlterEgo.getAction("buscar");
  }

  /**
   * Returns the action with name <code>crear</code>.
   */
  public IWDAction wdGetCrearAction() {
    return wdAlterEgo.getAction("crear");
  }

  /**
   * Create a new action for this controller. A unique name for the action is generated automatially.
   * @param eventHandler is the action's eventhandler with proper signature
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateAction(WDActionEventHandler eventHandler, String text) {
    return wdAlterEgo.createAction(null, eventHandler, text, null);
  }

  /**
   * Create a new action with the given name for this controller
   * @param eventHandler is the action's eventhandler with proper signature
   * @param name is the action's name
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateNamedAction(WDActionEventHandler eventHandler, String name, String text) {
    return wdAlterEgo.createAction(name, eventHandler, text, null);
  }

  // ---- Controller part ------------------------------------------------------

  /**
   * Creates a new instance of this controller.
   */
  public InternalConsulta_CompView(com.sap.tc.webdynpro.progmodel.gci.IGCIView alterEgo) {
    this.wdAlterEgo = alterEgo;
    wdInitContextNode();
    this.delegate = new ar.com.quilmes.consulta.Consulta_CompView((IPrivateConsulta_CompView) this);
    wdAlterEgo.createAction("buscar", WDActionEventHandler.BUSCAR, wdAlterEgo.getLocalizedText("action.Consulta_CompView.buscar"), "");
    wdAlterEgo.createAction("crear", WDActionEventHandler.CREAR, wdAlterEgo.getLocalizedText("action.Consulta_CompView.crear"), "");
  }

  /**
   * Returns the public API for this controller instance.
   */
  public com.sap.tc.webdynpro.progmodel.api.IWDViewController wdGetAPI() {
    return (com.sap.tc.webdynpro.progmodel.api.IWDViewController) wdAlterEgo;
  }

  /**
   * Hook method called to initialize view controller.
   */
  public void wdDoInit() {
    logger.pathT("entering: wdDoInit");
    delegate.wdDoInit();
    logger.pathT("exiting: wdDoInit"); 
  }

  /**
   * Hook method called to clean up view controller.
   */
  public void wdDoExit() {
    logger.pathT("entering: wdDoExit");
    delegate.wdDoExit();
    logger.pathT("exiting: wdDoExit"); 
  }

  public Object wdInvokeEventHandler(String handlerName, IWDCustomEvent event)
    throws NoSuchMethodException {
    
    logger.pathT("entering: wdInvokeEventHandler", new Object[] { handlerName } );
    try {
      if("onPlugentradaconsulta".equals(handlerName)) {

        delegate.onPlugentradaconsulta(event );
        return null;
      }
      if("onActionbuscar".equals(handlerName)) {

        delegate.onActionbuscar(event );
        return null;
      }
      if("onActioncrear".equals(handlerName)) {

        delegate.onActioncrear(event );
        return null;
      }
      throw new NoSuchMethodException("Eventhandler " + handlerName + " not found for event " + event.getName());
    } finally {
      logger.pathT("exiting: wdInvokeEventHandler"); 
    }
  }

  public void onPlugentradaconsulta(IWDCustomEvent wdEvent ) {
    delegate.onPlugentradaconsulta(wdEvent );
  }

  public void onActionbuscar(IWDCustomEvent wdEvent ) {
    delegate.onActionbuscar(wdEvent );
  }

  public void onActioncrear(IWDCustomEvent wdEvent ) {
    delegate.onActioncrear(wdEvent );
  }

  /** outgoing controller usage */
  public ar.com.quilmes.consulta.wdp.IPublicConsulta_WindowInterfaceView wdGetConsulta_WindowInterfaceViewController() {
    return
      (ar.com.quilmes.consulta.wdp.IPublicConsulta_WindowInterfaceView)
        wdAlterEgo
          .getComponentGCI()
            .getPublicInterface("Consulta_WindowInterfaceView");
  }

  /** outgoing controller usage */
  public ar.com.quilmes.consulta.wdp.IPublicConsulta_Comp wdGetConsulta_CompController() {
    return
      (ar.com.quilmes.consulta.wdp.IPublicConsulta_Comp)
        wdAlterEgo
          .getComponentGCI()
            .getPublicInterface("Consulta_Comp");
  }


  // ---- UI Tree ---------------------------------------------------------

  // create UI tree
  public com.sap.tc.webdynpro.progmodel.api.IWDViewElement wdCreateUITree()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _RootUIElementContainer__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout)
        _RootUIElementContainer.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer1());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer2());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer3());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer4());
    return (_RootUIElementContainer);
  }

  // create UI tree for RootUIElementContainer1
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer1()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer1");  
    _RootUIElementContainer1.setWidth("600px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _RootUIElementContainer1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _RootUIElementContainer1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _RootUIElementContainer1__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer1__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer1.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader _PageHeader
      = (com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader.class,
          "PageHeader");  
    _PageHeader.setTitle(wdAlterEgo.getLocalizedText("view.Consulta_CompView.RootUIElementContainer1.PageHeader.Property.title.value"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _PageHeader__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _PageHeader.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer1.addChild(_PageHeader);
    return (_RootUIElementContainer1);
  }
  
  // create UI tree for RootUIElementContainer2
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer2()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer2
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer2");  
    _RootUIElementContainer2.setWidth("600px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _RootUIElementContainer2__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _RootUIElementContainer2.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _RootUIElementContainer2__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer2__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer2.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter3
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter3");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _HorizontalGutter3__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _HorizontalGutter3.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer2.addChild(_HorizontalGutter3);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Label
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class,
          "Label");  
    _Label.setLabelFor("nro_cliente");
    _Label.setText(wdAlterEgo.getLocalizedText("view.Consulta_CompView.RootUIElementContainer2.Label.text"));
    _Label.setWidth("100px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _Label__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _Label.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _Label__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer2.addChild(_Label);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Label1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class,
          "Label1");  
    _Label1.setLabelFor("razon_social");
    _Label1.setText(wdAlterEgo.getLocalizedText("view.Consulta_CompView.RootUIElementContainer2.Label1.text"));
    _Label1.setWidth("200px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _Label1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _Label1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _Label1__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer2.addChild(_Label1);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Label2
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class,
          "Label2");  
    _Label2.setLabelFor("tipo_documento");
    _Label2.setText(wdAlterEgo.getLocalizedText("view.Consulta_CompView.RootUIElementContainer2.Label2.text"));
    _Label2.setWidth("100px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _Label2__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _Label2.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _Label2__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer2.addChild(_Label2);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Label3
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class,
          "Label3");  
    _Label3.setLabelFor("nro_documento");
    _Label3.setText(wdAlterEgo.getLocalizedText("view.Consulta_CompView.RootUIElementContainer2.Label3.text"));
    _Label3.setWidth("100px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _Label3__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _Label3.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _Label3__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer2.addChild(_Label3);
    return (_RootUIElementContainer2);
  }
  
  // create UI tree for RootUIElementContainer3
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer3()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer3
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer3");  
    _RootUIElementContainer3.setWidth("600px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _RootUIElementContainer3__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _RootUIElementContainer3.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _RootUIElementContainer3__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer3__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer3.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField _nro_cliente
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField.class,
          "nro_cliente");  
    _nro_cliente.setAlignment(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDInputFieldAlignment.valueOf("forcedLeft"));
    _nro_cliente.setWidth("100px");
    _nro_cliente.bindValue("nro_cliente");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _nro_cliente__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _nro_cliente.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _nro_cliente__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer3.addChild(_nro_cliente);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField _razon_social
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField.class,
          "razon_social");  
    _razon_social.setAlignment(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDInputFieldAlignment.valueOf("forcedLeft"));
    _razon_social.setWidth("200px");
    _razon_social.setTooltip(wdAlterEgo.getLocalizedText("view.Consulta_CompView.RootUIElementContainer3.razon_social.tooltip"));
    _razon_social.bindValue("razon_social");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _razon_social__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _razon_social.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _razon_social__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer3.addChild(_razon_social);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDDropDownByIndex _tipo_documento
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDDropDownByIndex)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDDropDownByIndex.class,
          "tipo_documento");  
    _tipo_documento.setWidth("80px");
    _tipo_documento.bindTexts("TipoDocumento.desc");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _tipo_documento__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _tipo_documento.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _tipo_documento__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer3.addChild(_tipo_documento);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField _nro_documento
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDInputField.class,
          "nro_documento");  
    _nro_documento.setAlignment(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDInputFieldAlignment.valueOf("forcedLeft"));
    _nro_documento.setWidth("100px");
    _nro_documento.bindValue("nro_documento");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _nro_documento__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _nro_documento.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _nro_documento__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer3.addChild(_nro_documento);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter1");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _HorizontalGutter1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _HorizontalGutter1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer3.addChild(_HorizontalGutter1);
    return (_RootUIElementContainer3);
  }
  
  // create UI tree for RootUIElementContainer4
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer4()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer4
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer4");  
    _RootUIElementContainer4.setWidth("600px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _RootUIElementContainer4__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _RootUIElementContainer4.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _RootUIElementContainer4__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer4__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer4.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _buscar
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class,
          "buscar");  
    _buscar.setWidth("50px");
    _buscar.setText(wdAlterEgo.getLocalizedText("view.Consulta_CompView.RootUIElementContainer4.buscar.text"));
    _buscar.bindEnabled("Ok");
    _buscar.setOnAction(wdAlterEgo.getAction("buscar"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _buscar__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _buscar.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _buscar__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer4.addChild(_buscar);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _crear
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class,
          "crear");  
    _crear.setWidth("50px");
    _crear.setText(wdAlterEgo.getLocalizedText("view.Consulta_CompView.RootUIElementContainer4.crear.text"));
    _crear.bindEnabled("Ok");
    _crear.setOnAction(wdAlterEgo.getAction("crear"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _crear__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _crear.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _crear__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer4.addChild(_crear);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter2
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter2");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _HorizontalGutter2__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _HorizontalGutter2.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer4.addChild(_HorizontalGutter2);
    return (_RootUIElementContainer4);
  }
  

  /**
   * Hook method called to modify view before rendering. Access to UI elements
   * is via the given view API only!
   * 
   * @param firstTime indicates whether the hook is called for the first time
   * during the lifetime of this view
   */
  public void wdDoModifyView(IWDView view, boolean firstTime) {
    logger.pathT("entering: doModifyView");
    ar.com.quilmes.consulta.Consulta_CompView.wdDoModifyView((IPrivateConsulta_CompView) this, (IPrivateConsulta_CompView.IContextNode) this.wdGetContext(), view, firstTime);
    logger.pathT("exiting: doModifyView"); 
  }

  /** outbound plug */
  public void wdFirePlugSalida_consulta( ) {
    Map parameters = Collections.EMPTY_MAP;
    wdAlterEgo.navigate("salida_consulta", parameters);
  }


}
