// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
// ---------------------------------------------------------------------------
package ar.com.quilmes.consulta.wdp;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import com.sap.tc.logging.Location;
import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

public class InternalClientes_View
  implements IPrivateClientes_View, com.sap.tc.webdynpro.progmodel.gci.IGCIViewDelegate
{

  /**
   * Location for this controller.
   */
  private static final Location logger = Location.getLocation(InternalClientes_View.class);

  /**
   * Framework implementation of Controller that delegates to this.
   */
  private final com.sap.tc.webdynpro.progmodel.gci.IGCIView wdAlterEgo;

  /**
   * Delegate that implements application defined logic
   */
  private final ar.com.quilmes.consulta.Clientes_View delegate;


  // ---- Context --------------------------------------------------------------

  IGCINodeInfo infoClientes;
  IGCINodeInfo infoTipoDocumento;
  IGCINodeInfo infoGetCtaCteClienteExecute;
  IGCINodeInfo infoMensajesMensajesItem;
  IGCINodeInfo infoMensajes;
  IGCINodeInfo infoGetCtaCteClienteExecuteResponse;
  IGCINodeInfo infoResponse;
  IGCINodeInfo infoCuentaCorriente;
  IGCINodeInfo infoRol;
  IGCINodeInfo infoContext;

  {

    infoClientes = GCIContext.createMappedNode("Clientes", ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente.class, true, false, false, ".Consulta_Comp.Clientes", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("localidad_Id", "localidad_Id", false),
        GCIContext.createMappedAttribute("razonSocial", "razonSocial", false),
        GCIContext.createMappedAttribute("documento", "documento", false),
        GCIContext.createMappedAttribute("territorio_Id", "territorio_Id", false),
        GCIContext.createMappedAttribute("id", "id", false),
        GCIContext.createMappedAttribute("domicilio", "domicilio", false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoTipoDocumento = GCIContext.createMappedNode("TipoDocumento", ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento.class, true, false, false, ".Consulta_Comp.TipoDocumento", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("id", "id", false),
        GCIContext.createMappedAttribute("desc", "desc", false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoGetCtaCteClienteExecute = GCIContext.createNode("GetCtaCteClienteExecute", ar.com.quilmes.consulta.models_eliminar_cc.GetCtaCteCliente_Execute.class, true, false, false, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("Cliid", "ddic:com.sap.dictionary.integer", null, "Cliid", false, false),
        GCIContext.createAttribute("Pais", "ddic:com.sap.dictionary.string", null, "Pais", false, false),
        GCIContext.createAttribute("Empid", "ddic:com.sap.dictionary.short", null, "Empid", false, false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoMensajesMensajesItem = GCIContext.createNode("MensajesMensajesItem", ar.com.quilmes.consulta.models_eliminar_cc.MensajesMensajesItem.class, true, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("MsgErrDesc", "ddic:com.sap.dictionary.string", null, "MsgErrDesc", false, false),
        GCIContext.createAttribute("MsgErrCode", "ddic:com.sap.dictionary.short", null, "MsgErrCode", false, false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoMensajes = GCIContext.createNode("Mensajes", ar.com.quilmes.consulta.models_eliminar_cc.Mensajes.class, true, true, false, false, false, true, null,
      (IGCIAttributeInfo[])null, // no attributes
      new IGCINodeInfo[] {
        infoMensajesMensajesItem,
      }
    );

    infoGetCtaCteClienteExecuteResponse = GCIContext.createNode("GetCtaCteClienteExecuteResponse", ar.com.quilmes.consulta.models_eliminar_cc.GetCtaCteCliente_ExecuteResponse.class, true, false, false, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("Clisdodoct", "ddic:com.sap.dictionary.double", null, "Clisdodoct", false, false),
        GCIContext.createAttribute("Totrech", "ddic:com.sap.dictionary.double", null, "Totrech", false, false),
        GCIContext.createAttribute("Sdoped", "ddic:com.sap.dictionary.double", null, "Sdoped", false, false),
        GCIContext.createAttribute("Fmapgoabv", "ddic:com.sap.dictionary.string", null, "Fmapgoabv", false, false),
        GCIContext.createAttribute("Clisdoctc", "ddic:com.sap.dictionary.double", null, "Clisdoctc", false, false),
        GCIContext.createAttribute("Totvenc", "ddic:com.sap.dictionary.double", null, "Totvenc", false, false),
      },
      new IGCINodeInfo[] {
        infoMensajes,
      }
    );

    infoResponse = GCIContext.createNode("Response", ar.com.quilmes.consulta.models_eliminar_cc.Response_Execute.class, true, false, false, false, false, true, null,
      (IGCIAttributeInfo[])null, // no attributes
      new IGCINodeInfo[] {
        infoGetCtaCteClienteExecuteResponse,
      }
    );

    infoCuentaCorriente = GCIContext.createNode("CuentaCorriente", ar.com.quilmes.consulta.models_eliminar_cc.Request_Execute.class, true, false, true, false, false, true, null,
      (IGCIAttributeInfo[])null, // no attributes
      new IGCINodeInfo[] {
        infoGetCtaCteClienteExecute,
        infoResponse,
      }
    );

    infoRol = GCIContext.createNode("Rol", ar.com.quilmes.bue.mdm_clientes.model.internas.Rol.class, true, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("tipoCobranza", "ddic:com.sap.dictionary.integerObject", null, "tipoCobranza", false, false),
        GCIContext.createAttribute("formaPago", "ddic:com.sap.dictionary.integerObject", null, "formaPago", false, false),
        GCIContext.createAttribute("perfilCliente", "ddic:com.sap.dictionary.string", null, "perfilCliente", false, false),
        GCIContext.createAttribute("segmentoVta", "ddic:com.sap.dictionary.integerObject", null, "segmentoVta", false, false),
        GCIContext.createAttribute("pagaSeguro", "ddic:com.sap.dictionary.string", null, "pagaSeguro", false, false),
        GCIContext.createAttribute("tipoVtaFalSobMerc", "ddic:com.sap.dictionary.integerObject", null, "tipoVtaFalSobMerc", false, false),
        GCIContext.createAttribute("tipoClienteContable", "ddic:com.sap.dictionary.integerObject", null, "tipoClienteContable", false, false),
        GCIContext.createAttribute("tienePromocion", "ddic:com.sap.dictionary.string", null, "tienePromocion", false, false),
        GCIContext.createAttribute("listaPrecioMaximo", "ddic:com.sap.dictionary.integerObject", null, "listaPrecioMaximo", false, false),
        GCIContext.createAttribute("imprimeRemito", "ddic:com.sap.dictionary.string", null, "imprimeRemito", false, false),
        GCIContext.createAttribute("listaPrecioBasico", "ddic:com.sap.dictionary.integerObject", null, "listaPrecioBasico", false, false),
        GCIContext.createAttribute("tipoEmpresa", "ddic:com.sap.dictionary.string", null, "tipoEmpresa", false, false),
        GCIContext.createAttribute("tipoVtaFalSobEnv", "ddic:com.sap.dictionary.integerObject", null, "tipoVtaFalSobEnv", false, false),
        GCIContext.createAttribute("esExclusivo", "ddic:com.sap.dictionary.string", null, "esExclusivo", false, false),
        GCIContext.createAttribute("sociedad", "ddic:com.sap.dictionary.string", null, "sociedad", false, false),
        GCIContext.createAttribute("aceptaDesdUnifPedidos", "ddic:com.sap.dictionary.string", null, "aceptaDesdUnifPedidos", false, false),
        GCIContext.createAttribute("formaEntregaCtaCte", "ddic:com.sap.dictionary.string", null, "formaEntregaCtaCte", false, false),
        GCIContext.createAttribute("canalVenta", "ddic:com.sap.dictionary.integerObject", null, "canalVenta", false, false),
        GCIContext.createAttribute("esquema", "ddic:com.sap.dictionary.string", null, "esquema", false, false),
        GCIContext.createAttribute("formaAtencion", "ddic:com.sap.dictionary.integerObject", null, "formaAtencion", false, false),
        GCIContext.createAttribute("agrupacionComercial", "ddic:com.sap.dictionary.integerObject", null, "agrupacionComercial", false, false),
        GCIContext.createAttribute("polVentaCal1", "ddic:com.sap.dictionary.integerObject", null, "polVentaCal1", false, false),
        GCIContext.createAttribute("ramo", "ddic:com.sap.dictionary.integerObject", null, "ramo", false, false),
        GCIContext.createAttribute("banco", "ddic:com.sap.dictionary.integerObject", null, "banco", false, false),
        GCIContext.createAttribute("ctaCteExterna", "ddic:com.sap.dictionary.string", null, "ctaCteExterna", false, false),
        GCIContext.createAttribute("cobrador", "ddic:com.sap.dictionary.string", null, "cobrador", false, false),
        GCIContext.createAttribute("personeriaJuridica", "ddic:com.sap.dictionary.string", null, "personeriaJuridica", false, false),
        GCIContext.createAttribute("tipoClienteCondVta", "ddic:com.sap.dictionary.integerObject", null, "tipoClienteCondVta", false, false),
        GCIContext.createAttribute("tipoMaqVend", "ddic:com.sap.dictionary.string", null, "tipoMaqVend", false, false),
        GCIContext.createAttribute("polVentaCal3", "ddic:com.sap.dictionary.integerObject", null, "polVentaCal3", false, false),
        GCIContext.createAttribute("identificacionJuridica", "ddic:com.sap.dictionary.string", null, "identificacionJuridica", false, false),
        GCIContext.createAttribute("moneda", "ddic:com.sap.dictionary.string", null, "moneda", false, false),
        GCIContext.createAttribute("tipoCliCom", "ddic:com.sap.dictionary.integerObject", null, "tipoCliCom", false, false),
        GCIContext.createAttribute("nroImpuestoInterno", "ddic:com.sap.dictionary.string", null, "nroImpuestoInterno", false, false),
        GCIContext.createAttribute("asigStock", "ddic:com.sap.dictionary.integerObject", null, "asigStock", false, false),
        GCIContext.createAttribute("comprador", "ddic:com.sap.dictionary.string", null, "comprador", false, false),
        GCIContext.createAttribute("fueCensado", "ddic:com.sap.dictionary.string", null, "fueCensado", false, false),
        GCIContext.createAttribute("polVentaCal2", "ddic:com.sap.dictionary.integerObject", null, "polVentaCal2", false, false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoContext = GCIContext.createNode("Context", null, true, true, false, true, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("nro_cli", ".Consulta_Comp.nro_cliente", false),
        GCIContext.createMappedAttribute("nro_doc", ".Consulta_Comp.nro_documento", false),
        GCIContext.createMappedAttribute("razon_soc", ".Consulta_Comp.razon_social", false),
        GCIContext.createAttribute("habilitar", "ddic:com.sap.dictionary.boolean", null, null, false, false),
        GCIContext.createAttribute("usuario", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("pais", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("empresa", "ddic:com.sap.dictionary.short", null, null, false, false),
      },
      new IGCINodeInfo[] {
        infoClientes,
        infoTipoDocumento,
        infoCuentaCorriente,
        infoRol,
      }
    );

  }
  
  private IContextNode contextNode;

  private void wdInitContextNode() {
    contextNode = new IContextNode(this, infoContext, (Node)null);
  }

  public IWDNode wdGetRootNode() {
    return contextNode;
  }

  public IContextNode wdGetContext() {
    return contextNode;
  }


  // ---- Actions --------------------------------------------------------------

  /**
   * Returns the action with name <code>volver</code>.
   */
  public IWDAction wdGetVolverAction() {
    return wdAlterEgo.getAction("volver");
  }

  /**
   * Returns the action with name <code>modificar</code>.
   */
  public IWDAction wdGetModificarAction() {
    return wdAlterEgo.getAction("modificar");
  }

  /**
   * Returns the action with name <code>eliminar</code>.
   */
  public IWDAction wdGetEliminarAction() {
    return wdAlterEgo.getAction("eliminar");
  }

  /**
   * Create a new action for this controller. A unique name for the action is generated automatially.
   * @param eventHandler is the action's eventhandler with proper signature
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateAction(WDActionEventHandler eventHandler, String text) {
    return wdAlterEgo.createAction(null, eventHandler, text, null);
  }

  /**
   * Create a new action with the given name for this controller
   * @param eventHandler is the action's eventhandler with proper signature
   * @param name is the action's name
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateNamedAction(WDActionEventHandler eventHandler, String name, String text) {
    return wdAlterEgo.createAction(name, eventHandler, text, null);
  }

  // ---- Controller part ------------------------------------------------------

  /**
   * Creates a new instance of this controller.
   */
  public InternalClientes_View(com.sap.tc.webdynpro.progmodel.gci.IGCIView alterEgo) {
    this.wdAlterEgo = alterEgo;
    wdInitContextNode();
    this.delegate = new ar.com.quilmes.consulta.Clientes_View((IPrivateClientes_View) this);
    wdAlterEgo.createAction("volver", WDActionEventHandler.VOLVER, wdAlterEgo.getLocalizedText("action.Clientes_View.volver"), "");
    wdAlterEgo.createAction("modificar", WDActionEventHandler.MODIFICAR, wdAlterEgo.getLocalizedText("action.Clientes_View.modificar"), "");
    wdAlterEgo.createAction("eliminar", WDActionEventHandler.ELIMINAR, wdAlterEgo.getLocalizedText("action.Clientes_View.eliminar"), "");
  }

  /**
   * Returns the public API for this controller instance.
   */
  public com.sap.tc.webdynpro.progmodel.api.IWDViewController wdGetAPI() {
    return (com.sap.tc.webdynpro.progmodel.api.IWDViewController) wdAlterEgo;
  }

  /**
   * Hook method called to initialize view controller.
   */
  public void wdDoInit() {
    logger.pathT("entering: wdDoInit");
    delegate.wdDoInit();
    logger.pathT("exiting: wdDoInit"); 
  }

  /**
   * Hook method called to clean up view controller.
   */
  public void wdDoExit() {
    logger.pathT("entering: wdDoExit");
    delegate.wdDoExit();
    logger.pathT("exiting: wdDoExit"); 
  }

  public Object wdInvokeEventHandler(String handlerName, IWDCustomEvent event)
    throws NoSuchMethodException {
    
    logger.pathT("entering: wdInvokeEventHandler", new Object[] { handlerName } );
    try {
      if("onPlugentradaclientes".equals(handlerName)) {

        delegate.onPlugentradaclientes(event );
        return null;
      }
      if("onActionvolver".equals(handlerName)) {

        delegate.onActionvolver(event );
        return null;
      }
      if("onActionmodificar".equals(handlerName)) {

        delegate.onActionmodificar(event );
        return null;
      }
      if("onActioneliminar".equals(handlerName)) {

        delegate.onActioneliminar(event );
        return null;
      }
      throw new NoSuchMethodException("Eventhandler " + handlerName + " not found for event " + event.getName());
    } finally {
      logger.pathT("exiting: wdInvokeEventHandler"); 
    }
  }

  public void onPlugentradaclientes(IWDCustomEvent wdEvent ) {
    delegate.onPlugentradaclientes(wdEvent );
  }

  public void onActionvolver(IWDCustomEvent wdEvent ) {
    delegate.onActionvolver(wdEvent );
  }

  public void onActionmodificar(IWDCustomEvent wdEvent ) {
    delegate.onActionmodificar(wdEvent );
  }

  public void onActioneliminar(IWDCustomEvent wdEvent ) {
    delegate.onActioneliminar(wdEvent );
  }

  /** outgoing controller usage */
  public ar.com.quilmes.consulta.wdp.IPublicConsulta_WindowInterfaceView wdGetConsulta_WindowInterfaceViewController() {
    return
      (ar.com.quilmes.consulta.wdp.IPublicConsulta_WindowInterfaceView)
        wdAlterEgo
          .getComponentGCI()
            .getPublicInterface("Consulta_WindowInterfaceView");
  }

  /** outgoing controller usage */
  public ar.com.quilmes.consulta.wdp.IPublicConsulta_Comp wdGetConsulta_CompController() {
    return
      (ar.com.quilmes.consulta.wdp.IPublicConsulta_Comp)
        wdAlterEgo
          .getComponentGCI()
            .getPublicInterface("Consulta_Comp");
  }


  // ---- UI Tree ---------------------------------------------------------

  // create UI tree
  public com.sap.tc.webdynpro.progmodel.api.IWDViewElement wdCreateUITree()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _RootUIElementContainer__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout)
        _RootUIElementContainer.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer1());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer2());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer3());
    return (_RootUIElementContainer);
  }

  // create UI tree for RootUIElementContainer1
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer1()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer1");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _RootUIElementContainer1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _RootUIElementContainer1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _RootUIElementContainer1__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer1__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer1.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader _PageHeader
      = (com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader.class,
          "PageHeader");  
    _PageHeader.setTitle(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer1.PageHeader.Property.title.value"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _PageHeader__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _PageHeader.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer1.addChild(_PageHeader);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter1");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _HorizontalGutter1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _HorizontalGutter1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer1.addChild(_HorizontalGutter1);
    return (_RootUIElementContainer1);
  }
  
  // create UI tree for RootUIElementContainer2
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer2()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer2
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer2");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _RootUIElementContainer2__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _RootUIElementContainer2.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _RootUIElementContainer2__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer2__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer2.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable _Table
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable.class,
          "Table");  
    _Table.setVisibleRowCount(10);
    _Table.bindDataSource("Clientes");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _Table__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _Table.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn _id_0_0
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn.class,
          "id_0_0");  

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _id_0_0_header
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "id_0_0_header");  
    _id_0_0_header.setText(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer2.Table.OutgoingAggregation.GroupedColumns.AggregatedObject.id_0_0.Header.text"));
    _id_0_0.setHeader(_id_0_0_header);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView _id_0_0_editor
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView.class,
          "id_0_0_editor");  
    _id_0_0_editor.bindText("Clientes.id");
    _id_0_0.setTableCellEditor(_id_0_0_editor);
    _Table.addGroupedColumn(_id_0_0);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn _razonSocial_0_0
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn.class,
          "razonSocial_0_0");  

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _razonSocial_0_0_header
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "razonSocial_0_0_header");  
    _razonSocial_0_0_header.setText(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer2.Table.OutgoingAggregation.GroupedColumns.AggregatedObject.razonSocial_0_0.Header.text"));
    _razonSocial_0_0.setHeader(_razonSocial_0_0_header);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView _razonSocial_0_0_editor
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView.class,
          "razonSocial_0_0_editor");  
    _razonSocial_0_0_editor.bindText("Clientes.razonSocial");
    _razonSocial_0_0.setTableCellEditor(_razonSocial_0_0_editor);
    _Table.addGroupedColumn(_razonSocial_0_0);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn _documento_0_0
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn.class,
          "documento_0_0");  

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _documento_0_0_header
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "documento_0_0_header");  
    _documento_0_0_header.setText(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer2.Table.OutgoingAggregation.GroupedColumns.AggregatedObject.documento_0_0.Header.text"));
    _documento_0_0.setHeader(_documento_0_0_header);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView _documento_0_0_editor
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView.class,
          "documento_0_0_editor");  
    _documento_0_0_editor.bindText("Clientes.documento");
    _documento_0_0.setTableCellEditor(_documento_0_0_editor);
    _Table.addGroupedColumn(_documento_0_0);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn _localidad_Id_0_0
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn.class,
          "localidad_Id_0_0");  

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _localidad_Id_0_0_header
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "localidad_Id_0_0_header");  
    _localidad_Id_0_0_header.setText(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer2.Table.OutgoingAggregation.GroupedColumns.AggregatedObject.localidad_Id_0_0.Header.text"));
    _localidad_Id_0_0.setHeader(_localidad_Id_0_0_header);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView _localidad_Id_0_0_editor
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView.class,
          "localidad_Id_0_0_editor");  
    _localidad_Id_0_0_editor.bindText("Clientes.localidad_Id");
    _localidad_Id_0_0.setTableCellEditor(_localidad_Id_0_0_editor);
    _Table.addGroupedColumn(_localidad_Id_0_0);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn _domicilio_0_0
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn.class,
          "domicilio_0_0");  

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _domicilio_0_0_header
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "domicilio_0_0_header");  
    _domicilio_0_0_header.setText(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer2.Table.OutgoingAggregation.GroupedColumns.AggregatedObject.domicilio_0_0.Header.text"));
    _domicilio_0_0.setHeader(_domicilio_0_0_header);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView _domicilio_0_0_editor
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView.class,
          "domicilio_0_0_editor");  
    _domicilio_0_0_editor.bindText("Clientes.domicilio");
    _domicilio_0_0.setTableCellEditor(_domicilio_0_0_editor);
    _Table.addGroupedColumn(_domicilio_0_0);
    _RootUIElementContainer2.addChild(_Table);
    return (_RootUIElementContainer2);
  }
  
  // create UI tree for RootUIElementContainer3
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer3()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer3
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer3");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _RootUIElementContainer3__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _RootUIElementContainer3.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _RootUIElementContainer3__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer3__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer3.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _HorizontalGutter__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _HorizontalGutter.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer3.addChild(_HorizontalGutter);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _modificar
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class,
          "modificar");  
    _modificar.setWidth("50px");
    _modificar.setText(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer3.modificar.text"));
    _modificar.bindEnabled("habilitar");
    _modificar.setOnAction(wdAlterEgo.getAction("modificar"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _modificar__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _modificar.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _modificar__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer3.addChild(_modificar);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _eliminar
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class,
          "eliminar");  
    _eliminar.setWidth("50px");
    _eliminar.setText(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer3.eliminar.text"));
    _eliminar.bindEnabled("habilitar");
    _eliminar.setOnAction(wdAlterEgo.getAction("eliminar"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _eliminar__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _eliminar.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _eliminar__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer3.addChild(_eliminar);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _volver
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class,
          "volver");  
    _volver.setWidth("50px");
    _volver.setText(wdAlterEgo.getLocalizedText("view.Clientes_View.RootUIElementContainer3.volver.text"));
    _volver.setOnAction(wdAlterEgo.getAction("volver"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _volver__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _volver.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _volver__LayoutData.setPaddingRight("7px");
    _RootUIElementContainer3.addChild(_volver);
    return (_RootUIElementContainer3);
  }
  

  /**
   * Hook method called to modify view before rendering. Access to UI elements
   * is via the given view API only!
   * 
   * @param firstTime indicates whether the hook is called for the first time
   * during the lifetime of this view
   */
  public void wdDoModifyView(IWDView view, boolean firstTime) {
    logger.pathT("entering: doModifyView");
    ar.com.quilmes.consulta.Clientes_View.wdDoModifyView((IPrivateClientes_View) this, (IPrivateClientes_View.IContextNode) this.wdGetContext(), view, firstTime);
    logger.pathT("exiting: doModifyView"); 
  }

  /** outbound plug */
  public void wdFirePlugSalidaclientes_b( ) {
    Map parameters = Collections.EMPTY_MAP;
    wdAlterEgo.navigate("salidaclientes_b", parameters);
  }

  /** outbound plug */
  public void wdFirePlugSalidaclientes( ) {
    Map parameters = Collections.EMPTY_MAP;
    wdAlterEgo.navigate("salidaclientes", parameters);
  }

  /** outbound plug */
  public void wdFirePlugSalidaclientes_m( ) {
    Map parameters = Collections.EMPTY_MAP;
    wdAlterEgo.navigate("salidaclientes_m", parameters);
  }


}
