// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
// ---------------------------------------------------------------------------
package ar.com.quilmes.consulta.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

/** Interface that is provided to application class. */

public interface IPrivateConsulta_CompView {

  /*
   * Event Handler identifiers.
   */ 
    
  /** Event handler constant. */
  public static IWDEventHandlerId WD_EVENTHANDLER_ON_PLUGENTRADACONSULTA = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventHandlerId("onPlugentradaconsulta", "Consulta_CompView", "ar.com.quilmes.consulta.Consulta_Comp");
  
  /** Event handler constant. */
  public static IWDEventHandlerId WD_EVENTHANDLER_ON_ACTIONBUSCAR = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventHandlerId("onActionbuscar", "Consulta_CompView", "ar.com.quilmes.consulta.Consulta_Comp");
  
  /** Event handler constant. */
  public static IWDEventHandlerId WD_EVENTHANDLER_ON_ACTIONCREAR = new com.sap.tc.webdynpro.progmodel.gci.impl.GCIEventHandlerId("onActioncrear", "Consulta_CompView", "ar.com.quilmes.consulta.Consulta_Comp");
  
  /**
   * Provides access to the generic API of this controller.
   */
  IWDViewController wdGetAPI();


  /**
   * Interface for the node 'Context'.
   *
   * singleton = true, cardinality = _1_1, selection = _1_1
   */
  public static class IContextNode extends Node
  {
    private InternalConsulta_CompView gen_delegate;

    IContextNode(InternalConsulta_CompView delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    protected com.sap.tc.webdynpro.progmodel.context.Node createNode(IGCINodeInfo nodeInfo, com.sap.tc.webdynpro.progmodel.context.Node parentNode, com.sap.tc.webdynpro.progmodel.context.NodeElement parentElement) {
      if (nodeInfo == gen_delegate.infoContext)
        return new IPrivateConsulta_CompView.IContextNode(gen_delegate, nodeInfo, parentNode);
      if (nodeInfo == gen_delegate.infoTipoDocumento)
        return new IPrivateConsulta_CompView.ITipoDocumentoNode(gen_delegate, nodeInfo, parentNode);
      if (nodeInfo == gen_delegate.infoRol)
        return new IPrivateConsulta_CompView.IRolNode(gen_delegate, nodeInfo, parentNode);
      return super.createNode(nodeInfo, parentNode, parentElement);
    }

    protected com.sap.tc.webdynpro.progmodel.context.NodeElement doCreateElement(IGCINodeInfo nodeInfo, Object reference) {
      if (nodeInfo == gen_delegate.infoContext) {
        return new IPrivateConsulta_CompView.IContextElement(gen_delegate, nodeInfo);
      }
      if (nodeInfo == gen_delegate.infoTipoDocumento) {
        return new IPrivateConsulta_CompView.ITipoDocumentoElement(gen_delegate, nodeInfo, reference);
      }
      if (nodeInfo == gen_delegate.infoRol) {
        return new IPrivateConsulta_CompView.IRolElement(gen_delegate, nodeInfo, reference);
      }
      return super.doCreateElement(nodeInfo, reference);
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Provides access to the generic context API as described by IWDContext.
     */
    public IWDContext wdGetAPI() {
      return getContext();
    }

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IContextElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @return an element for this node
     */
    public IPrivateConsulta_CompView.IContextElement createContextElement() {
      return (IPrivateConsulta_CompView.IContextElement)createElement();
    }

    /**
     * Binds a single IContextElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateConsulta_CompView.IContextElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateConsulta_CompView.IContextElement currentContextElement() {
      return (IPrivateConsulta_CompView.IContextElement) getCurrentElement();
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

    private IPrivateConsulta_CompView.ITipoDocumentoNode gen_nodeTipoDocumento;
    
    /**
     * Returns the singleton child node TipoDocumento.
     * @return the child node
     */
    public IPrivateConsulta_CompView.ITipoDocumentoNode nodeTipoDocumento() {
      if (gen_nodeTipoDocumento == null)
        gen_nodeTipoDocumento = (IPrivateConsulta_CompView.ITipoDocumentoNode) getChildNode("TipoDocumento");
      return gen_nodeTipoDocumento;
    }

    /**
     * Returns the current (lead selection) element of the singleton child node
     * TipoDocumento.
     * @return the child node element or <code>null</code> if no such element 
     *         exists
     */
    public IPrivateConsulta_CompView.ITipoDocumentoElement currentTipoDocumentoElement() {
      return (IPrivateConsulta_CompView.ITipoDocumentoElement) nodeTipoDocumento().getCurrentElement();
    }

    public IPrivateConsulta_CompView.ITipoDocumentoElement createTipoDocumentoElement(ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento model) {
      return (IPrivateConsulta_CompView.ITipoDocumentoElement) doCreateElement(gen_delegate.infoTipoDocumento, model);
    }

    private IPrivateConsulta_CompView.IRolNode gen_nodeRol;
    
    /**
     * Returns the singleton child node Rol.
     * @return the child node
     */
    public IPrivateConsulta_CompView.IRolNode nodeRol() {
      if (gen_nodeRol == null)
        gen_nodeRol = (IPrivateConsulta_CompView.IRolNode) getChildNode("Rol");
      return gen_nodeRol;
    }

    /**
     * Returns the current (lead selection) element of the singleton child node
     * Rol.
     * @return the child node element or <code>null</code> if no such element 
     *         exists
     */
    public IPrivateConsulta_CompView.IRolElement currentRolElement() {
      return (IPrivateConsulta_CompView.IRolElement) nodeRol().getCurrentElement();
    }

    public IPrivateConsulta_CompView.IRolElement createRolElement(ar.com.quilmes.bue.mdm_clientes.model.internas.Rol model) {
      return (IPrivateConsulta_CompView.IRolElement) doCreateElement(gen_delegate.infoRol, model);
    }

  }

  /**
   * Interface for the elements of the node Context.
   */
  public static class IContextElement extends com.sap.tc.webdynpro.progmodel.context.NodeElement
  {
    private InternalConsulta_CompView gen_delegate;

    public IContextElement(InternalConsulta_CompView delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info) {
      super(info);
      gen_delegate = delegate;
    }

    // attribute "nro_cliente"
    public final static String NRO__CLIENTE = "nro_cliente";

    private MappedAttribute _nro_cliente;

    /**
     * Returns the attribute nro_cliente.
     */
    public int getNro_cliente() {
      if (_nro_cliente == null)
        _nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
      return _nro_cliente.getInt();
    }

    /**
     * Sets the attribute nro_cliente.
     * @param value the new value
     */
    public void setNro_cliente(int value) {
      if (this._nro_cliente == null)
        this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
      this._nro_cliente.setInt(value);
    }
    
    // attribute "razon_social"
    public final static String RAZON__SOCIAL = "razon_social";

    private MappedAttribute _razon_social;

    /**
     * Returns the attribute razon_social.
     */
    public java.lang.String getRazon_social() {
      if (_razon_social == null)
        _razon_social = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("razon_social"), this);
      return _razon_social.getString();
    }

    /**
     * Sets the attribute razon_social.
     * @param value the new value
     */
    public void setRazon_social(java.lang.String value) {
      if (this._razon_social == null)
        this._razon_social = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("razon_social"), this);
      this._razon_social.setString(value);
    }
    
    // attribute "nro_documento"
    public final static String NRO__DOCUMENTO = "nro_documento";

    private MappedAttribute _nro_documento;

    /**
     * Returns the attribute nro_documento.
     */
    public java.lang.String getNro_documento() {
      if (_nro_documento == null)
        _nro_documento = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_documento"), this);
      return _nro_documento.getString();
    }

    /**
     * Sets the attribute nro_documento.
     * @param value the new value
     */
    public void setNro_documento(java.lang.String value) {
      if (this._nro_documento == null)
        this._nro_documento = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_documento"), this);
      this._nro_documento.setString(value);
    }
    
    // attribute "Ok"
    public final static String OK = "Ok";

    private boolean _ok;

    /**
     * Returns the attribute Ok.
     */
    public boolean getOk() {
      return _ok;
    }

    /**
     * Sets the attribute Ok.
     * @param value the new value
     */
    public void setOk(boolean value) {
      this._ok = value;
      changed(3);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          if (this._nro_cliente == null)
            this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
          return _nro_cliente.getObject();
        case 1: // razon_social
          if (this._razon_social == null)
            this._razon_social = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("razon_social"), this);
          return _razon_social.getObject();
        case 2: // nro_documento
          if (this._nro_documento == null)
            this._nro_documento = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_documento"), this);
          return _nro_documento.getObject();
        case 3: // Ok
          return new Boolean(_ok);
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          if (this._nro_cliente == null)
            this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
          this._nro_cliente.setObject(value);
          break;
        case 1: // razon_social
          if (this._razon_social == null)
            this._razon_social = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("razon_social"), this);
          this._razon_social.setObject(value);
          break;
        case 2: // nro_documento
          if (this._nro_documento == null)
            this._nro_documento = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_documento"), this);
          this._nro_documento.setObject(value);
          break;
        case 3: // Ok
          this._ok = ((Boolean)value).booleanValue();
          changed(info);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected boolean wdGetBoolean(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 3: // Ok
          return _ok;
        default:
          return super.wdGetBoolean(info);
      }
    }

    protected void wdSetBoolean(IGCIAttributeInfo info, boolean value) {
      switch (info.getIndex()) {
        case 3: // Ok
          this._ok = (boolean)value;
          changed(info);
          break;
        default:
          super.wdSetBoolean(info, value);
          break;
      }
    }

    protected int wdGetInt(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          if (this._nro_cliente == null)
            this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
          return _nro_cliente.getInt();
        default:
          return super.wdGetInt(info);
      }
    }

    protected void wdSetInt(IGCIAttributeInfo info, int value) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          if (this._nro_cliente == null)
            this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
          this._nro_cliente.setInt(value);
          break;
        default:
          super.wdSetInt(info, value);
          break;
      }
    }

    protected String wdGetString(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 1: // razon_social
          if (this._razon_social == null)
            this._razon_social = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("razon_social"), this);
          return _razon_social.getString();
        case 2: // nro_documento
          if (this._nro_documento == null)
            this._nro_documento = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_documento"), this);
          return _nro_documento.getString();
        default:
          return super.wdGetString(info);
      }
    }

    protected void wdSetString(IGCIAttributeInfo info, String value) {
      switch (info.getIndex()) {
        case 1: // razon_social
          if (this._razon_social == null)
            this._razon_social = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("razon_social"), this);
          this._razon_social.setString(value);
          break;
        case 2: // nro_documento
          if (this._nro_documento == null)
            this._nro_documento = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_documento"), this);
          this._nro_documento.setString(value);
          break;
        default:
          super.wdSetString(info, value);
          break;
      }
    }

  }


  /**
   * Interface for the node 'TipoDocumento'.
   *
   * singleton = true, cardinality = _0_n, selection = _0_1
   */
  public static class ITipoDocumentoNode extends Node
  {
    private InternalConsulta_CompView gen_delegate;

    ITipoDocumentoNode(InternalConsulta_CompView delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(ITipoDocumentoElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @param model an instance of ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento needed for this model element
     * @return an element for this node
     */
    public IPrivateConsulta_CompView.ITipoDocumentoElement createTipoDocumentoElement(ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento model) {
      return (IPrivateConsulta_CompView.ITipoDocumentoElement)createElement(model);
    }

    /**
     * Binds a single ITipoDocumentoElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateConsulta_CompView.ITipoDocumentoElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /**
     * Creates a new ITipoDocumentoElement with the given model object 
     * and binds it to this node.
     * @param model an object of the model class
     */
    public void bind(ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento model) {
      bind(model == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(model));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateConsulta_CompView.ITipoDocumentoElement currentTipoDocumentoElement() {
      return (IPrivateConsulta_CompView.ITipoDocumentoElement) getCurrentElement();
    }

    /** 
     * Returns the element at the given index.
     * @param index the index of the element you want to get
     * @return the element or <code>null</code> if no element
     *         exists at that index
     */
    public IPrivateConsulta_CompView.ITipoDocumentoElement getTipoDocumentoElementAt(int index) {
      return (IPrivateConsulta_CompView.ITipoDocumentoElement) getElementAt(index);
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node TipoDocumento.
   */
  public static class ITipoDocumentoElement extends com.sap.tc.webdynpro.progmodel.context.MappedNodeElement
  {
    private InternalConsulta_CompView gen_delegate;

    public ITipoDocumentoElement(InternalConsulta_CompView delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info, Object reference) {
      super(info, reference);
      gen_delegate = delegate;
    }

    /**
     * Returns the referenced element of the mapped node.
     * @return the referenced element
     */
    public ar.com.quilmes.consulta.wdp.IPublicConsulta_Comp.ITipoDocumentoElement mappedTipoDocumentoElement() {
      return (ar.com.quilmes.consulta.wdp.IPublicConsulta_Comp.ITipoDocumentoElement)wdGetMappedElement();
    }

    /**
     * Returns the referenced ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento.
     * @return the referenced ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento
     */
    public ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento modelObject() {
      return (ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento)model();
    }
    
    // attribute "id"
    public final static String ID = "id";

    /**
     * Returns the attribute id.
     */
    public int getId() {
      return wdGetInt(wdGetNodeInfoGCI().getAttributeGCI(0));
    }

    /**
     * Sets the attribute id.
     * @param value the new value
     */
    public void setId(int value) {
      wdSetInt(wdGetNodeInfoGCI().getAttributeGCI(0), value);
    }
    
    // attribute "desc"
    public final static String DESC = "desc";

    /**
     * Returns the attribute desc.
     */
    public java.lang.String getDesc() {
      return wdGetString(wdGetNodeInfoGCI().getAttributeGCI(1));
    }

    /**
     * Sets the attribute desc.
     * @param value the new value
     */
    public void setDesc(java.lang.String value) {
      wdSetString(wdGetNodeInfoGCI().getAttributeGCI(1), value);
    }
    
  }


  /**
   * Interface for the node 'Rol'.
   *
   * singleton = true, cardinality = _0_n, selection = _0_1
   */
  public static class IRolNode extends Node
  {
    private InternalConsulta_CompView gen_delegate;

    IRolNode(InternalConsulta_CompView delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IRolElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @param model an instance of ar.com.quilmes.bue.mdm_clientes.model.internas.Rol needed for this model element
     * @return an element for this node
     */
    public IPrivateConsulta_CompView.IRolElement createRolElement(ar.com.quilmes.bue.mdm_clientes.model.internas.Rol model) {
      return (IPrivateConsulta_CompView.IRolElement)createElement(model);
    }

    /**
     * Binds a single IRolElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateConsulta_CompView.IRolElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /**
     * Creates a new IRolElement with the given model object 
     * and binds it to this node.
     * @param model an object of the model class
     */
    public void bind(ar.com.quilmes.bue.mdm_clientes.model.internas.Rol model) {
      bind(model == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(model));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateConsulta_CompView.IRolElement currentRolElement() {
      return (IPrivateConsulta_CompView.IRolElement) getCurrentElement();
    }

    /** 
     * Returns the element at the given index.
     * @param index the index of the element you want to get
     * @return the element or <code>null</code> if no element
     *         exists at that index
     */
    public IPrivateConsulta_CompView.IRolElement getRolElementAt(int index) {
      return (IPrivateConsulta_CompView.IRolElement) getElementAt(index);
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node Rol.
   */
  public static class IRolElement extends com.sap.tc.webdynpro.progmodel.context.ModelNodeElement
  {
    private InternalConsulta_CompView gen_delegate;

    private final ar.com.quilmes.bue.mdm_clientes.model.internas.Rol gen_modelInstance;

    public IRolElement(InternalConsulta_CompView delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info, Object modelInstance) {
      super(info, modelInstance);
      this.gen_modelInstance = (ar.com.quilmes.bue.mdm_clientes.model.internas.Rol) modelInstance;
      gen_delegate = delegate;
    }

    /**
     * Returns the referenced ar.com.quilmes.bue.mdm_clientes.model.internas.Rol.
     * @return the referenced ar.com.quilmes.bue.mdm_clientes.model.internas.Rol
     */
    public ar.com.quilmes.bue.mdm_clientes.model.internas.Rol modelObject() {
      return gen_modelInstance;
    }

    // attribute "tipoCobranza"
    public final static String TIPO_COBRANZA = "tipoCobranza";

    /**
     * Returns the attribute tipoCobranza.
     */
    public java.lang.Integer getTipoCobranza() {
      return gen_modelInstance.getTipoCobranza();
    }

    /**
     * Sets the attribute tipoCobranza.
     * @param value the new value
     */
    public void setTipoCobranza(java.lang.Integer value) {
      gen_modelInstance.setTipoCobranza(value);
      changed(0);
    }
    
    // attribute "formaPago"
    public final static String FORMA_PAGO = "formaPago";

    /**
     * Returns the attribute formaPago.
     */
    public java.lang.Integer getFormaPago() {
      return gen_modelInstance.getFormaPago();
    }

    /**
     * Sets the attribute formaPago.
     * @param value the new value
     */
    public void setFormaPago(java.lang.Integer value) {
      gen_modelInstance.setFormaPago(value);
      changed(1);
    }
    
    // attribute "perfilCliente"
    public final static String PERFIL_CLIENTE = "perfilCliente";

    /**
     * Returns the attribute perfilCliente.
     */
    public java.lang.String getPerfilCliente() {
      return gen_modelInstance.getPerfilCliente();
    }

    /**
     * Sets the attribute perfilCliente.
     * @param value the new value
     */
    public void setPerfilCliente(java.lang.String value) {
      gen_modelInstance.setPerfilCliente(value);
      changed(2);
    }
    
    // attribute "segmentoVta"
    public final static String SEGMENTO_VTA = "segmentoVta";

    /**
     * Returns the attribute segmentoVta.
     */
    public java.lang.Integer getSegmentoVta() {
      return gen_modelInstance.getSegmentoVta();
    }

    /**
     * Sets the attribute segmentoVta.
     * @param value the new value
     */
    public void setSegmentoVta(java.lang.Integer value) {
      gen_modelInstance.setSegmentoVta(value);
      changed(3);
    }
    
    // attribute "pagaSeguro"
    public final static String PAGA_SEGURO = "pagaSeguro";

    /**
     * Returns the attribute pagaSeguro.
     */
    public java.lang.String getPagaSeguro() {
      return gen_modelInstance.getPagaSeguro();
    }

    /**
     * Sets the attribute pagaSeguro.
     * @param value the new value
     */
    public void setPagaSeguro(java.lang.String value) {
      gen_modelInstance.setPagaSeguro(value);
      changed(4);
    }
    
    // attribute "tipoVtaFalSobMerc"
    public final static String TIPO_VTA_FAL_SOB_MERC = "tipoVtaFalSobMerc";

    /**
     * Returns the attribute tipoVtaFalSobMerc.
     */
    public java.lang.Integer getTipoVtaFalSobMerc() {
      return gen_modelInstance.getTipoVtaFalSobMerc();
    }

    /**
     * Sets the attribute tipoVtaFalSobMerc.
     * @param value the new value
     */
    public void setTipoVtaFalSobMerc(java.lang.Integer value) {
      gen_modelInstance.setTipoVtaFalSobMerc(value);
      changed(5);
    }
    
    // attribute "tipoClienteContable"
    public final static String TIPO_CLIENTE_CONTABLE = "tipoClienteContable";

    /**
     * Returns the attribute tipoClienteContable.
     */
    public java.lang.Integer getTipoClienteContable() {
      return gen_modelInstance.getTipoClienteContable();
    }

    /**
     * Sets the attribute tipoClienteContable.
     * @param value the new value
     */
    public void setTipoClienteContable(java.lang.Integer value) {
      gen_modelInstance.setTipoClienteContable(value);
      changed(6);
    }
    
    // attribute "tienePromocion"
    public final static String TIENE_PROMOCION = "tienePromocion";

    /**
     * Returns the attribute tienePromocion.
     */
    public java.lang.String getTienePromocion() {
      return gen_modelInstance.getTienePromocion();
    }

    /**
     * Sets the attribute tienePromocion.
     * @param value the new value
     */
    public void setTienePromocion(java.lang.String value) {
      gen_modelInstance.setTienePromocion(value);
      changed(7);
    }
    
    // attribute "listaPrecioMaximo"
    public final static String LISTA_PRECIO_MAXIMO = "listaPrecioMaximo";

    /**
     * Returns the attribute listaPrecioMaximo.
     */
    public java.lang.Integer getListaPrecioMaximo() {
      return gen_modelInstance.getListaPrecioMaximo();
    }

    /**
     * Sets the attribute listaPrecioMaximo.
     * @param value the new value
     */
    public void setListaPrecioMaximo(java.lang.Integer value) {
      gen_modelInstance.setListaPrecioMaximo(value);
      changed(8);
    }
    
    // attribute "imprimeRemito"
    public final static String IMPRIME_REMITO = "imprimeRemito";

    /**
     * Returns the attribute imprimeRemito.
     */
    public java.lang.String getImprimeRemito() {
      return gen_modelInstance.getImprimeRemito();
    }

    /**
     * Sets the attribute imprimeRemito.
     * @param value the new value
     */
    public void setImprimeRemito(java.lang.String value) {
      gen_modelInstance.setImprimeRemito(value);
      changed(9);
    }
    
    // attribute "listaPrecioBasico"
    public final static String LISTA_PRECIO_BASICO = "listaPrecioBasico";

    /**
     * Returns the attribute listaPrecioBasico.
     */
    public java.lang.Integer getListaPrecioBasico() {
      return gen_modelInstance.getListaPrecioBasico();
    }

    /**
     * Sets the attribute listaPrecioBasico.
     * @param value the new value
     */
    public void setListaPrecioBasico(java.lang.Integer value) {
      gen_modelInstance.setListaPrecioBasico(value);
      changed(10);
    }
    
    // attribute "tipoEmpresa"
    public final static String TIPO_EMPRESA = "tipoEmpresa";

    /**
     * Returns the attribute tipoEmpresa.
     */
    public java.lang.String getTipoEmpresa() {
      return gen_modelInstance.getTipoEmpresa();
    }

    /**
     * Sets the attribute tipoEmpresa.
     * @param value the new value
     */
    public void setTipoEmpresa(java.lang.String value) {
      gen_modelInstance.setTipoEmpresa(value);
      changed(11);
    }
    
    // attribute "tipoVtaFalSobEnv"
    public final static String TIPO_VTA_FAL_SOB_ENV = "tipoVtaFalSobEnv";

    /**
     * Returns the attribute tipoVtaFalSobEnv.
     */
    public java.lang.Integer getTipoVtaFalSobEnv() {
      return gen_modelInstance.getTipoVtaFalSobEnv();
    }

    /**
     * Sets the attribute tipoVtaFalSobEnv.
     * @param value the new value
     */
    public void setTipoVtaFalSobEnv(java.lang.Integer value) {
      gen_modelInstance.setTipoVtaFalSobEnv(value);
      changed(12);
    }
    
    // attribute "esExclusivo"
    public final static String ES_EXCLUSIVO = "esExclusivo";

    /**
     * Returns the attribute esExclusivo.
     */
    public java.lang.String getEsExclusivo() {
      return gen_modelInstance.getEsExclusivo();
    }

    /**
     * Sets the attribute esExclusivo.
     * @param value the new value
     */
    public void setEsExclusivo(java.lang.String value) {
      gen_modelInstance.setEsExclusivo(value);
      changed(13);
    }
    
    // attribute "sociedad"
    public final static String SOCIEDAD = "sociedad";

    /**
     * Returns the attribute sociedad.
     */
    public java.lang.String getSociedad() {
      return gen_modelInstance.getSociedad();
    }

    /**
     * Sets the attribute sociedad.
     * @param value the new value
     */
    public void setSociedad(java.lang.String value) {
      gen_modelInstance.setSociedad(value);
      changed(14);
    }
    
    // attribute "aceptaDesdUnifPedidos"
    public final static String ACEPTA_DESD_UNIF_PEDIDOS = "aceptaDesdUnifPedidos";

    /**
     * Returns the attribute aceptaDesdUnifPedidos.
     */
    public java.lang.String getAceptaDesdUnifPedidos() {
      return gen_modelInstance.getAceptaDesdUnifPedidos();
    }

    /**
     * Sets the attribute aceptaDesdUnifPedidos.
     * @param value the new value
     */
    public void setAceptaDesdUnifPedidos(java.lang.String value) {
      gen_modelInstance.setAceptaDesdUnifPedidos(value);
      changed(15);
    }
    
    // attribute "formaEntregaCtaCte"
    public final static String FORMA_ENTREGA_CTA_CTE = "formaEntregaCtaCte";

    /**
     * Returns the attribute formaEntregaCtaCte.
     */
    public java.lang.String getFormaEntregaCtaCte() {
      return gen_modelInstance.getFormaEntregaCtaCte();
    }

    /**
     * Sets the attribute formaEntregaCtaCte.
     * @param value the new value
     */
    public void setFormaEntregaCtaCte(java.lang.String value) {
      gen_modelInstance.setFormaEntregaCtaCte(value);
      changed(16);
    }
    
    // attribute "canalVenta"
    public final static String CANAL_VENTA = "canalVenta";

    /**
     * Returns the attribute canalVenta.
     */
    public java.lang.Integer getCanalVenta() {
      return gen_modelInstance.getCanalVenta();
    }

    /**
     * Sets the attribute canalVenta.
     * @param value the new value
     */
    public void setCanalVenta(java.lang.Integer value) {
      gen_modelInstance.setCanalVenta(value);
      changed(17);
    }
    
    // attribute "esquema"
    public final static String ESQUEMA = "esquema";

    /**
     * Returns the attribute esquema.
     */
    public java.lang.String getEsquema() {
      return gen_modelInstance.getEsquema();
    }

    /**
     * Sets the attribute esquema.
     * @param value the new value
     */
    public void setEsquema(java.lang.String value) {
      gen_modelInstance.setEsquema(value);
      changed(18);
    }
    
    // attribute "formaAtencion"
    public final static String FORMA_ATENCION = "formaAtencion";

    /**
     * Returns the attribute formaAtencion.
     */
    public java.lang.Integer getFormaAtencion() {
      return gen_modelInstance.getFormaAtencion();
    }

    /**
     * Sets the attribute formaAtencion.
     * @param value the new value
     */
    public void setFormaAtencion(java.lang.Integer value) {
      gen_modelInstance.setFormaAtencion(value);
      changed(19);
    }
    
    // attribute "agrupacionComercial"
    public final static String AGRUPACION_COMERCIAL = "agrupacionComercial";

    /**
     * Returns the attribute agrupacionComercial.
     */
    public java.lang.Integer getAgrupacionComercial() {
      return gen_modelInstance.getAgrupacionComercial();
    }

    /**
     * Sets the attribute agrupacionComercial.
     * @param value the new value
     */
    public void setAgrupacionComercial(java.lang.Integer value) {
      gen_modelInstance.setAgrupacionComercial(value);
      changed(20);
    }
    
    // attribute "polVentaCal1"
    public final static String POL_VENTA_CAL1 = "polVentaCal1";

    /**
     * Returns the attribute polVentaCal1.
     */
    public java.lang.Integer getPolVentaCal1() {
      return gen_modelInstance.getPolVentaCal1();
    }

    /**
     * Sets the attribute polVentaCal1.
     * @param value the new value
     */
    public void setPolVentaCal1(java.lang.Integer value) {
      gen_modelInstance.setPolVentaCal1(value);
      changed(21);
    }
    
    // attribute "ramo"
    public final static String RAMO = "ramo";

    /**
     * Returns the attribute ramo.
     */
    public java.lang.Integer getRamo() {
      return gen_modelInstance.getRamo();
    }

    /**
     * Sets the attribute ramo.
     * @param value the new value
     */
    public void setRamo(java.lang.Integer value) {
      gen_modelInstance.setRamo(value);
      changed(22);
    }
    
    // attribute "banco"
    public final static String BANCO = "banco";

    /**
     * Returns the attribute banco.
     */
    public java.lang.Integer getBanco() {
      return gen_modelInstance.getBanco();
    }

    /**
     * Sets the attribute banco.
     * @param value the new value
     */
    public void setBanco(java.lang.Integer value) {
      gen_modelInstance.setBanco(value);
      changed(23);
    }
    
    // attribute "ctaCteExterna"
    public final static String CTA_CTE_EXTERNA = "ctaCteExterna";

    /**
     * Returns the attribute ctaCteExterna.
     */
    public java.lang.String getCtaCteExterna() {
      return gen_modelInstance.getCtaCteExterna();
    }

    /**
     * Sets the attribute ctaCteExterna.
     * @param value the new value
     */
    public void setCtaCteExterna(java.lang.String value) {
      gen_modelInstance.setCtaCteExterna(value);
      changed(24);
    }
    
    // attribute "cobrador"
    public final static String COBRADOR = "cobrador";

    /**
     * Returns the attribute cobrador.
     */
    public java.lang.String getCobrador() {
      return gen_modelInstance.getCobrador();
    }

    /**
     * Sets the attribute cobrador.
     * @param value the new value
     */
    public void setCobrador(java.lang.String value) {
      gen_modelInstance.setCobrador(value);
      changed(25);
    }
    
    // attribute "personeriaJuridica"
    public final static String PERSONERIA_JURIDICA = "personeriaJuridica";

    /**
     * Returns the attribute personeriaJuridica.
     */
    public java.lang.String getPersoneriaJuridica() {
      return gen_modelInstance.getPersoneriaJuridica();
    }

    /**
     * Sets the attribute personeriaJuridica.
     * @param value the new value
     */
    public void setPersoneriaJuridica(java.lang.String value) {
      gen_modelInstance.setPersoneriaJuridica(value);
      changed(26);
    }
    
    // attribute "tipoClienteCondVta"
    public final static String TIPO_CLIENTE_COND_VTA = "tipoClienteCondVta";

    /**
     * Returns the attribute tipoClienteCondVta.
     */
    public java.lang.Integer getTipoClienteCondVta() {
      return gen_modelInstance.getTipoClienteCondVta();
    }

    /**
     * Sets the attribute tipoClienteCondVta.
     * @param value the new value
     */
    public void setTipoClienteCondVta(java.lang.Integer value) {
      gen_modelInstance.setTipoClienteCondVta(value);
      changed(27);
    }
    
    // attribute "tipoMaqVend"
    public final static String TIPO_MAQ_VEND = "tipoMaqVend";

    /**
     * Returns the attribute tipoMaqVend.
     */
    public java.lang.String getTipoMaqVend() {
      return gen_modelInstance.getTipoMaqVend();
    }

    /**
     * Sets the attribute tipoMaqVend.
     * @param value the new value
     */
    public void setTipoMaqVend(java.lang.String value) {
      gen_modelInstance.setTipoMaqVend(value);
      changed(28);
    }
    
    // attribute "polVentaCal3"
    public final static String POL_VENTA_CAL3 = "polVentaCal3";

    /**
     * Returns the attribute polVentaCal3.
     */
    public java.lang.Integer getPolVentaCal3() {
      return gen_modelInstance.getPolVentaCal3();
    }

    /**
     * Sets the attribute polVentaCal3.
     * @param value the new value
     */
    public void setPolVentaCal3(java.lang.Integer value) {
      gen_modelInstance.setPolVentaCal3(value);
      changed(29);
    }
    
    // attribute "identificacionJuridica"
    public final static String IDENTIFICACION_JURIDICA = "identificacionJuridica";

    /**
     * Returns the attribute identificacionJuridica.
     */
    public java.lang.String getIdentificacionJuridica() {
      return gen_modelInstance.getIdentificacionJuridica();
    }

    /**
     * Sets the attribute identificacionJuridica.
     * @param value the new value
     */
    public void setIdentificacionJuridica(java.lang.String value) {
      gen_modelInstance.setIdentificacionJuridica(value);
      changed(30);
    }
    
    // attribute "moneda"
    public final static String MONEDA = "moneda";

    /**
     * Returns the attribute moneda.
     */
    public java.lang.String getMoneda() {
      return gen_modelInstance.getMoneda();
    }

    /**
     * Sets the attribute moneda.
     * @param value the new value
     */
    public void setMoneda(java.lang.String value) {
      gen_modelInstance.setMoneda(value);
      changed(31);
    }
    
    // attribute "tipoCliCom"
    public final static String TIPO_CLI_COM = "tipoCliCom";

    /**
     * Returns the attribute tipoCliCom.
     */
    public java.lang.Integer getTipoCliCom() {
      return gen_modelInstance.getTipoCliCom();
    }

    /**
     * Sets the attribute tipoCliCom.
     * @param value the new value
     */
    public void setTipoCliCom(java.lang.Integer value) {
      gen_modelInstance.setTipoCliCom(value);
      changed(32);
    }
    
    // attribute "nroImpuestoInterno"
    public final static String NRO_IMPUESTO_INTERNO = "nroImpuestoInterno";

    /**
     * Returns the attribute nroImpuestoInterno.
     */
    public java.lang.String getNroImpuestoInterno() {
      return gen_modelInstance.getNroImpuestoInterno();
    }

    /**
     * Sets the attribute nroImpuestoInterno.
     * @param value the new value
     */
    public void setNroImpuestoInterno(java.lang.String value) {
      gen_modelInstance.setNroImpuestoInterno(value);
      changed(33);
    }
    
    // attribute "asigStock"
    public final static String ASIG_STOCK = "asigStock";

    /**
     * Returns the attribute asigStock.
     */
    public java.lang.Integer getAsigStock() {
      return gen_modelInstance.getAsigStock();
    }

    /**
     * Sets the attribute asigStock.
     * @param value the new value
     */
    public void setAsigStock(java.lang.Integer value) {
      gen_modelInstance.setAsigStock(value);
      changed(34);
    }
    
    // attribute "comprador"
    public final static String COMPRADOR = "comprador";

    /**
     * Returns the attribute comprador.
     */
    public java.lang.String getComprador() {
      return gen_modelInstance.getComprador();
    }

    /**
     * Sets the attribute comprador.
     * @param value the new value
     */
    public void setComprador(java.lang.String value) {
      gen_modelInstance.setComprador(value);
      changed(35);
    }
    
    // attribute "fueCensado"
    public final static String FUE_CENSADO = "fueCensado";

    /**
     * Returns the attribute fueCensado.
     */
    public java.lang.String getFueCensado() {
      return gen_modelInstance.getFueCensado();
    }

    /**
     * Sets the attribute fueCensado.
     * @param value the new value
     */
    public void setFueCensado(java.lang.String value) {
      gen_modelInstance.setFueCensado(value);
      changed(36);
    }
    
    // attribute "polVentaCal2"
    public final static String POL_VENTA_CAL2 = "polVentaCal2";

    /**
     * Returns the attribute polVentaCal2.
     */
    public java.lang.Integer getPolVentaCal2() {
      return gen_modelInstance.getPolVentaCal2();
    }

    /**
     * Sets the attribute polVentaCal2.
     * @param value the new value
     */
    public void setPolVentaCal2(java.lang.Integer value) {
      gen_modelInstance.setPolVentaCal2(value);
      changed(37);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // tipoCobranza
          return gen_modelInstance.getTipoCobranza();
        case 1: // formaPago
          return gen_modelInstance.getFormaPago();
        case 2: // perfilCliente
          return gen_modelInstance.getPerfilCliente();
        case 3: // segmentoVta
          return gen_modelInstance.getSegmentoVta();
        case 4: // pagaSeguro
          return gen_modelInstance.getPagaSeguro();
        case 5: // tipoVtaFalSobMerc
          return gen_modelInstance.getTipoVtaFalSobMerc();
        case 6: // tipoClienteContable
          return gen_modelInstance.getTipoClienteContable();
        case 7: // tienePromocion
          return gen_modelInstance.getTienePromocion();
        case 8: // listaPrecioMaximo
          return gen_modelInstance.getListaPrecioMaximo();
        case 9: // imprimeRemito
          return gen_modelInstance.getImprimeRemito();
        case 10: // listaPrecioBasico
          return gen_modelInstance.getListaPrecioBasico();
        case 11: // tipoEmpresa
          return gen_modelInstance.getTipoEmpresa();
        case 12: // tipoVtaFalSobEnv
          return gen_modelInstance.getTipoVtaFalSobEnv();
        case 13: // esExclusivo
          return gen_modelInstance.getEsExclusivo();
        case 14: // sociedad
          return gen_modelInstance.getSociedad();
        case 15: // aceptaDesdUnifPedidos
          return gen_modelInstance.getAceptaDesdUnifPedidos();
        case 16: // formaEntregaCtaCte
          return gen_modelInstance.getFormaEntregaCtaCte();
        case 17: // canalVenta
          return gen_modelInstance.getCanalVenta();
        case 18: // esquema
          return gen_modelInstance.getEsquema();
        case 19: // formaAtencion
          return gen_modelInstance.getFormaAtencion();
        case 20: // agrupacionComercial
          return gen_modelInstance.getAgrupacionComercial();
        case 21: // polVentaCal1
          return gen_modelInstance.getPolVentaCal1();
        case 22: // ramo
          return gen_modelInstance.getRamo();
        case 23: // banco
          return gen_modelInstance.getBanco();
        case 24: // ctaCteExterna
          return gen_modelInstance.getCtaCteExterna();
        case 25: // cobrador
          return gen_modelInstance.getCobrador();
        case 26: // personeriaJuridica
          return gen_modelInstance.getPersoneriaJuridica();
        case 27: // tipoClienteCondVta
          return gen_modelInstance.getTipoClienteCondVta();
        case 28: // tipoMaqVend
          return gen_modelInstance.getTipoMaqVend();
        case 29: // polVentaCal3
          return gen_modelInstance.getPolVentaCal3();
        case 30: // identificacionJuridica
          return gen_modelInstance.getIdentificacionJuridica();
        case 31: // moneda
          return gen_modelInstance.getMoneda();
        case 32: // tipoCliCom
          return gen_modelInstance.getTipoCliCom();
        case 33: // nroImpuestoInterno
          return gen_modelInstance.getNroImpuestoInterno();
        case 34: // asigStock
          return gen_modelInstance.getAsigStock();
        case 35: // comprador
          return gen_modelInstance.getComprador();
        case 36: // fueCensado
          return gen_modelInstance.getFueCensado();
        case 37: // polVentaCal2
          return gen_modelInstance.getPolVentaCal2();
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // tipoCobranza
          gen_modelInstance.setTipoCobranza((java.lang.Integer)value);
          changed(info);
          break;
        case 1: // formaPago
          gen_modelInstance.setFormaPago((java.lang.Integer)value);
          changed(info);
          break;
        case 2: // perfilCliente
          gen_modelInstance.setPerfilCliente((String)value);
          changed(info);
          break;
        case 3: // segmentoVta
          gen_modelInstance.setSegmentoVta((java.lang.Integer)value);
          changed(info);
          break;
        case 4: // pagaSeguro
          gen_modelInstance.setPagaSeguro((String)value);
          changed(info);
          break;
        case 5: // tipoVtaFalSobMerc
          gen_modelInstance.setTipoVtaFalSobMerc((java.lang.Integer)value);
          changed(info);
          break;
        case 6: // tipoClienteContable
          gen_modelInstance.setTipoClienteContable((java.lang.Integer)value);
          changed(info);
          break;
        case 7: // tienePromocion
          gen_modelInstance.setTienePromocion((String)value);
          changed(info);
          break;
        case 8: // listaPrecioMaximo
          gen_modelInstance.setListaPrecioMaximo((java.lang.Integer)value);
          changed(info);
          break;
        case 9: // imprimeRemito
          gen_modelInstance.setImprimeRemito((String)value);
          changed(info);
          break;
        case 10: // listaPrecioBasico
          gen_modelInstance.setListaPrecioBasico((java.lang.Integer)value);
          changed(info);
          break;
        case 11: // tipoEmpresa
          gen_modelInstance.setTipoEmpresa((String)value);
          changed(info);
          break;
        case 12: // tipoVtaFalSobEnv
          gen_modelInstance.setTipoVtaFalSobEnv((java.lang.Integer)value);
          changed(info);
          break;
        case 13: // esExclusivo
          gen_modelInstance.setEsExclusivo((String)value);
          changed(info);
          break;
        case 14: // sociedad
          gen_modelInstance.setSociedad((String)value);
          changed(info);
          break;
        case 15: // aceptaDesdUnifPedidos
          gen_modelInstance.setAceptaDesdUnifPedidos((String)value);
          changed(info);
          break;
        case 16: // formaEntregaCtaCte
          gen_modelInstance.setFormaEntregaCtaCte((String)value);
          changed(info);
          break;
        case 17: // canalVenta
          gen_modelInstance.setCanalVenta((java.lang.Integer)value);
          changed(info);
          break;
        case 18: // esquema
          gen_modelInstance.setEsquema((String)value);
          changed(info);
          break;
        case 19: // formaAtencion
          gen_modelInstance.setFormaAtencion((java.lang.Integer)value);
          changed(info);
          break;
        case 20: // agrupacionComercial
          gen_modelInstance.setAgrupacionComercial((java.lang.Integer)value);
          changed(info);
          break;
        case 21: // polVentaCal1
          gen_modelInstance.setPolVentaCal1((java.lang.Integer)value);
          changed(info);
          break;
        case 22: // ramo
          gen_modelInstance.setRamo((java.lang.Integer)value);
          changed(info);
          break;
        case 23: // banco
          gen_modelInstance.setBanco((java.lang.Integer)value);
          changed(info);
          break;
        case 24: // ctaCteExterna
          gen_modelInstance.setCtaCteExterna((String)value);
          changed(info);
          break;
        case 25: // cobrador
          gen_modelInstance.setCobrador((String)value);
          changed(info);
          break;
        case 26: // personeriaJuridica
          gen_modelInstance.setPersoneriaJuridica((String)value);
          changed(info);
          break;
        case 27: // tipoClienteCondVta
          gen_modelInstance.setTipoClienteCondVta((java.lang.Integer)value);
          changed(info);
          break;
        case 28: // tipoMaqVend
          gen_modelInstance.setTipoMaqVend((String)value);
          changed(info);
          break;
        case 29: // polVentaCal3
          gen_modelInstance.setPolVentaCal3((java.lang.Integer)value);
          changed(info);
          break;
        case 30: // identificacionJuridica
          gen_modelInstance.setIdentificacionJuridica((String)value);
          changed(info);
          break;
        case 31: // moneda
          gen_modelInstance.setMoneda((String)value);
          changed(info);
          break;
        case 32: // tipoCliCom
          gen_modelInstance.setTipoCliCom((java.lang.Integer)value);
          changed(info);
          break;
        case 33: // nroImpuestoInterno
          gen_modelInstance.setNroImpuestoInterno((String)value);
          changed(info);
          break;
        case 34: // asigStock
          gen_modelInstance.setAsigStock((java.lang.Integer)value);
          changed(info);
          break;
        case 35: // comprador
          gen_modelInstance.setComprador((String)value);
          changed(info);
          break;
        case 36: // fueCensado
          gen_modelInstance.setFueCensado((String)value);
          changed(info);
          break;
        case 37: // polVentaCal2
          gen_modelInstance.setPolVentaCal2((java.lang.Integer)value);
          changed(info);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected String wdGetString(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 2: // perfilCliente
          return gen_modelInstance.getPerfilCliente();
        case 4: // pagaSeguro
          return gen_modelInstance.getPagaSeguro();
        case 7: // tienePromocion
          return gen_modelInstance.getTienePromocion();
        case 9: // imprimeRemito
          return gen_modelInstance.getImprimeRemito();
        case 11: // tipoEmpresa
          return gen_modelInstance.getTipoEmpresa();
        case 13: // esExclusivo
          return gen_modelInstance.getEsExclusivo();
        case 14: // sociedad
          return gen_modelInstance.getSociedad();
        case 15: // aceptaDesdUnifPedidos
          return gen_modelInstance.getAceptaDesdUnifPedidos();
        case 16: // formaEntregaCtaCte
          return gen_modelInstance.getFormaEntregaCtaCte();
        case 18: // esquema
          return gen_modelInstance.getEsquema();
        case 24: // ctaCteExterna
          return gen_modelInstance.getCtaCteExterna();
        case 25: // cobrador
          return gen_modelInstance.getCobrador();
        case 26: // personeriaJuridica
          return gen_modelInstance.getPersoneriaJuridica();
        case 28: // tipoMaqVend
          return gen_modelInstance.getTipoMaqVend();
        case 30: // identificacionJuridica
          return gen_modelInstance.getIdentificacionJuridica();
        case 31: // moneda
          return gen_modelInstance.getMoneda();
        case 33: // nroImpuestoInterno
          return gen_modelInstance.getNroImpuestoInterno();
        case 35: // comprador
          return gen_modelInstance.getComprador();
        case 36: // fueCensado
          return gen_modelInstance.getFueCensado();
        default:
          return super.wdGetString(info);
      }
    }

    protected void wdSetString(IGCIAttributeInfo info, String value) {
      switch (info.getIndex()) {
        case 2: // perfilCliente
          gen_modelInstance.setPerfilCliente((java.lang.String)value);
          changed(info);
          break;
        case 4: // pagaSeguro
          gen_modelInstance.setPagaSeguro((java.lang.String)value);
          changed(info);
          break;
        case 7: // tienePromocion
          gen_modelInstance.setTienePromocion((java.lang.String)value);
          changed(info);
          break;
        case 9: // imprimeRemito
          gen_modelInstance.setImprimeRemito((java.lang.String)value);
          changed(info);
          break;
        case 11: // tipoEmpresa
          gen_modelInstance.setTipoEmpresa((java.lang.String)value);
          changed(info);
          break;
        case 13: // esExclusivo
          gen_modelInstance.setEsExclusivo((java.lang.String)value);
          changed(info);
          break;
        case 14: // sociedad
          gen_modelInstance.setSociedad((java.lang.String)value);
          changed(info);
          break;
        case 15: // aceptaDesdUnifPedidos
          gen_modelInstance.setAceptaDesdUnifPedidos((java.lang.String)value);
          changed(info);
          break;
        case 16: // formaEntregaCtaCte
          gen_modelInstance.setFormaEntregaCtaCte((java.lang.String)value);
          changed(info);
          break;
        case 18: // esquema
          gen_modelInstance.setEsquema((java.lang.String)value);
          changed(info);
          break;
        case 24: // ctaCteExterna
          gen_modelInstance.setCtaCteExterna((java.lang.String)value);
          changed(info);
          break;
        case 25: // cobrador
          gen_modelInstance.setCobrador((java.lang.String)value);
          changed(info);
          break;
        case 26: // personeriaJuridica
          gen_modelInstance.setPersoneriaJuridica((java.lang.String)value);
          changed(info);
          break;
        case 28: // tipoMaqVend
          gen_modelInstance.setTipoMaqVend((java.lang.String)value);
          changed(info);
          break;
        case 30: // identificacionJuridica
          gen_modelInstance.setIdentificacionJuridica((java.lang.String)value);
          changed(info);
          break;
        case 31: // moneda
          gen_modelInstance.setMoneda((java.lang.String)value);
          changed(info);
          break;
        case 33: // nroImpuestoInterno
          gen_modelInstance.setNroImpuestoInterno((java.lang.String)value);
          changed(info);
          break;
        case 35: // comprador
          gen_modelInstance.setComprador((java.lang.String)value);
          changed(info);
          break;
        case 36: // fueCensado
          gen_modelInstance.setFueCensado((java.lang.String)value);
          changed(info);
          break;
        default:
          super.wdSetString(info, value);
          break;
      }
    }

  }

  /**
   * Returns the context root node.
   * @return the context root node.
   */
  IContextNode wdGetContext();

  /** Fires outbound plug. */
  void wdFirePlugSalida_consulta( );

  /** Declared event handler. */
  void onPlugentradaconsulta(IWDCustomEvent wdEvent );

  /** Declared event handler. */
  void onActionbuscar(IWDCustomEvent wdEvent );

  /** Declared event handler. */
  void onActioncrear(IWDCustomEvent wdEvent );

  /** Gets controller belonging to the same component. */
  ar.com.quilmes.consulta.wdp.IPublicConsulta_WindowInterfaceView wdGetConsulta_WindowInterfaceViewController();

  /** Gets controller belonging to the same component. */
  ar.com.quilmes.consulta.wdp.IPublicConsulta_Comp wdGetConsulta_CompController();

  /** Gets action 'buscar'. */
  IWDAction wdGetBuscarAction();

  /** Gets action 'crear'. */
  IWDAction wdGetCrearAction();

  /** Enumeration of all available action event handlers. */
  public final class WDActionEventHandler extends com.sap.tc.webdynpro.progmodel.gci.GCIActionEventHandlerEnum
  {
    public static final WDActionEventHandler BUSCAR = new WDActionEventHandler("onActionbuscar", true, NO_PARAMETERS);
    public static final WDActionEventHandler CREAR = new WDActionEventHandler("onActioncrear", true, NO_PARAMETERS);

    private WDActionEventHandler(String value, boolean isValidating, Object[] declaredParameters) {
      super(value, isValidating, declaredParameters);
    }
  }

  /**
   * Creates a new action for this controller.
   * @param eventHandler is the action's event handler with an appropriate signature
   * @param text is the text displayed in the UI element triggering this action
   */
  IWDAction wdCreateAction(WDActionEventHandler eventHandler, String text);

  /**
   * Creates a new action with the given name for this controller.
   * @param eventHandler is the action's event handler with an appropriate signature
   * @param name is the action's name
   * @param text is the text displayed in the UI element triggering this action
   */
  IWDAction wdCreateNamedAction(WDActionEventHandler eventHandler, String name, String text);

}
