// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
// ---------------------------------------------------------------------------
package ar.com.quilmes.consulta.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

public interface IPublicConsulta_Comp {

  /**
   * Provides access to the generic API of this component.
   */
  IWDComponent wdGetAPI();


  /**
   * Interface for the node 'Context'.
   *
   * singleton = true, cardinality = _1_1, selection = _1_1
   */
  public static class IContextNode extends Node
  {
    private InternalConsulta_Comp gen_delegate;

    IContextNode(InternalConsulta_Comp delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    protected com.sap.tc.webdynpro.progmodel.context.Node createNode(IGCINodeInfo nodeInfo, com.sap.tc.webdynpro.progmodel.context.Node parentNode, com.sap.tc.webdynpro.progmodel.context.NodeElement parentElement) {
      if (nodeInfo == gen_delegate.infoContext)
        return new IPrivateConsulta_Comp.IContextNode(gen_delegate, nodeInfo, parentNode);
      if (nodeInfo == gen_delegate.infoClientes)
        return new IPrivateConsulta_Comp.IClientesNode(gen_delegate, nodeInfo, parentNode);
      if (nodeInfo == gen_delegate.infoTipoDocumento)
        return new IPrivateConsulta_Comp.ITipoDocumentoNode(gen_delegate, nodeInfo, parentNode);
      return super.createNode(nodeInfo, parentNode, parentElement);
    }

    protected com.sap.tc.webdynpro.progmodel.context.NodeElement doCreateElement(IGCINodeInfo nodeInfo, Object reference) {
      if (nodeInfo == gen_delegate.infoContext) {
        return new IPrivateConsulta_Comp.IContextElement(gen_delegate, nodeInfo);
      }
      if (nodeInfo == gen_delegate.infoClientes) {
        return new IPrivateConsulta_Comp.IClientesElement(gen_delegate, nodeInfo, reference);
      }
      if (nodeInfo == gen_delegate.infoTipoDocumento) {
        return new IPrivateConsulta_Comp.ITipoDocumentoElement(gen_delegate, nodeInfo, reference);
      }
      return super.doCreateElement(nodeInfo, reference);
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Provides access to the generic context API as described by IWDContext.
     */
    public IWDContext wdGetAPI() {
      return getContext();
    }

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IContextElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @return an element for this node
     */
    public IPrivateConsulta_Comp.IContextElement createContextElement() {
      return (IPrivateConsulta_Comp.IContextElement)createElement();
    }

    /**
     * Binds a single IContextElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateConsulta_Comp.IContextElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateConsulta_Comp.IContextElement currentContextElement() {
      return (IPrivateConsulta_Comp.IContextElement) getCurrentElement();
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

    private IPrivateConsulta_Comp.IClientesNode gen_nodeClientes;
    
    /**
     * Returns the singleton child node Clientes.
     * @return the child node
     */
    public IPrivateConsulta_Comp.IClientesNode nodeClientes() {
      if (gen_nodeClientes == null)
        gen_nodeClientes = (IPrivateConsulta_Comp.IClientesNode) getChildNode("Clientes");
      return gen_nodeClientes;
    }

    /**
     * Returns the current (lead selection) element of the singleton child node
     * Clientes.
     * @return the child node element or <code>null</code> if no such element 
     *         exists
     */
    public IPrivateConsulta_Comp.IClientesElement currentClientesElement() {
      return (IPrivateConsulta_Comp.IClientesElement) nodeClientes().getCurrentElement();
    }

    public IPrivateConsulta_Comp.IClientesElement createClientesElement(ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente model) {
      return (IPrivateConsulta_Comp.IClientesElement) doCreateElement(gen_delegate.infoClientes, model);
    }

    private IPrivateConsulta_Comp.ITipoDocumentoNode gen_nodeTipoDocumento;
    
    /**
     * Returns the singleton child node TipoDocumento.
     * @return the child node
     */
    public IPrivateConsulta_Comp.ITipoDocumentoNode nodeTipoDocumento() {
      if (gen_nodeTipoDocumento == null)
        gen_nodeTipoDocumento = (IPrivateConsulta_Comp.ITipoDocumentoNode) getChildNode("TipoDocumento");
      return gen_nodeTipoDocumento;
    }

    /**
     * Returns the current (lead selection) element of the singleton child node
     * TipoDocumento.
     * @return the child node element or <code>null</code> if no such element 
     *         exists
     */
    public IPrivateConsulta_Comp.ITipoDocumentoElement currentTipoDocumentoElement() {
      return (IPrivateConsulta_Comp.ITipoDocumentoElement) nodeTipoDocumento().getCurrentElement();
    }

    public IPrivateConsulta_Comp.ITipoDocumentoElement createTipoDocumentoElement(ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento model) {
      return (IPrivateConsulta_Comp.ITipoDocumentoElement) doCreateElement(gen_delegate.infoTipoDocumento, model);
    }

  }

  /**
   * Interface for the elements of the node Context.
   */
  public static class IContextElement extends com.sap.tc.webdynpro.progmodel.context.NodeElement
  {
    private InternalConsulta_Comp gen_delegate;

    public IContextElement(InternalConsulta_Comp delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info) {
      super(info);
      gen_delegate = delegate;
    }

    // attribute "nro_cliente"
    public final static String NRO__CLIENTE = "nro_cliente";

    private int _nro_cliente;

    /**
     * Returns the attribute nro_cliente.
     */
    public int getNro_cliente() {
      return _nro_cliente;
    }

    /**
     * Sets the attribute nro_cliente.
     * @param value the new value
     */
    public void setNro_cliente(int value) {
      this._nro_cliente = value;
      changed(0);
    }
    
    // attribute "razon_social"
    public final static String RAZON__SOCIAL = "razon_social";

    private java.lang.String _razon_social;

    /**
     * Returns the attribute razon_social.
     */
    public java.lang.String getRazon_social() {
      return _razon_social;
    }

    /**
     * Sets the attribute razon_social.
     * @param value the new value
     */
    public void setRazon_social(java.lang.String value) {
      this._razon_social = value;
      changed(1);
    }
    
    // attribute "nro_documento"
    public final static String NRO__DOCUMENTO = "nro_documento";

    private java.lang.String _nro_documento;

    /**
     * Returns the attribute nro_documento.
     */
    public java.lang.String getNro_documento() {
      return _nro_documento;
    }

    /**
     * Sets the attribute nro_documento.
     * @param value the new value
     */
    public void setNro_documento(java.lang.String value) {
      this._nro_documento = value;
      changed(2);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          return new Integer(_nro_cliente);
        case 1: // razon_social
          return _razon_social;
        case 2: // nro_documento
          return _nro_documento;
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          this._nro_cliente = ((Number)value).intValue();
          changed(info);
          break;
        case 1: // razon_social
          this._razon_social = (String)value;
          changed(info);
          break;
        case 2: // nro_documento
          this._nro_documento = (String)value;
          changed(info);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected int wdGetInt(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          return _nro_cliente;
        default:
          return super.wdGetInt(info);
      }
    }

    protected void wdSetInt(IGCIAttributeInfo info, int value) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          this._nro_cliente = (int)value;
          changed(info);
          break;
        default:
          super.wdSetInt(info, value);
          break;
      }
    }

    protected String wdGetString(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 1: // razon_social
          return _razon_social;
        case 2: // nro_documento
          return _nro_documento;
        default:
          return super.wdGetString(info);
      }
    }

    protected void wdSetString(IGCIAttributeInfo info, String value) {
      switch (info.getIndex()) {
        case 1: // razon_social
          this._razon_social = (java.lang.String)value;
          changed(info);
          break;
        case 2: // nro_documento
          this._nro_documento = (java.lang.String)value;
          changed(info);
          break;
        default:
          super.wdSetString(info, value);
          break;
      }
    }

  }


  /**
   * Interface for the node 'Clientes'.
   *
   * singleton = true, cardinality = _0_n, selection = _0_1
   */
  public static class IClientesNode extends Node
  {
    private InternalConsulta_Comp gen_delegate;

    IClientesNode(InternalConsulta_Comp delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IClientesElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @param model an instance of ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente needed for this model element
     * @return an element for this node
     */
    public IPrivateConsulta_Comp.IClientesElement createClientesElement(ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente model) {
      return (IPrivateConsulta_Comp.IClientesElement)createElement(model);
    }

    /**
     * Binds a single IClientesElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateConsulta_Comp.IClientesElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /**
     * Creates a new IClientesElement with the given model object 
     * and binds it to this node.
     * @param model an object of the model class
     */
    public void bind(ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente model) {
      bind(model == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(model));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateConsulta_Comp.IClientesElement currentClientesElement() {
      return (IPrivateConsulta_Comp.IClientesElement) getCurrentElement();
    }

    /** 
     * Returns the element at the given index.
     * @param index the index of the element you want to get
     * @return the element or <code>null</code> if no element
     *         exists at that index
     */
    public IPrivateConsulta_Comp.IClientesElement getClientesElementAt(int index) {
      return (IPrivateConsulta_Comp.IClientesElement) getElementAt(index);
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node Clientes.
   */
  public static class IClientesElement extends com.sap.tc.webdynpro.progmodel.context.ModelNodeElement
  {
    private InternalConsulta_Comp gen_delegate;

    private final ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente gen_modelInstance;

    public IClientesElement(InternalConsulta_Comp delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info, Object modelInstance) {
      super(info, modelInstance);
      this.gen_modelInstance = (ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente) modelInstance;
      gen_delegate = delegate;
    }

    /**
     * Returns the referenced ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente.
     * @return the referenced ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente
     */
    public ar.com.quilmes.bue.mdm_clientes.model.externas.Cliente modelObject() {
      return gen_modelInstance;
    }

    // attribute "localidad_Id"
    public final static String LOCALIDAD__ID = "localidad_Id";

    /**
     * Returns the attribute localidad_Id.
     */
    public java.lang.String getLocalidad_Id() {
      return gen_modelInstance.getLocalidad_Id();
    }

    /**
     * Sets the attribute localidad_Id.
     * @param value the new value
     */
    public void setLocalidad_Id(java.lang.String value) {
      gen_modelInstance.setLocalidad_Id(value);
      changed(0);
    }
    
    // attribute "razonSocial"
    public final static String RAZON_SOCIAL = "razonSocial";

    /**
     * Returns the attribute razonSocial.
     */
    public java.lang.String getRazonSocial() {
      return gen_modelInstance.getRazonSocial();
    }

    /**
     * Sets the attribute razonSocial.
     * @param value the new value
     */
    public void setRazonSocial(java.lang.String value) {
      gen_modelInstance.setRazonSocial(value);
      changed(1);
    }
    
    // attribute "documento"
    public final static String DOCUMENTO = "documento";

    /**
     * Returns the attribute documento.
     */
    public java.lang.String getDocumento() {
      return gen_modelInstance.getDocumento();
    }

    /**
     * Sets the attribute documento.
     * @param value the new value
     */
    public void setDocumento(java.lang.String value) {
      gen_modelInstance.setDocumento(value);
      changed(2);
    }
    
    // attribute "territorio_Id"
    public final static String TERRITORIO__ID = "territorio_Id";

    /**
     * Returns the attribute territorio_Id.
     */
    public int getTerritorio_Id() {
      return gen_modelInstance.getTerritorio_Id();
    }

    /**
     * Sets the attribute territorio_Id.
     * @param value the new value
     */
    public void setTerritorio_Id(int value) {
      gen_modelInstance.setTerritorio_Id(value);
      changed(3);
    }
    
    // attribute "id"
    public final static String ID = "id";

    /**
     * Returns the attribute id.
     */
    public int getId() {
      return gen_modelInstance.getId();
    }

    /**
     * Sets the attribute id.
     * @param value the new value
     */
    public void setId(int value) {
      gen_modelInstance.setId(value);
      changed(4);
    }
    
    // attribute "domicilio"
    public final static String DOMICILIO = "domicilio";

    /**
     * Returns the attribute domicilio.
     */
    public java.lang.String getDomicilio() {
      return gen_modelInstance.getDomicilio();
    }

    /**
     * Sets the attribute domicilio.
     * @param value the new value
     */
    public void setDomicilio(java.lang.String value) {
      gen_modelInstance.setDomicilio(value);
      changed(5);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // localidad_Id
          return gen_modelInstance.getLocalidad_Id();
        case 1: // razonSocial
          return gen_modelInstance.getRazonSocial();
        case 2: // documento
          return gen_modelInstance.getDocumento();
        case 3: // territorio_Id
          return new Integer(gen_modelInstance.getTerritorio_Id());
        case 4: // id
          return new Integer(gen_modelInstance.getId());
        case 5: // domicilio
          return gen_modelInstance.getDomicilio();
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // localidad_Id
          gen_modelInstance.setLocalidad_Id((String)value);
          changed(info);
          break;
        case 1: // razonSocial
          gen_modelInstance.setRazonSocial((String)value);
          changed(info);
          break;
        case 2: // documento
          gen_modelInstance.setDocumento((String)value);
          changed(info);
          break;
        case 3: // territorio_Id
          gen_modelInstance.setTerritorio_Id(((Number)value).intValue());
          changed(info);
          break;
        case 4: // id
          gen_modelInstance.setId(((Number)value).intValue());
          changed(info);
          break;
        case 5: // domicilio
          gen_modelInstance.setDomicilio((String)value);
          changed(info);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected int wdGetInt(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 3: // territorio_Id
          return gen_modelInstance.getTerritorio_Id();
        case 4: // id
          return gen_modelInstance.getId();
        default:
          return super.wdGetInt(info);
      }
    }

    protected void wdSetInt(IGCIAttributeInfo info, int value) {
      switch (info.getIndex()) {
        case 3: // territorio_Id
          gen_modelInstance.setTerritorio_Id((int)value);
          changed(info);
          break;
        case 4: // id
          gen_modelInstance.setId((int)value);
          changed(info);
          break;
        default:
          super.wdSetInt(info, value);
          break;
      }
    }

    protected String wdGetString(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // localidad_Id
          return gen_modelInstance.getLocalidad_Id();
        case 1: // razonSocial
          return gen_modelInstance.getRazonSocial();
        case 2: // documento
          return gen_modelInstance.getDocumento();
        case 5: // domicilio
          return gen_modelInstance.getDomicilio();
        default:
          return super.wdGetString(info);
      }
    }

    protected void wdSetString(IGCIAttributeInfo info, String value) {
      switch (info.getIndex()) {
        case 0: // localidad_Id
          gen_modelInstance.setLocalidad_Id((java.lang.String)value);
          changed(info);
          break;
        case 1: // razonSocial
          gen_modelInstance.setRazonSocial((java.lang.String)value);
          changed(info);
          break;
        case 2: // documento
          gen_modelInstance.setDocumento((java.lang.String)value);
          changed(info);
          break;
        case 5: // domicilio
          gen_modelInstance.setDomicilio((java.lang.String)value);
          changed(info);
          break;
        default:
          super.wdSetString(info, value);
          break;
      }
    }

  }


  /**
   * Interface for the node 'TipoDocumento'.
   *
   * singleton = true, cardinality = _0_n, selection = _0_1
   */
  public static class ITipoDocumentoNode extends Node
  {
    private InternalConsulta_Comp gen_delegate;

    ITipoDocumentoNode(InternalConsulta_Comp delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(ITipoDocumentoElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @param model an instance of ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento needed for this model element
     * @return an element for this node
     */
    public IPrivateConsulta_Comp.ITipoDocumentoElement createTipoDocumentoElement(ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento model) {
      return (IPrivateConsulta_Comp.ITipoDocumentoElement)createElement(model);
    }

    /**
     * Binds a single ITipoDocumentoElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateConsulta_Comp.ITipoDocumentoElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /**
     * Creates a new ITipoDocumentoElement with the given model object 
     * and binds it to this node.
     * @param model an object of the model class
     */
    public void bind(ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento model) {
      bind(model == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(model));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateConsulta_Comp.ITipoDocumentoElement currentTipoDocumentoElement() {
      return (IPrivateConsulta_Comp.ITipoDocumentoElement) getCurrentElement();
    }

    /** 
     * Returns the element at the given index.
     * @param index the index of the element you want to get
     * @return the element or <code>null</code> if no element
     *         exists at that index
     */
    public IPrivateConsulta_Comp.ITipoDocumentoElement getTipoDocumentoElementAt(int index) {
      return (IPrivateConsulta_Comp.ITipoDocumentoElement) getElementAt(index);
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node TipoDocumento.
   */
  public static class ITipoDocumentoElement extends com.sap.tc.webdynpro.progmodel.context.ModelNodeElement
  {
    private InternalConsulta_Comp gen_delegate;

    private final ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento gen_modelInstance;

    public ITipoDocumentoElement(InternalConsulta_Comp delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info, Object modelInstance) {
      super(info, modelInstance);
      this.gen_modelInstance = (ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento) modelInstance;
      gen_delegate = delegate;
    }

    /**
     * Returns the referenced ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento.
     * @return the referenced ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento
     */
    public ar.com.quilmes.bue.mdm_clientes.model.externas.TipoDeDocumento modelObject() {
      return gen_modelInstance;
    }

    // attribute "id"
    public final static String ID = "id";

    /**
     * Returns the attribute id.
     */
    public int getId() {
      return gen_modelInstance.getId();
    }

    /**
     * Sets the attribute id.
     * @param value the new value
     */
    public void setId(int value) {
      gen_modelInstance.setId(value);
      changed(0);
    }
    
    // attribute "desc"
    public final static String DESC = "desc";

    /**
     * Returns the attribute desc.
     */
    public java.lang.String getDesc() {
      return gen_modelInstance.getDesc();
    }

    /**
     * Sets the attribute desc.
     * @param value the new value
     */
    public void setDesc(java.lang.String value) {
      gen_modelInstance.setDesc(value);
      changed(1);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // id
          return new Integer(gen_modelInstance.getId());
        case 1: // desc
          return gen_modelInstance.getDesc();
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // id
          gen_modelInstance.setId(((Number)value).intValue());
          changed(info);
          break;
        case 1: // desc
          gen_modelInstance.setDesc((String)value);
          changed(info);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected int wdGetInt(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // id
          return gen_modelInstance.getId();
        default:
          return super.wdGetInt(info);
      }
    }

    protected void wdSetInt(IGCIAttributeInfo info, int value) {
      switch (info.getIndex()) {
        case 0: // id
          gen_modelInstance.setId((int)value);
          changed(info);
          break;
        default:
          super.wdSetInt(info, value);
          break;
      }
    }

    protected String wdGetString(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 1: // desc
          return gen_modelInstance.getDesc();
        default:
          return super.wdGetString(info);
      }
    }

    protected void wdSetString(IGCIAttributeInfo info, String value) {
      switch (info.getIndex()) {
        case 1: // desc
          gen_modelInstance.setDesc((java.lang.String)value);
          changed(info);
          break;
        default:
          super.wdSetString(info, value);
          break;
      }
    }

  }

  /**
   * Returns the context root node.
   * @return the context root node.
   */
  IContextNode wdGetContext();

  /** Declared method. */
  ar.com.quilmes.bue.mdm_clientes.ejb.ConsultasExternas getConsultasExternasBean( );

  /** Declared method. */
  ar.com.quilmes.bue.mdm_clientes.ejb.ConsultasInternas getConsultasInternasBean( );

}
