// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
// ---------------------------------------------------------------------------
package ar.com.quilmes.consulta.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

public interface IPublicConsulta_CompInterface extends ar.com.quilmes.consulta.wdp.IExternalConsulta_CompInterface {


  /**
   * Interface for the node 'Context'.
   *
   * singleton = true, cardinality = _1_1, selection = _1_1
   */
  public static class IContextNode extends Node
  {
    private InternalConsulta_CompInterface gen_delegate;

    IContextNode(InternalConsulta_CompInterface delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    protected com.sap.tc.webdynpro.progmodel.context.Node createNode(IGCINodeInfo nodeInfo, com.sap.tc.webdynpro.progmodel.context.Node parentNode, com.sap.tc.webdynpro.progmodel.context.NodeElement parentElement) {
      if (nodeInfo == gen_delegate.infoContext)
        return new IPrivateConsulta_CompInterface.IContextNode(gen_delegate, nodeInfo, parentNode);
      return super.createNode(nodeInfo, parentNode, parentElement);
    }

    protected com.sap.tc.webdynpro.progmodel.context.NodeElement doCreateElement(IGCINodeInfo nodeInfo, Object reference) {
      if (nodeInfo == gen_delegate.infoContext) {
        return new IPrivateConsulta_CompInterface.IContextElement(gen_delegate, nodeInfo);
      }
      return super.doCreateElement(nodeInfo, reference);
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Provides access to the generic context API as described by IWDContext.
     */
    public IWDContext wdGetAPI() {
      return getContext();
    }

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IContextElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @return an element for this node
     */
    public IPrivateConsulta_CompInterface.IContextElement createContextElement() {
      return (IPrivateConsulta_CompInterface.IContextElement)createElement();
    }

    /**
     * Binds a single IContextElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateConsulta_CompInterface.IContextElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateConsulta_CompInterface.IContextElement currentContextElement() {
      return (IPrivateConsulta_CompInterface.IContextElement) getCurrentElement();
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node Context.
   */
  public static class IContextElement extends com.sap.tc.webdynpro.progmodel.context.NodeElement
  {
    private InternalConsulta_CompInterface gen_delegate;

    public IContextElement(InternalConsulta_CompInterface delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info) {
      super(info);
      gen_delegate = delegate;
    }

    // attribute "nro_cliente"
    public final static String NRO__CLIENTE = "nro_cliente";

    private int _nro_cliente;

    /**
     * Returns the attribute nro_cliente.
     */
    public int getNro_cliente() {
      return _nro_cliente;
    }

    /**
     * Sets the attribute nro_cliente.
     * @param value the new value
     */
    public void setNro_cliente(int value) {
      this._nro_cliente = value;
      changed(0);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          return new Integer(_nro_cliente);
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          this._nro_cliente = ((Number)value).intValue();
          changed(info);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected int wdGetInt(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          return _nro_cliente;
        default:
          return super.wdGetInt(info);
      }
    }

    protected void wdSetInt(IGCIAttributeInfo info, int value) {
      switch (info.getIndex()) {
        case 0: // nro_cliente
          this._nro_cliente = (int)value;
          changed(info);
          break;
        default:
          super.wdSetInt(info, value);
          break;
      }
    }

  }

  /**
   * Returns the context root node.
   * @return the context root node.
   */
  IContextNode wdGetContext();

  /** Fires event. */
  void wdFireEventTechnicalException( com.sap.caf.eu.gp.exception.api.GPTechnicalCallableObjectException technicalException );
  
}
