// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package com.quilmes.baja_cc;


/**
 * "GetCtaCteCliente_ExecuteResponse" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class GetCtaCteCliente_ExecuteResponse extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public GetCtaCteCliente_ExecuteResponse(CuentaCorriente modelInstance) {
    super(modelInstance, "GetCtaCteCliente_ExecuteResponse");
  }

  public CuentaCorriente getModelInstance() {
    return (CuentaCorriente) this.associatedModel();
  }
  
  private GetCtaCteCliente_ExecuteResponse(CuentaCorriente modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new GetCtaCteCliente_ExecuteResponse((CuentaCorriente)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> Mensajes
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Mensajes 
   *  @return value of ModelAttribute Mensajes */
  public com.quilmes.baja_cc.Mensajes getMensajes() {
    return (com.quilmes.baja_cc.Mensajes)getRelatedModelObject("Mensajes");
  }
  
  /** setter for 1:1 Relation Role -> Mensajes 
   *  @param value new value for 1:1 Relation Role  Mensajes */
  public void setMensajes(com.quilmes.baja_cc.Mensajes value) {
    setRelatedModelObject("Mensajes",value);
  }

  /* ***************************************************************************
   *  ModelAttribute -> Clisdoctc
   * **************************************************************************/
  /** getter for ModelAttribute -> Clisdoctc 
   *  @return value of ModelAttribute Clisdoctc */
  public double getClisdoctc() {
    return super.getAttributeValueAsDouble("Clisdoctc");
  }
  /** setter for ModelAttribute -> Clisdoctc 
   *  @param value new value for ModelAttribute Clisdoctc */
  public void setClisdoctc(double value) {
    super.setAttributeValueAsDouble("Clisdoctc", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Clisdodoct
   * **************************************************************************/
  /** getter for ModelAttribute -> Clisdodoct 
   *  @return value of ModelAttribute Clisdodoct */
  public double getClisdodoct() {
    return super.getAttributeValueAsDouble("Clisdodoct");
  }
  /** setter for ModelAttribute -> Clisdodoct 
   *  @param value new value for ModelAttribute Clisdodoct */
  public void setClisdodoct(double value) {
    super.setAttributeValueAsDouble("Clisdodoct", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Fmapgoabv
   * **************************************************************************/
  /** getter for ModelAttribute -> Fmapgoabv 
   *  @return value of ModelAttribute Fmapgoabv */
  public java.lang.String getFmapgoabv() {
    return (java.lang.String)super.getAttributeValue("Fmapgoabv");
  }
  /** setter for ModelAttribute -> Fmapgoabv 
   *  @param value new value for ModelAttribute Fmapgoabv */
  public void setFmapgoabv(java.lang.String value) {
    super.setAttributeValue("Fmapgoabv", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Sdoped
   * **************************************************************************/
  /** getter for ModelAttribute -> Sdoped 
   *  @return value of ModelAttribute Sdoped */
  public double getSdoped() {
    return super.getAttributeValueAsDouble("Sdoped");
  }
  /** setter for ModelAttribute -> Sdoped 
   *  @param value new value for ModelAttribute Sdoped */
  public void setSdoped(double value) {
    super.setAttributeValueAsDouble("Sdoped", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Totrech
   * **************************************************************************/
  /** getter for ModelAttribute -> Totrech 
   *  @return value of ModelAttribute Totrech */
  public double getTotrech() {
    return super.getAttributeValueAsDouble("Totrech");
  }
  /** setter for ModelAttribute -> Totrech 
   *  @param value new value for ModelAttribute Totrech */
  public void setTotrech(double value) {
    super.setAttributeValueAsDouble("Totrech", value);
  }
  /* ***************************************************************************
   *  ModelAttribute -> Totvenc
   * **************************************************************************/
  /** getter for ModelAttribute -> Totvenc 
   *  @return value of ModelAttribute Totvenc */
  public double getTotvenc() {
    return super.getAttributeValueAsDouble("Totvenc");
  }
  /** setter for ModelAttribute -> Totvenc 
   *  @param value new value for ModelAttribute Totvenc */
  public void setTotvenc(double value) {
    super.setAttributeValueAsDouble("Totvenc", value);
  }
}

