// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
// ---------------------------------------------------------------------------
package com.quilmes.baja.wdp;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import com.sap.tc.logging.Location;
import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

public class InternalAdjuntos_View
  implements IPrivateAdjuntos_View, com.sap.tc.webdynpro.progmodel.gci.IGCIViewDelegate
{

  /**
   * Location for this controller.
   */
  private static final Location logger = Location.getLocation(InternalAdjuntos_View.class);

  /**
   * Framework implementation of Controller that delegates to this.
   */
  private final com.sap.tc.webdynpro.progmodel.gci.IGCIView wdAlterEgo;

  /**
   * Delegate that implements application defined logic
   */
  private final com.quilmes.baja.Adjuntos_View delegate;


  // ---- Context --------------------------------------------------------------

  IGCINodeInfo infoAdjunto;
  IGCINodeInfo infoLogs;
  IGCINodeInfo infoAdjuntos;
  IGCINodeInfo infoFrecuencias;
  IGCINodeInfo infoTerritorios;
  IGCINodeInfo infoTicket;
  IGCINodeInfo infoContext;

  {

    infoAdjunto = GCIContext.createMappedNode("Adjunto", null, true, false, false, ".BajaUS.Adjunto", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("nombre", "nombre", false),
        GCIContext.createMappedAttribute("url", "url", false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoLogs = GCIContext.createMappedNode("Logs", ar.com.quilmes.bue.mdm_clientes.model.internas.LogModificacion.class, true, false, false, ".BajaUS.Ticket.Logs", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("fecha", "fecha", false),
        GCIContext.createMappedAttribute("nuevoDato", "nuevoDato", false),
        GCIContext.createMappedAttribute("campo", "campo", false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoAdjuntos = GCIContext.createMappedNode("Adjuntos", ar.com.quilmes.bue.mdm_clientes.model.internas.Adjunto.class, true, false, false, ".BajaUS.Ticket.Adjuntos", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("archivo", "archivo", false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoFrecuencias = GCIContext.createMappedNode("Frecuencias", ar.com.quilmes.bue.mdm_clientes.model.internas.Frecuencia.class, false, false, false, ".BajaUS.Ticket.Territorios.Frecuencias", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("codDiaSemana", "codDiaSemana", false),
        GCIContext.createMappedAttribute("tipoFrecuencia", "tipoFrecuencia", false),
        GCIContext.createMappedAttribute("codCliVisitAntes", "codCliVisitAntes", false),
        GCIContext.createMappedAttribute("diaSemanaDesc", "diaSemanaDesc", false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoTerritorios = GCIContext.createMappedNode("Territorios", ar.com.quilmes.bue.mdm_clientes.model.internas.TerritorioTabla.class, true, false, false, ".BajaUS.Ticket.Territorios", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("codTerritorio", "codTerritorio", false),
        GCIContext.createMappedAttribute("centroDespacho", "centroDespacho", false),
        GCIContext.createMappedAttribute("canalVenta", "canalVenta", false),
        GCIContext.createMappedAttribute("codTerritorioGeo", "codTerritorioGeo", false),
      },
      new IGCINodeInfo[] {
        infoFrecuencias,
      }
    );

    infoTicket = GCIContext.createMappedNode("Ticket", ar.com.quilmes.bue.mdm_clientes.model.internas.Ticket.class, true, false, false, ".BajaUS.Ticket", true, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createMappedAttribute("motivoBaja", "motivoBaja", false),
        GCIContext.createMappedAttribute("perfilCliente", "perfilCliente", false),
        GCIContext.createMappedAttribute("listaPrecioMaximo", "listaPrecioMaximo", false),
        GCIContext.createMappedAttribute("tienePromocion", "tienePromocion", false),
        GCIContext.createMappedAttribute("tipoClienteCom", "tipoClienteCom", false),
        GCIContext.createMappedAttribute("codFormaAtencion", "codFormaAtencion", false),
        GCIContext.createMappedAttribute("excIvaFechaDesde", "excIvaFechaDesde", false),
        GCIContext.createMappedAttribute("provinciaDesc", "provinciaDesc", false),
        GCIContext.createMappedAttribute("codClienteAdy", "codClienteAdy", false),
        GCIContext.createMappedAttribute("fechaAniversario", "fechaAniversario", false),
        GCIContext.createMappedAttribute("nroSolicitud", "nroSolicitud", false),
        GCIContext.createMappedAttribute("tipoVtaFsMercaderia", "tipoVtaFsMercaderia", false),
        GCIContext.createMappedAttribute("formaPago", "formaPago", false),
        GCIContext.createMappedAttribute("identificacionJuridica", "identificacionJuridica", false),
        GCIContext.createMappedAttribute("carpeta", "carpeta", false),
        GCIContext.createMappedAttribute("moneda", "moneda", false),
        GCIContext.createMappedAttribute("localidadDesc", "localidadDesc", false),
        GCIContext.createMappedAttribute("idMensajeFactura", "idMensajeFactura", false),
        GCIContext.createMappedAttribute("nombreFantasia", "nombreFantasia", false),
        GCIContext.createMappedAttribute("codLocalidad", "codLocalidad", false),
        GCIContext.createMappedAttribute("numero", "numero", false),
        GCIContext.createMappedAttribute("localidadTrDeuda", "localidadTrDeuda", false),
        GCIContext.createMappedAttribute("numeroDocumento", "numeroDocumento", false),
        GCIContext.createMappedAttribute("codClienteTransfiereDeuda", "codClienteTransfiereDeuda", false),
        GCIContext.createMappedAttribute("tipoCobranza", "tipoCobranza", false),
        GCIContext.createMappedAttribute("aceptaDesdUnifPedido", "aceptaDesdUnifPedido", false),
        GCIContext.createMappedAttribute("nroIIBB", "nroIIBB", false),
        GCIContext.createMappedAttribute("porcExcIIBB", "porcExcIIBB", false),
        GCIContext.createMappedAttribute("esExcluivo", "esExcluivo", false),
        GCIContext.createMappedAttribute("razonSocial", "razonSocial", false),
        GCIContext.createMappedAttribute("transfiereHistoricoVentas", "transfiereHistoricoVentas", false),
        GCIContext.createMappedAttribute("excIIBBFechaHasta", "excIIBBFechaHasta", false),
        GCIContext.createMappedAttribute("sociedad", "sociedad", false),
        GCIContext.createMappedAttribute("tipoIvaDesc", "tipoIvaDesc", false),
        GCIContext.createMappedAttribute("esquema", "esquema", false),
        GCIContext.createMappedAttribute("calle", "calle", false),
        GCIContext.createMappedAttribute("puerta", "puerta", false),
        GCIContext.createMappedAttribute("observacionesMd", "observacionesMd", false),
        GCIContext.createMappedAttribute("tipoMaqVend", "tipoMaqVend", false),
        GCIContext.createMappedAttribute("codCategCliente", "codCategCliente", false),
        GCIContext.createMappedAttribute("observacionesUs", "observacionesUs", false),
        GCIContext.createMappedAttribute("cp", "cp", false),
        GCIContext.createMappedAttribute("razonSocialAbreviada", "razonSocialAbreviada", false),
        GCIContext.createMappedAttribute("usuarioAprobador", "usuarioAprobador", false),
        GCIContext.createMappedAttribute("formaEntregaCtaCte", "formaEntregaCtaCte", false),
        GCIContext.createMappedAttribute("agrupacionComercial", "agrupacionComercial", false),
        GCIContext.createMappedAttribute("cantGeocodificacion", "cantGeocodificacion", false),
        GCIContext.createMappedAttribute("polVtaCal3", "polVtaCal3", false),
        GCIContext.createMappedAttribute("repositorio", "repositorio", false),
        GCIContext.createMappedAttribute("ramo", "ramo", false),
        GCIContext.createMappedAttribute("tipoIVA", "tipoIVA", false),
        GCIContext.createMappedAttribute("fechaVencimientoLicencia", "fechaVencimientoLicencia", false),
        GCIContext.createMappedAttribute("direccionTrDeuda", "direccionTrDeuda", false),
        GCIContext.createMappedAttribute("subCanalMkt", "subCanalMkt", false),
        GCIContext.createMappedAttribute("categoriaClienteDesc", "categoriaClienteDesc", false),
        GCIContext.createMappedAttribute("fechaUltVerif", "fechaUltVerif", false),
        GCIContext.createMappedAttribute("usuarioSolicitante", "usuarioSolicitante", false),
        GCIContext.createMappedAttribute("tipoDocumentoDesc", "tipoDocumentoDesc", false),
        GCIContext.createMappedAttribute("transfDeudaEnv", "transfDeudaEnv", false),
        GCIContext.createMappedAttribute("pagaSeguro", "pagaSeguro", false),
        GCIContext.createMappedAttribute("tipoVtaFsEnvases", "tipoVtaFsEnvases", false),
        GCIContext.createMappedAttribute("imprimeRemito", "imprimeRemito", false),
        GCIContext.createMappedAttribute("codTipoDocumento", "codTipoDocumento", false),
        GCIContext.createMappedAttribute("nroImpuestoInterno", "nroImpuestoInterno", false),
        GCIContext.createMappedAttribute("cuitTrDeuda", "cuitTrDeuda", false),
        GCIContext.createMappedAttribute("polVtaCal2", "polVtaCal2", false),
        GCIContext.createMappedAttribute("nroTicketCrm", "nroTicketCrm", false),
        GCIContext.createMappedAttribute("esAltaBaja", "esAltaBaja", false),
        GCIContext.createMappedAttribute("excIvaFechaHasta", "excIvaFechaHasta", false),
        GCIContext.createMappedAttribute("codNuevoClienteCCQ", "codNuevoClienteCCQ", false),
        GCIContext.createMappedAttribute("autVentaAlochol", "autVentaAlochol", false),
        GCIContext.createMappedAttribute("excIIBBFechaDesde", "excIIBBFechaDesde", false),
        GCIContext.createMappedAttribute("mesajeFactura", "mesajeFactura", false),
        GCIContext.createMappedAttribute("coordenadaX", "coordenadaX", false),
        GCIContext.createMappedAttribute("nroTicketAsociado", "nroTicketAsociado", false),
        GCIContext.createMappedAttribute("banco", "banco", false),
        GCIContext.createMappedAttribute("ctaCteExterna", "ctaCteExterna", false),
        GCIContext.createMappedAttribute("fechaCierre", "fechaCierre", false),
        GCIContext.createMappedAttribute("tipoEmpresa", "tipoEmpresa", false),
        GCIContext.createMappedAttribute("tipoIIBB", "tipoIIBB", false),
        GCIContext.createMappedAttribute("porcExcIva", "porcExcIva", false),
        GCIContext.createMappedAttribute("codCuentaMadre", "codCuentaMadre", false),
        GCIContext.createMappedAttribute("nroLicVentaAlochol", "nroLicVentaAlochol", false),
        GCIContext.createMappedAttribute("cobrador", "cobrador", false),
        GCIContext.createMappedAttribute("codCliente", "codCliente", false),
        GCIContext.createMappedAttribute("subCanalMktDesc", "subCanalMktDesc", false),
        GCIContext.createMappedAttribute("personeriaJuridica", "personeriaJuridica", false),
        GCIContext.createMappedAttribute("tipoClienteCondVta", "tipoClienteCondVta", false),
        GCIContext.createMappedAttribute("coordenadaY", "coordenadaY", false),
        GCIContext.createMappedAttribute("telefono", "telefono", false),
        GCIContext.createMappedAttribute("tipoClienteContab", "tipoClienteContab", false),
        GCIContext.createMappedAttribute("razonSocialClTrDeuda", "razonSocialClTrDeuda", false),
        GCIContext.createMappedAttribute("segmentoVta", "segmentoVta", false),
        GCIContext.createMappedAttribute("listaPrecioBasico", "listaPrecioBasico", false),
        GCIContext.createMappedAttribute("fechaCreacion", "fechaCreacion", false),
        GCIContext.createMappedAttribute("observacionesGeo", "observacionesGeo", false),
        GCIContext.createMappedAttribute("interseccion", "interseccion", false),
        GCIContext.createMappedAttribute("asigStock", "asigStock", false),
        GCIContext.createMappedAttribute("tipoSolicitud", "tipoSolicitud", false),
        GCIContext.createMappedAttribute("comprador", "comprador", false),
        GCIContext.createMappedAttribute("fueCensado", "fueCensado", false),
        GCIContext.createMappedAttribute("email", "email", false),
        GCIContext.createMappedAttribute("polVtaCal1", "polVtaCal1", false),
        GCIContext.createMappedAttribute("estadoTicket", "estadoTicket", false),
        GCIContext.createMappedAttribute("codProvincia", "codProvincia", false),
      },
      new IGCINodeInfo[] {
        infoLogs,
        infoAdjuntos,
        infoTerritorios,
      }
    );

    infoContext = GCIContext.createNode("Context", null, true, true, false, true, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("adjunto1", "ddic:com.sap.ide.webdynpro.uielementdefinitions.Resource", null, null, false, false),
        GCIContext.createAttribute("MD", "ddic:com.sap.ide.webdynpro.uielementdefinitions.Visibility", null, null, false, false),
        GCIContext.createAttribute("US", "ddic:com.sap.ide.webdynpro.uielementdefinitions.Visibility", null, null, false, false),
        GCIContext.createMappedAttribute("carpeta", ".BajaUS.carpeta", false),
        GCIContext.createMappedAttribute("repositorio", ".BajaUS.repositorio", false),
        GCIContext.createAttribute("cantidad", "ddic:com.sap.dictionary.integer", null, null, false, false),
        GCIContext.createAttribute("tamano", "ddic:com.sap.dictionary.integer", null, null, false, false),
        GCIContext.createMappedAttribute("esquema", ".BajaUS.esquema", false),
        GCIContext.createMappedAttribute("master", ".BajaUS.master", false),
        GCIContext.createMappedAttribute("segmento", ".BajaUS.segmento", false),
        GCIContext.createAttribute("url", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createMappedAttribute("nro_solicitud", ".BajaUS.nro_solicitud", false),
        GCIContext.createMappedAttribute("flag_adjunto", ".BajaUS.flag_adjunto", false),
        GCIContext.createAttribute("cant_us", "ddic:com.sap.dictionary.integer", null, null, false, false),
      },
      new IGCINodeInfo[] {
        infoAdjunto,
        infoTicket,
      }
    );

  }
  
  private IContextNode contextNode;

  private void wdInitContextNode() {
    contextNode = new IContextNode(this, infoContext, (Node)null);
  }

  public IWDNode wdGetRootNode() {
    return contextNode;
  }

  public IContextNode wdGetContext() {
    return contextNode;
  }


  // ---- Actions --------------------------------------------------------------

  /**
   * Returns the action with name <code>volver</code>.
   */
  public IWDAction wdGetVolverAction() {
    return wdAlterEgo.getAction("volver");
  }

  /**
   * Returns the action with name <code>adjuntar</code>.
   */
  public IWDAction wdGetAdjuntarAction() {
    return wdAlterEgo.getAction("adjuntar");
  }

  /**
   * Returns the action with name <code>borrar</code>.
   */
  public IWDAction wdGetBorrarAction() {
    return wdAlterEgo.getAction("borrar");
  }

  /**
   * Create a new action for this controller. A unique name for the action is generated automatially.
   * @param eventHandler is the action's eventhandler with proper signature
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateAction(WDActionEventHandler eventHandler, String text) {
    return wdAlterEgo.createAction(null, eventHandler, text, null);
  }

  /**
   * Create a new action with the given name for this controller
   * @param eventHandler is the action's eventhandler with proper signature
   * @param name is the action's name
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateNamedAction(WDActionEventHandler eventHandler, String name, String text) {
    return wdAlterEgo.createAction(name, eventHandler, text, null);
  }

  // ---- Controller part ------------------------------------------------------

  /**
   * Creates a new instance of this controller.
   */
  public InternalAdjuntos_View(com.sap.tc.webdynpro.progmodel.gci.IGCIView alterEgo) {
    this.wdAlterEgo = alterEgo;
    wdInitContextNode();
    this.delegate = new com.quilmes.baja.Adjuntos_View((IPrivateAdjuntos_View) this);
    wdAlterEgo.createAction("volver", WDActionEventHandler.VOLVER, wdAlterEgo.getLocalizedText("action.Adjuntos_View.volver"), "");
    wdAlterEgo.createAction("adjuntar", WDActionEventHandler.ADJUNTAR, wdAlterEgo.getLocalizedText("action.Adjuntos_View.adjuntar"), "");
    wdAlterEgo.createAction("borrar", WDActionEventHandler.BORRAR, wdAlterEgo.getLocalizedText("action.Adjuntos_View.borrar"), "");
  }

  /**
   * Returns the public API for this controller instance.
   */
  public com.sap.tc.webdynpro.progmodel.api.IWDViewController wdGetAPI() {
    return (com.sap.tc.webdynpro.progmodel.api.IWDViewController) wdAlterEgo;
  }

  /**
   * Hook method called to initialize view controller.
   */
  public void wdDoInit() {
    logger.pathT("entering: wdDoInit");
    delegate.wdDoInit();
    logger.pathT("exiting: wdDoInit"); 
  }

  /**
   * Hook method called to clean up view controller.
   */
  public void wdDoExit() {
    logger.pathT("entering: wdDoExit");
    delegate.wdDoExit();
    logger.pathT("exiting: wdDoExit"); 
  }

  public Object wdInvokeEventHandler(String handlerName, IWDCustomEvent event)
    throws NoSuchMethodException {
    
    logger.pathT("entering: wdInvokeEventHandler", new Object[] { handlerName } );
    try {
      if("onPlugentradaadjuntos".equals(handlerName)) {

        delegate.onPlugentradaadjuntos(event );
        return null;
      }
      if("onActionvolver".equals(handlerName)) {

        delegate.onActionvolver(event );
        return null;
      }
      if("onActionadjuntar".equals(handlerName)) {

        delegate.onActionadjuntar(event );
        return null;
      }
      if("onActionborrar".equals(handlerName)) {

        delegate.onActionborrar(event );
        return null;
      }
      throw new NoSuchMethodException("Eventhandler " + handlerName + " not found for event " + event.getName());
    } finally {
      logger.pathT("exiting: wdInvokeEventHandler"); 
    }
  }

  public void onPlugentradaadjuntos(IWDCustomEvent wdEvent ) {
    delegate.onPlugentradaadjuntos(wdEvent );
  }

  public void onActionvolver(IWDCustomEvent wdEvent ) {
    delegate.onActionvolver(wdEvent );
  }

  public void onActionadjuntar(IWDCustomEvent wdEvent ) {
    delegate.onActionadjuntar(wdEvent );
  }

  public void onActionborrar(IWDCustomEvent wdEvent ) {
    delegate.onActionborrar(wdEvent );
  }

  /** outgoing controller usage */
  public com.quilmes.baja.wdp.IPublicBajaUS wdGetBajaUSController() {
    return
      (com.quilmes.baja.wdp.IPublicBajaUS)
        wdAlterEgo
          .getComponentGCI()
            .getPublicInterface("BajaUS");
  }


  // ---- UI Tree ---------------------------------------------------------

  // create UI tree
  public com.sap.tc.webdynpro.progmodel.api.IWDViewElement wdCreateUITree()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer1());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer2());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer3());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer4());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer5());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer6());
    _RootUIElementContainer.addChild(wdCreateUITreeForRootUIElementContainer9());
    return (_RootUIElementContainer);
  }

  // create UI tree for RootUIElementContainer1
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer1()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer1");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _RootUIElementContainer1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _RootUIElementContainer1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout _RootUIElementContainer1__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout)
        _RootUIElementContainer1.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader _PageHeader
      = (com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.pattern.api.IWDPageHeader.class,
          "PageHeader");  
    _PageHeader.setTitle(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer1.PageHeader.Property.title.value"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _PageHeader__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _PageHeader.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer1.addChild(_PageHeader);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _HorizontalGutter__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _HorizontalGutter.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    _RootUIElementContainer1.addChild(_HorizontalGutter);
    return (_RootUIElementContainer1);
  }
  
  // create UI tree for RootUIElementContainer2
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer2()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer2
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer2");  
    _RootUIElementContainer2.setWidth("250px");
    _RootUIElementContainer2.bindVisible("US");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _RootUIElementContainer2__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _RootUIElementContainer2.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout _RootUIElementContainer2__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout)
        _RootUIElementContainer2.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFileUpload _FileUpload1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFileUpload)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFileUpload.class,
          "FileUpload1");  
    _FileUpload1.bindVisible("US");
    _FileUpload1.bindResource("adjunto1");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData _FileUpload1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData)
        _FileUpload1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData.class);
    _RootUIElementContainer2.addChild(_FileUpload1);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _adjuntar
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class,
          "adjuntar");  
    _adjuntar.setWidth("50px");
    _adjuntar.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer2.adjuntar.text"));
    _adjuntar.bindVisible("US");
    _adjuntar.setOnAction(wdAlterEgo.getAction("adjuntar"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData _adjuntar__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData)
        _adjuntar.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData.class);
    _RootUIElementContainer2.addChild(_adjuntar);
    return (_RootUIElementContainer2);
  }
  
  // create UI tree for RootUIElementContainer3
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer3()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer3
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer3");  
    _RootUIElementContainer3.bindVisible("US");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _RootUIElementContainer3__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _RootUIElementContainer3.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _RootUIElementContainer3__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout)
        _RootUIElementContainer3.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter2
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter2");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _HorizontalGutter2__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _HorizontalGutter2.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _HorizontalGutter2__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer3.addChild(_HorizontalGutter2);
    return (_RootUIElementContainer3);
  }
  
  // create UI tree for RootUIElementContainer4
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer4()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer4
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer4");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _RootUIElementContainer4__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _RootUIElementContainer4.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _RootUIElementContainer4__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout)
        _RootUIElementContainer4.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable _Table
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable.class,
          "Table");  
    _Table.bindDataSource("Adjunto");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Table__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Table.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Table__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn _url
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn.class,
          "url");  

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _url_header
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "url_header");  
    _url_header.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer4.Table.OutgoingAggregation.GroupedColumns.AggregatedObject.url.Header.text"));
    _url.setHeader(_url_header);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLinkToURL _url_editor
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLinkToURL)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLinkToURL.class,
          "url_editor");  
    _url_editor.setTarget("_BLANK");
    _url_editor.bindText("Adjunto.nombre");
    _url_editor.bindReference("Adjunto.url");
    _url.setTableCellEditor(_url_editor);
    _Table.addGroupedColumn(_url);
    _RootUIElementContainer4.addChild(_Table);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable _Table_md
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTable.class,
          "Table_md");  
    _Table_md.setVisible(com.sap.tc.webdynpro.progmodel.api.WDVisibility.valueOf("none"));
    _Table_md.bindDataSource("Ticket.Adjuntos");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Table_md__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Table_md.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Table_md__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn _archivo
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTableColumn.class,
          "archivo");  

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _archivo_header
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "archivo_header");  
    _archivo_header.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer4.Table_md.OutgoingAggregation.GroupedColumns.AggregatedObject.archivo.Header.text"));
    _archivo.setHeader(_archivo_header);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView _archivo_editor
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView.class,
          "archivo_editor");  
    _archivo_editor.bindText("Ticket.Adjuntos.archivo");
    _archivo.setTableCellEditor(_archivo_editor);
    _Table_md.addGroupedColumn(_archivo);
    _RootUIElementContainer4.addChild(_Table_md);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter1");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _HorizontalGutter1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _HorizontalGutter1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _HorizontalGutter1__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer4.addChild(_HorizontalGutter1);
    return (_RootUIElementContainer4);
  }
  
  // create UI tree for RootUIElementContainer5
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer5()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer5
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer5");  
    _RootUIElementContainer5.setWidth("100px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _RootUIElementContainer5__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _RootUIElementContainer5.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout _RootUIElementContainer5__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout)
        _RootUIElementContainer5.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _volver
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class,
          "volver");  
    _volver.setWidth("50px");
    _volver.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer5.volver.text"));
    _volver.setOnAction(wdAlterEgo.getAction("volver"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData _volver__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData)
        _volver.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData.class);
    _RootUIElementContainer5.addChild(_volver);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton _borrar
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDButton.class,
          "borrar");  
    _borrar.setWidth("50px");
    _borrar.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer5.borrar.text"));
    _borrar.bindVisible("US");
    _borrar.setOnAction(wdAlterEgo.getAction("borrar"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData _borrar__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData)
        _borrar.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData.class);
    _RootUIElementContainer5.addChild(_borrar);
    return (_RootUIElementContainer5);
  }
  
  // create UI tree for RootUIElementContainer6
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer6()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer6
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer6");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _RootUIElementContainer6__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _RootUIElementContainer6.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _RootUIElementContainer6__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout)
        _RootUIElementContainer6.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter3
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter3");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _HorizontalGutter3__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _HorizontalGutter3.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _HorizontalGutter3__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer6.addChild(_HorizontalGutter3);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView _TextView
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTextView.class,
          "TextView");  
    _TextView.setDesign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDTextViewDesign.valueOf("groupTitle"));
    _TextView.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer6.TextView.text"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _TextView__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _TextView.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _TextView__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer6.addChild(_TextView);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter _HorizontalGutter4
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDHorizontalGutter.class,
          "HorizontalGutter4");  
    _HorizontalGutter4.setVisible(com.sap.tc.webdynpro.progmodel.api.WDVisibility.valueOf("blank"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _HorizontalGutter4__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _HorizontalGutter4.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _HorizontalGutter4__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer6.addChild(_HorizontalGutter4);
    return (_RootUIElementContainer6);
  }
  
  // create UI tree for RootUIElementContainer9
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer9()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer9
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer9");  
    _RootUIElementContainer9.setWidth("400px");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData _RootUIElementContainer9__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData)
        _RootUIElementContainer9.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDFlowData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout _RootUIElementContainer9__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout)
        _RootUIElementContainer9.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixLayout.class);
    _RootUIElementContainer9.addChild(wdCreateUITreeForRootUIElementContainer7());
    _RootUIElementContainer9.addChild(wdCreateUITreeForRootUIElementContainer8());
    return (_RootUIElementContainer9);
  }
  
  // create UI tree for RootUIElementContainer7
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer7()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer7
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer7");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData _RootUIElementContainer7__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData)
        _RootUIElementContainer7.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _RootUIElementContainer7__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout)
        _RootUIElementContainer7.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Label0
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class,
          "Label0");  
    _Label0.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer9.RootUIElementContainer7.Label0.text"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Label0__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Label0.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Label0__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer7.addChild(_Label0);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Label
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class,
          "Label");  
    _Label.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer9.RootUIElementContainer7.Label.text"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Label__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Label.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Label__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer7.addChild(_Label);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Label1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class,
          "Label1");  
    _Label1.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer9.RootUIElementContainer7.Label1.text"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Label1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Label1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Label1__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer7.addChild(_Label1);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel _Label2
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDLabel.class,
          "Label2");  
    _Label2.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer9.RootUIElementContainer7.Label2.text"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Label2__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Label2.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Label2__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer7.addChild(_Label2);
    return (_RootUIElementContainer7);
  }
  
  // create UI tree for RootUIElementContainer8
  private com.sap.tc.webdynpro.progmodel.api.IWDUIElement wdCreateUITreeForRootUIElementContainer8()
  {

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer _RootUIElementContainer8
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDTransparentContainer.class,
          "RootUIElementContainer8");  
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData _RootUIElementContainer8__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData)
        _RootUIElementContainer8.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDMatrixData.class);
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout _RootUIElementContainer8__Layout
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout)
        _RootUIElementContainer8.createLayout(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridLayout.class);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _Caption1
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "Caption1");  
    _Caption1.bindText("cantidad");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Caption1__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Caption1.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Caption1__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer8.addChild(_Caption1);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _Caption2
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "Caption2");  
    _Caption2.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer9.RootUIElementContainer8.Caption2.text"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Caption2__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Caption2.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Caption2__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer8.addChild(_Caption2);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _Caption3
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "Caption3");  
    _Caption3.bindText("tamano");
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Caption3__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Caption3.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Caption3__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer8.addChild(_Caption3);

    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption _Caption4
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption)
        wdAlterEgo.createElement(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDCaption.class,
          "Caption4");  
    _Caption4.setText(wdAlterEgo.getLocalizedText("view.Adjuntos_View.RootUIElementContainer9.RootUIElementContainer8.Caption4.text"));
    com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData _Caption4__LayoutData
      = (com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData)
        _Caption4.createLayoutData(com.sap.tc.webdynpro.clientserver.uielib.standard.api.IWDGridData.class);
    _Caption4__LayoutData.setHAlign(com.sap.tc.webdynpro.clientserver.uielib.standard.api.WDCellHAlign.valueOf("left"));
    _RootUIElementContainer8.addChild(_Caption4);
    return (_RootUIElementContainer8);
  }
  

  /**
   * Hook method called to modify view before rendering. Access to UI elements
   * is via the given view API only!
   * 
   * @param firstTime indicates whether the hook is called for the first time
   * during the lifetime of this view
   */
  public void wdDoModifyView(IWDView view, boolean firstTime) {
    logger.pathT("entering: doModifyView");
    com.quilmes.baja.Adjuntos_View.wdDoModifyView((IPrivateAdjuntos_View) this, (IPrivateAdjuntos_View.IContextNode) this.wdGetContext(), view, firstTime);
    logger.pathT("exiting: doModifyView"); 
  }

  /** outbound plug */
  public void wdFirePlugSalidaadjuntos_v( ) {
    Map parameters = Collections.EMPTY_MAP;
    wdAlterEgo.navigate("salidaadjuntos_v", parameters);
  }


}
