// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
// ---------------------------------------------------------------------------
package com.quilmes.baja.wdp;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import com.sap.tc.logging.Location;
import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

public class InternalBajaUS
  implements IPrivateBajaUS, com.sap.tc.webdynpro.progmodel.gci.IGCIComponentDelegate
{

  /**
   * Location for this controller.
   */
  private static final Location logger = Location.getLocation(InternalBajaUS.class);

  /**
   * Framework implementation of Controller that delegates to this.
   */
  private final com.sap.tc.webdynpro.progmodel.gci.IGCIComponent wdAlterEgo;

  /**
   * Delegate that implements application defined logic
   */
  private final com.quilmes.baja.BajaUS delegate;


  // ---- Context --------------------------------------------------------------

  IGCINodeInfo infoAdjunto;
  IGCINodeInfo infoLogs;
  IGCINodeInfo infoAdjuntos;
  IGCINodeInfo infoFrecuencias;
  IGCINodeInfo infoTerritorios;
  IGCINodeInfo infoTicket;
  IGCINodeInfo infoContext;

  {

    infoAdjunto = GCIContext.createNode("Adjunto", null, true, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("nombre", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("url", "ddic:com.sap.dictionary.string", null, null, false, false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoLogs = GCIContext.createNode("Logs", ar.com.quilmes.bue.mdm_clientes.model.internas.LogModificacion.class, true, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("fecha", "ddic:com.sap.dictionary.date", null, "fecha", false, false),
        GCIContext.createAttribute("nuevoDato", "ddic:com.sap.dictionary.string", null, "nuevoDato", false, false),
        GCIContext.createAttribute("campo", "ddic:com.sap.dictionary.string", null, "campo", false, false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoAdjuntos = GCIContext.createNode("Adjuntos", ar.com.quilmes.bue.mdm_clientes.model.internas.Adjunto.class, true, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("archivo", "ddic:com.sap.dictionary.string", null, "archivo", false, false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoFrecuencias = GCIContext.createNode("Frecuencias", ar.com.quilmes.bue.mdm_clientes.model.internas.Frecuencia.class, false, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("codDiaSemana", "ddic:com.sap.dictionary.integerObject", null, "codDiaSemana", false, false),
        GCIContext.createAttribute("tipoFrecuencia", "ddic:com.sap.dictionary.string", null, "tipoFrecuencia", false, false),
        GCIContext.createAttribute("codCliVisitAntes", "ddic:com.sap.dictionary.integerObject", null, "codCliVisitAntes", false, false),
        GCIContext.createAttribute("diaSemanaDesc", "ddic:com.sap.dictionary.string", null, "diaSemanaDesc", false, false),
      },
      (IGCINodeInfo[])null // no child nodes
    );

    infoTerritorios = GCIContext.createNode("Territorios", ar.com.quilmes.bue.mdm_clientes.model.internas.TerritorioTabla.class, true, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("codTerritorio", "ddic:com.sap.dictionary.integerObject", null, "codTerritorio", false, false),
        GCIContext.createAttribute("centroDespacho", "ddic:com.sap.dictionary.string", null, "centroDespacho", false, false),
        GCIContext.createAttribute("canalVenta", "ddic:com.sap.dictionary.integerObject", null, "canalVenta", false, false),
        GCIContext.createAttribute("codTerritorioGeo", "ddic:com.sap.dictionary.integerObject", null, "codTerritorioGeo", false, false),
      },
      new IGCINodeInfo[] {
        infoFrecuencias,
      }
    );

    infoTicket = GCIContext.createNode("Ticket", ar.com.quilmes.bue.mdm_clientes.model.internas.Ticket.class, true, false, true, false, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("motivoBaja", "ddic:com.sap.dictionary.string", null, "motivoBaja", false, false),
        GCIContext.createAttribute("perfilCliente", "ddic:com.sap.dictionary.string", null, "perfilCliente", false, false),
        GCIContext.createAttribute("listaPrecioMaximo", "ddic:com.sap.dictionary.integerObject", null, "listaPrecioMaximo", false, false),
        GCIContext.createAttribute("tienePromocion", "ddic:com.sap.dictionary.string", null, "tienePromocion", false, false),
        GCIContext.createAttribute("tipoClienteCom", "ddic:com.sap.dictionary.integerObject", null, "tipoClienteCom", false, false),
        GCIContext.createAttribute("codFormaAtencion", "ddic:com.sap.dictionary.integerObject", null, "codFormaAtencion", false, false),
        GCIContext.createAttribute("excIvaFechaDesde", "ddic:com.sap.dictionary.date", null, "excIvaFechaDesde", false, false),
        GCIContext.createAttribute("provinciaDesc", "ddic:com.sap.dictionary.string", null, "provinciaDesc", false, false),
        GCIContext.createAttribute("codClienteAdy", "ddic:com.sap.dictionary.integerObject", null, "codClienteAdy", false, false),
        GCIContext.createAttribute("fechaAniversario", "ddic:com.sap.dictionary.date", null, "fechaAniversario", false, false),
        GCIContext.createAttribute("nroSolicitud", "ddic:com.sap.dictionary.long", null, "nroSolicitud", false, false),
        GCIContext.createAttribute("tipoVtaFsMercaderia", "ddic:com.sap.dictionary.integerObject", null, "tipoVtaFsMercaderia", false, false),
        GCIContext.createAttribute("formaPago", "ddic:com.sap.dictionary.integerObject", null, "formaPago", false, false),
        GCIContext.createAttribute("identificacionJuridica", "ddic:com.sap.dictionary.string", null, "identificacionJuridica", false, false),
        GCIContext.createAttribute("carpeta", "ddic:com.sap.dictionary.string", null, "carpeta", false, false),
        GCIContext.createAttribute("moneda", "ddic:com.sap.dictionary.string", null, "moneda", false, false),
        GCIContext.createAttribute("localidadDesc", "ddic:com.sap.dictionary.string", null, "localidadDesc", false, false),
        GCIContext.createAttribute("idMensajeFactura", "ddic:com.sap.dictionary.integerObject", null, "idMensajeFactura", false, false),
        GCIContext.createAttribute("nombreFantasia", "ddic:com.sap.dictionary.string", null, "nombreFantasia", false, false),
        GCIContext.createAttribute("codLocalidad", "ddic:com.sap.dictionary.string", null, "codLocalidad", false, false),
        GCIContext.createAttribute("numero", "ddic:com.sap.dictionary.string", null, "numero", false, false),
        GCIContext.createAttribute("localidadTrDeuda", "ddic:com.sap.dictionary.string", null, "localidadTrDeuda", false, false),
        GCIContext.createAttribute("numeroDocumento", "ddic:com.sap.dictionary.string", null, "numeroDocumento", false, false),
        GCIContext.createAttribute("codClienteTransfiereDeuda", "ddic:com.sap.dictionary.integerObject", null, "codClienteTransfiereDeuda", false, false),
        GCIContext.createAttribute("tipoCobranza", "ddic:com.sap.dictionary.integerObject", null, "tipoCobranza", false, false),
        GCIContext.createAttribute("aceptaDesdUnifPedido", "ddic:com.sap.dictionary.string", null, "aceptaDesdUnifPedido", false, false),
        GCIContext.createAttribute("nroIIBB", "ddic:com.sap.dictionary.string", null, "nroIIBB", false, false),
        GCIContext.createAttribute("porcExcIIBB", "ddic:com.sap.dictionary.decimal", null, "porcExcIIBB", false, false),
        GCIContext.createAttribute("esExcluivo", "ddic:com.sap.dictionary.string", null, "esExcluivo", false, false),
        GCIContext.createAttribute("razonSocial", "ddic:com.sap.dictionary.string", null, "razonSocial", false, false),
        GCIContext.createAttribute("transfiereHistoricoVentas", "ddic:com.sap.dictionary.string", null, "transfiereHistoricoVentas", false, false),
        GCIContext.createAttribute("excIIBBFechaHasta", "ddic:com.sap.dictionary.date", null, "excIIBBFechaHasta", false, false),
        GCIContext.createAttribute("sociedad", "ddic:com.sap.dictionary.string", null, "sociedad", false, false),
        GCIContext.createAttribute("tipoIvaDesc", "ddic:com.sap.dictionary.string", null, "tipoIvaDesc", false, false),
        GCIContext.createAttribute("esquema", "ddic:com.sap.dictionary.string", null, "esquema", false, false),
        GCIContext.createAttribute("calle", "ddic:com.sap.dictionary.string", null, "calle", false, false),
        GCIContext.createAttribute("puerta", "ddic:com.sap.dictionary.string", null, "puerta", false, false),
        GCIContext.createAttribute("observacionesMd", "ddic:com.sap.dictionary.string", null, "observacionesMd", false, false),
        GCIContext.createAttribute("tipoMaqVend", "ddic:com.sap.dictionary.string", null, "tipoMaqVend", false, false),
        GCIContext.createAttribute("codCategCliente", "ddic:com.sap.dictionary.string", null, "codCategCliente", false, false),
        GCIContext.createAttribute("observacionesUs", "ddic:com.sap.dictionary.string", null, "observacionesUs", false, false),
        GCIContext.createAttribute("cp", "ddic:com.sap.dictionary.string", null, "cp", false, false),
        GCIContext.createAttribute("razonSocialAbreviada", "ddic:com.sap.dictionary.string", null, "razonSocialAbreviada", false, false),
        GCIContext.createAttribute("usuarioAprobador", "ddic:com.sap.dictionary.string", null, "usuarioAprobador", false, false),
        GCIContext.createAttribute("formaEntregaCtaCte", "ddic:com.sap.dictionary.string", null, "formaEntregaCtaCte", false, false),
        GCIContext.createAttribute("agrupacionComercial", "ddic:com.sap.dictionary.integerObject", null, "agrupacionComercial", false, false),
        GCIContext.createAttribute("cantGeocodificacion", "ddic:com.sap.dictionary.integerObject", null, "cantGeocodificacion", false, false),
        GCIContext.createAttribute("polVtaCal3", "ddic:com.sap.dictionary.integerObject", null, "polVtaCal3", false, false),
        GCIContext.createAttribute("repositorio", "ddic:com.sap.dictionary.string", null, "repositorio", false, false),
        GCIContext.createAttribute("ramo", "ddic:com.sap.dictionary.integerObject", null, "ramo", false, false),
        GCIContext.createAttribute("tipoIVA", "ddic:com.sap.dictionary.integerObject", null, "tipoIVA", false, false),
        GCIContext.createAttribute("fechaVencimientoLicencia", "ddic:com.sap.dictionary.date", null, "fechaVencimientoLicencia", false, false),
        GCIContext.createAttribute("direccionTrDeuda", "ddic:com.sap.dictionary.string", null, "direccionTrDeuda", false, false),
        GCIContext.createAttribute("subCanalMkt", "ddic:com.sap.dictionary.integerObject", null, "subCanalMkt", false, false),
        GCIContext.createAttribute("categoriaClienteDesc", "ddic:com.sap.dictionary.string", null, "categoriaClienteDesc", false, false),
        GCIContext.createAttribute("fechaUltVerif", "ddic:com.sap.dictionary.date", null, "fechaUltVerif", false, false),
        GCIContext.createAttribute("usuarioSolicitante", "ddic:com.sap.dictionary.string", null, "usuarioSolicitante", false, false),
        GCIContext.createAttribute("tipoDocumentoDesc", "ddic:com.sap.dictionary.string", null, "tipoDocumentoDesc", false, false),
        GCIContext.createAttribute("transfDeudaEnv", "ddic:com.sap.dictionary.string", null, "transfDeudaEnv", false, false),
        GCIContext.createAttribute("pagaSeguro", "ddic:com.sap.dictionary.string", null, "pagaSeguro", false, false),
        GCIContext.createAttribute("tipoVtaFsEnvases", "ddic:com.sap.dictionary.integerObject", null, "tipoVtaFsEnvases", false, false),
        GCIContext.createAttribute("imprimeRemito", "ddic:com.sap.dictionary.string", null, "imprimeRemito", false, false),
        GCIContext.createAttribute("codTipoDocumento", "ddic:com.sap.dictionary.integerObject", null, "codTipoDocumento", false, false),
        GCIContext.createAttribute("nroImpuestoInterno", "ddic:com.sap.dictionary.string", null, "nroImpuestoInterno", false, false),
        GCIContext.createAttribute("cuitTrDeuda", "ddic:com.sap.dictionary.string", null, "cuitTrDeuda", false, false),
        GCIContext.createAttribute("polVtaCal2", "ddic:com.sap.dictionary.integerObject", null, "polVtaCal2", false, false),
        GCIContext.createAttribute("nroTicketCrm", "ddic:com.sap.dictionary.string", null, "nroTicketCrm", false, false),
        GCIContext.createAttribute("esAltaBaja", "ddic:com.sap.dictionary.string", null, "esAltaBaja", false, false),
        GCIContext.createAttribute("excIvaFechaHasta", "ddic:com.sap.dictionary.date", null, "excIvaFechaHasta", false, false),
        GCIContext.createAttribute("codNuevoClienteCCQ", "ddic:com.sap.dictionary.integerObject", null, "codNuevoClienteCCQ", false, false),
        GCIContext.createAttribute("autVentaAlochol", "ddic:com.sap.dictionary.string", null, "autVentaAlochol", false, false),
        GCIContext.createAttribute("excIIBBFechaDesde", "ddic:com.sap.dictionary.date", null, "excIIBBFechaDesde", false, false),
        GCIContext.createAttribute("mesajeFactura", "ddic:com.sap.dictionary.string", null, "mesajeFactura", false, false),
        GCIContext.createAttribute("coordenadaX", "ddic:com.sap.dictionary.string", null, "coordenadaX", false, false),
        GCIContext.createAttribute("nroTicketAsociado", "ddic:com.sap.dictionary.string", null, "nroTicketAsociado", false, false),
        GCIContext.createAttribute("banco", "ddic:com.sap.dictionary.integerObject", null, "banco", false, false),
        GCIContext.createAttribute("ctaCteExterna", "ddic:com.sap.dictionary.string", null, "ctaCteExterna", false, false),
        GCIContext.createAttribute("fechaCierre", "ddic:com.sap.dictionary.date", null, "fechaCierre", false, false),
        GCIContext.createAttribute("tipoEmpresa", "ddic:com.sap.dictionary.string", null, "tipoEmpresa", false, false),
        GCIContext.createAttribute("tipoIIBB", "ddic:com.sap.dictionary.string", null, "tipoIIBB", false, false),
        GCIContext.createAttribute("porcExcIva", "ddic:com.sap.dictionary.decimal", null, "porcExcIva", false, false),
        GCIContext.createAttribute("codCuentaMadre", "ddic:com.sap.dictionary.integerObject", null, "codCuentaMadre", false, false),
        GCIContext.createAttribute("nroLicVentaAlochol", "ddic:com.sap.dictionary.string", null, "nroLicVentaAlochol", false, false),
        GCIContext.createAttribute("cobrador", "ddic:com.sap.dictionary.string", null, "cobrador", false, false),
        GCIContext.createAttribute("codCliente", "ddic:com.sap.dictionary.integerObject", null, "codCliente", false, false),
        GCIContext.createAttribute("subCanalMktDesc", "ddic:com.sap.dictionary.string", null, "subCanalMktDesc", false, false),
        GCIContext.createAttribute("personeriaJuridica", "ddic:com.sap.dictionary.string", null, "personeriaJuridica", false, false),
        GCIContext.createAttribute("tipoClienteCondVta", "ddic:com.sap.dictionary.integerObject", null, "tipoClienteCondVta", false, false),
        GCIContext.createAttribute("coordenadaY", "ddic:com.sap.dictionary.string", null, "coordenadaY", false, false),
        GCIContext.createAttribute("telefono", "ddic:com.sap.dictionary.string", null, "telefono", false, false),
        GCIContext.createAttribute("tipoClienteContab", "ddic:com.sap.dictionary.integerObject", null, "tipoClienteContab", false, false),
        GCIContext.createAttribute("razonSocialClTrDeuda", "ddic:com.sap.dictionary.string", null, "razonSocialClTrDeuda", false, false),
        GCIContext.createAttribute("segmentoVta", "ddic:com.sap.dictionary.integerObject", null, "segmentoVta", false, false),
        GCIContext.createAttribute("listaPrecioBasico", "ddic:com.sap.dictionary.integerObject", null, "listaPrecioBasico", false, false),
        GCIContext.createAttribute("fechaCreacion", "ddic:com.sap.dictionary.date", null, "fechaCreacion", false, false),
        GCIContext.createAttribute("observacionesGeo", "ddic:com.sap.dictionary.string", null, "observacionesGeo", false, false),
        GCIContext.createAttribute("interseccion", "ddic:com.sap.dictionary.string", null, "interseccion", false, false),
        GCIContext.createAttribute("asigStock", "ddic:com.sap.dictionary.integerObject", null, "asigStock", false, false),
        GCIContext.createAttribute("tipoSolicitud", "ddic:com.sap.dictionary.string", null, "tipoSolicitud", false, false),
        GCIContext.createAttribute("comprador", "ddic:com.sap.dictionary.string", null, "comprador", false, false),
        GCIContext.createAttribute("fueCensado", "ddic:com.sap.dictionary.string", null, "fueCensado", false, false),
        GCIContext.createAttribute("email", "ddic:com.sap.dictionary.string", null, "email", false, false),
        GCIContext.createAttribute("polVtaCal1", "ddic:com.sap.dictionary.integerObject", null, "polVtaCal1", false, false),
        GCIContext.createAttribute("estadoTicket", "ddic:com.sap.dictionary.string", null, "estadoTicket", false, false),
        GCIContext.createAttribute("codProvincia", "ddic:com.sap.dictionary.integerObject", null, "codProvincia", false, false),
      },
      new IGCINodeInfo[] {
        infoLogs,
        infoAdjuntos,
        infoTerritorios,
      }
    );

    infoContext = GCIContext.createNode("Context", null, true, true, false, true, false, true, null,
      new IGCIAttributeInfo[] {
        GCIContext.createAttribute("esquema", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("segmento", "ddic:com.sap.dictionary.integer", null, null, false, false),
        GCIContext.createAttribute("numero", "ddic:com.sap.dictionary.integer", null, null, false, false),
        GCIContext.createAttribute("master", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("carpeta", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("nro_solicitud", "ddic:com.sap.dictionary.long", null, null, false, false),
        GCIContext.createAttribute("repositorio", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("observac", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("atributo", "java:com.sap.tc.webdynpro.services.session.api.IWDWindow", null, null, false, false),
        GCIContext.createAttribute("resultado", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("eleccion", "ddic:com.sap.dictionary.string", null, null, false, false),
        GCIContext.createAttribute("flag_adjunto", "ddic:com.sap.dictionary.string", null, null, false, false),
      },
      new IGCINodeInfo[] {
        infoAdjunto,
        infoTicket,
      }
    );

  }
  
  private IContextNode contextNode;

  private void wdInitContextNode() {
    contextNode = new IContextNode(this, infoContext, (Node)null);
  }

  public IWDNode wdGetRootNode() {
    return contextNode;
  }

  public IContextNode wdGetContext() {
    return contextNode;
  }


  // ---- Actions --------------------------------------------------------------

  /**
   * Create a new action for this controller. A unique name for the action is generated automatially.
   * @param eventHandler is the action's eventhandler with proper signature
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateAction(WDActionEventHandler eventHandler, String text) {
    return wdAlterEgo.createAction(null, eventHandler, text, null);
  }

  /**
   * Create a new action with the given name for this controller
   * @param eventHandler is the action's eventhandler with proper signature
   * @param name is the action's name
   * @param text is the text displayed in the UI element triggering this action
   */
  public IWDAction wdCreateNamedAction(WDActionEventHandler eventHandler, String name, String text) {
    return wdAlterEgo.createAction(name, eventHandler, text, null);
  }

  // ---- Controller part ------------------------------------------------------

  /**
   * Creates a new instance of this controller.
   */
  public InternalBajaUS(com.sap.tc.webdynpro.progmodel.gci.IGCIComponent alterEgo) {
    this.wdAlterEgo = alterEgo;
    wdInitContextNode();
    this.delegate = new com.quilmes.baja.BajaUS((IPrivateBajaUS) this);
  }

  /**
   * Returns the public API for this controller instance.
   */
  public com.sap.tc.webdynpro.progmodel.api.IWDComponent wdGetAPI() {
    return (com.sap.tc.webdynpro.progmodel.api.IWDComponent) wdAlterEgo;
  }

  /**
   * Hook method called to initialize component controller.
   */
  public void wdDoInit() {
    logger.pathT("entering: wdDoInit");
    delegate.wdDoInit();
    logger.pathT("exiting: wdDoInit"); 
  }

  /**
   * Hook method called to clean up component controller.
   */
  public void wdDoExit() {
    logger.pathT("entering: wdDoExit");
    delegate.wdDoExit();
    logger.pathT("exiting: wdDoExit"); 
  }

  /**
   * Hook called by framework in a request/response cycle each time before rendering starts
   */
  public void wdDoPostProcessing(boolean isCurrentRoot) {
    logger.pathT("entering: wdDoPostProcessing");
    delegate.wdDoPostProcessing(isCurrentRoot);
    logger.pathT("exiting: wdDoPostProcessing"); 
  }

  /**
   * Hook called by framework in a request/response cycle each time before the navigation queue is processed
   */
  public void wdDoBeforeNavigation(boolean isCurrentRoot) {
    logger.pathT("entering: wdDoBeforeNavigation");
    delegate.wdDoBeforeNavigation(isCurrentRoot);
    logger.pathT("exiting: wdDoBeforeNavigation"); 
  }
  
  /**
   * Hook called by framework when an application state change occurs
   */
  public void wdDoApplicationStateChange(com.sap.tc.webdynpro.progmodel.api.IWDApplicationStateChangeInfo stateChangeInfo, com.sap.tc.webdynpro.progmodel.api.IWDApplicationStateChangeReturn stateChangeReturn)
  {
    logger.pathT("entering: wdDoApplicationStateChange");
    delegate.wdDoApplicationStateChange(stateChangeInfo, stateChangeReturn);
    logger.pathT("exiting: wdDoApplicationStateChange"); 
  }
  

  public ar.com.quilmes.bue.mdm_clientes.ejb.ConsultasExternas getConsultasExternasBean( ) {
    return delegate.getConsultasExternasBean();
  }

  public ar.com.quilmes.bue.mdm_clientes.ejb.ConsultasInternas getConsultasInternasBean( ) {
    return delegate.getConsultasInternasBean();
  }

  public void inicializar( ) {
    delegate.inicializar();
  }

  public void fireInicializarEvent( ) {
    delegate.fireInicializarEvent();
  }

  public void BuscarPop( ) {
    delegate.BuscarPop();
  }

  public void closepop( ) {
    delegate.closepop();
  }

  public void fireFinalizarEvent( ) {
    delegate.fireFinalizarEvent();
  }

  public Object wdInvokeEventHandler(String handlerName, IWDCustomEvent event)
    throws NoSuchMethodException {
    
    logger.pathT("entering: wdInvokeEventHandler", new Object[] { handlerName } );
    try {
      throw new NoSuchMethodException("Eventhandler " + handlerName + " not found for event " + event.getName());
    } finally {
      logger.pathT("exiting: wdInvokeEventHandler"); 
    }
  }

  /** fire event */
  public void wdFireEventInicializar( ) {
    Map parameters = Collections.EMPTY_MAP;
    wdAlterEgo.getComponentGCI().fireEvent("BajaUS", "Inicializar", parameters);
  }
  
  /** fire event */
  public void wdFireEventFinalizar( ) {
    Map parameters = Collections.EMPTY_MAP;
    wdAlterEgo.getComponentGCI().fireEvent("BajaUS", "Finalizar", parameters);
  }
  

  public com.sap.tc.webdynpro.progmodel.api.IWDExternalControllerInterface wdGetExternalInterface() {
    return null;
  }
}
