// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// DO NOT MODIFY! CHANGES WILL BE LOST IF THE FILE IS REGENERATED.
// ---------------------------------------------------------------------------
package com.quilmes.baja.wdp;

import com.sap.tc.webdynpro.progmodel.api.*;
import com.sap.tc.webdynpro.progmodel.gci.*;
import com.sap.tc.webdynpro.progmodel.context.*;
import com.sap.tc.webdynpro.services.exceptions.WDRuntimeException;

public interface IPublicBajaUSInterface extends com.quilmes.baja.wdp.IExternalBajaUSInterface {


  /**
   * Interface for the node 'Context'.
   *
   * singleton = true, cardinality = _1_1, selection = _1_1
   */
  public static class IContextNode extends Node
  {
    private InternalBajaUSInterface gen_delegate;

    IContextNode(InternalBajaUSInterface delegate, IGCINodeInfo nodeInfo, Node parent) {
      super(nodeInfo, parent);
      gen_delegate = delegate;
    }

    protected com.sap.tc.webdynpro.progmodel.context.Node createNode(IGCINodeInfo nodeInfo, com.sap.tc.webdynpro.progmodel.context.Node parentNode, com.sap.tc.webdynpro.progmodel.context.NodeElement parentElement) {
      if (nodeInfo == gen_delegate.infoContext)
        return new IPrivateBajaUSInterface.IContextNode(gen_delegate, nodeInfo, parentNode);
      return super.createNode(nodeInfo, parentNode, parentElement);
    }

    protected com.sap.tc.webdynpro.progmodel.context.NodeElement doCreateElement(IGCINodeInfo nodeInfo, Object reference) {
      if (nodeInfo == gen_delegate.infoContext) {
        return new IPrivateBajaUSInterface.IContextElement(gen_delegate, nodeInfo);
      }
      return super.doCreateElement(nodeInfo, reference);
    }

    // ---- typed accessors --------------------------------------------------

    /**
     * Provides access to the generic context API as described by IWDContext.
     */
    public IWDContext wdGetAPI() {
      return getContext();
    }

    /**
     * Creates a new element for this node. The element is <b>not</b> bound 
     * to the node. Use {@link #bind(IContextElement)} or 
     * {@link IWDNode#bind(Collection)} to bind it or {@link IWDNode#addElement(IWDNodeElement)}
     * to add it to the node.
     * @return an element for this node
     */
    public IPrivateBajaUSInterface.IContextElement createContextElement() {
      return (IPrivateBajaUSInterface.IContextElement)createElement();
    }

    /**
     * Binds a single IContextElement to the node.
     * @param element a node element for this node
     */
    public void bind(IPrivateBajaUSInterface.IContextElement element) {
      bind(element == null ? java.util.Collections.EMPTY_LIST : java.util.Collections.singletonList(element));
    }

    /** 
     * Returns the element at the lead selection.
     * @return the element at the lead selection or <code>null</code> if the
     *         lead selection is not set
     */
    public IPrivateBajaUSInterface.IContextElement currentContextElement() {
      return (IPrivateBajaUSInterface.IContextElement) getCurrentElement();
    }

    // ---- hooks ------------------------------------------------------------

    // ---- child nodes ------------------------------------------------------------

  }

  /**
   * Interface for the elements of the node Context.
   */
  public static class IContextElement extends com.sap.tc.webdynpro.progmodel.context.NodeElement
  {
    private InternalBajaUSInterface gen_delegate;

    public IContextElement(InternalBajaUSInterface delegate, com.sap.tc.webdynpro.progmodel.gci.IGCINodeInfo info) {
      super(info);
      gen_delegate = delegate;
    }

    // attribute "tipo_usuario"
    public final static String TIPO__USUARIO = "tipo_usuario";

    private MappedAttribute _tipo_usuario;

    /**
     * Returns the attribute tipo_usuario.
     */
    public java.lang.String getTipo_usuario() {
      if (_tipo_usuario == null)
        _tipo_usuario = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("tipo_usuario"), this);
      return _tipo_usuario.getString();
    }

    /**
     * Sets the attribute tipo_usuario.
     * @param value the new value
     */
    public void setTipo_usuario(java.lang.String value) {
      if (this._tipo_usuario == null)
        this._tipo_usuario = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("tipo_usuario"), this);
      this._tipo_usuario.setString(value);
    }
    
    // attribute "nro_cliente"
    public final static String NRO__CLIENTE = "nro_cliente";

    private MappedAttribute _nro_cliente;

    /**
     * Returns the attribute nro_cliente.
     */
    public int getNro_cliente() {
      if (_nro_cliente == null)
        _nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
      return _nro_cliente.getInt();
    }

    /**
     * Sets the attribute nro_cliente.
     * @param value the new value
     */
    public void setNro_cliente(int value) {
      if (this._nro_cliente == null)
        this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
      this._nro_cliente.setInt(value);
    }
    
    // attribute "nro_solicitud"
    public final static String NRO__SOLICITUD = "nro_solicitud";

    private MappedAttribute _nro_solicitud;

    /**
     * Returns the attribute nro_solicitud.
     */
    public long getNro_solicitud() {
      if (_nro_solicitud == null)
        _nro_solicitud = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_solicitud"), this);
      return _nro_solicitud.getLong();
    }

    /**
     * Sets the attribute nro_solicitud.
     * @param value the new value
     */
    public void setNro_solicitud(long value) {
      if (this._nro_solicitud == null)
        this._nro_solicitud = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_solicitud"), this);
      this._nro_solicitud.setLong(value);
    }
    
    // generic access to fields (framework usage)
    protected Object wdGetObject(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // tipo_usuario
          if (this._tipo_usuario == null)
            this._tipo_usuario = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("tipo_usuario"), this);
          return _tipo_usuario.getObject();
        case 1: // nro_cliente
          if (this._nro_cliente == null)
            this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
          return _nro_cliente.getObject();
        case 2: // nro_solicitud
          if (this._nro_solicitud == null)
            this._nro_solicitud = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_solicitud"), this);
          return _nro_solicitud.getObject();
        default:
          return super.wdGetObject(info);
      }
    }

    protected void wdSetObject(IGCIAttributeInfo info, Object value) {
      switch (info.getIndex()) {
        case 0: // tipo_usuario
          if (this._tipo_usuario == null)
            this._tipo_usuario = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("tipo_usuario"), this);
          this._tipo_usuario.setObject(value);
          break;
        case 1: // nro_cliente
          if (this._nro_cliente == null)
            this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
          this._nro_cliente.setObject(value);
          break;
        case 2: // nro_solicitud
          if (this._nro_solicitud == null)
            this._nro_solicitud = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_solicitud"), this);
          this._nro_solicitud.setObject(value);
          break;
        default:
          super.wdSetObject(info, value);
          break;
      }
    }

    protected int wdGetInt(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 1: // nro_cliente
          if (this._nro_cliente == null)
            this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
          return _nro_cliente.getInt();
        default:
          return super.wdGetInt(info);
      }
    }

    protected void wdSetInt(IGCIAttributeInfo info, int value) {
      switch (info.getIndex()) {
        case 1: // nro_cliente
          if (this._nro_cliente == null)
            this._nro_cliente = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_cliente"), this);
          this._nro_cliente.setInt(value);
          break;
        default:
          super.wdSetInt(info, value);
          break;
      }
    }

    protected long wdGetLong(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 2: // nro_solicitud
          if (this._nro_solicitud == null)
            this._nro_solicitud = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_solicitud"), this);
          return _nro_solicitud.getLong();
        default:
          return super.wdGetLong(info);
      }
    }

    protected void wdSetLong(IGCIAttributeInfo info, long value) {
      switch (info.getIndex()) {
        case 2: // nro_solicitud
          if (this._nro_solicitud == null)
            this._nro_solicitud = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("nro_solicitud"), this);
          this._nro_solicitud.setLong(value);
          break;
        default:
          super.wdSetLong(info, value);
          break;
      }
    }

    protected String wdGetString(IGCIAttributeInfo info) {
      switch (info.getIndex()) {
        case 0: // tipo_usuario
          if (this._tipo_usuario == null)
            this._tipo_usuario = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("tipo_usuario"), this);
          return _tipo_usuario.getString();
        default:
          return super.wdGetString(info);
      }
    }

    protected void wdSetString(IGCIAttributeInfo info, String value) {
      switch (info.getIndex()) {
        case 0: // tipo_usuario
          if (this._tipo_usuario == null)
            this._tipo_usuario = new MappedAttribute(wdGetNodeInfoGCI().getAttributeGCI("tipo_usuario"), this);
          this._tipo_usuario.setString(value);
          break;
        default:
          super.wdSetString(info, value);
          break;
      }
    }

  }

  /**
   * Returns the context root node.
   * @return the context root node.
   */
  IContextNode wdGetContext();

  /** Fires event. */
  void wdFireEventTechnicalException( com.sap.caf.eu.gp.exception.api.GPTechnicalCallableObjectException technicalException );
  
}
