// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package ar.com.quilmes.consulta.models_eliminar_cc;


/**
 * "Request_Execute" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class Request_Execute extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClassExecutable
{
  public Request_Execute(CuentaCorriente modelInstance) {
    super(modelInstance, "Request_Execute");
  }

  public CuentaCorriente getModelInstance() {
    return (CuentaCorriente) this.associatedModel();
  }
  
  private Request_Execute(CuentaCorriente modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new Request_Execute((CuentaCorriente)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> GetCtaCteClienteExecute
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> GetCtaCteClienteExecute 
   *  @return value of ModelAttribute GetCtaCteClienteExecute */
  public ar.com.quilmes.consulta.models_eliminar_cc.GetCtaCteCliente_Execute getGetCtaCteClienteExecute() {
    return (ar.com.quilmes.consulta.models_eliminar_cc.GetCtaCteCliente_Execute)getRelatedModelObject("GetCtaCteClienteExecute");
  }
  
  /** setter for 1:1 Relation Role -> GetCtaCteClienteExecute 
   *  @param value new value for 1:1 Relation Role  GetCtaCteClienteExecute */
  public void setGetCtaCteClienteExecute(ar.com.quilmes.consulta.models_eliminar_cc.GetCtaCteCliente_Execute value) {
    setRelatedModelObject("GetCtaCteClienteExecute",value);
  }
  /****************************************************************************
   * 1:1 Relation -> Response
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> Response 
   *  @return value of ModelAttribute Response */
  public ar.com.quilmes.consulta.models_eliminar_cc.Response_Execute getResponse() {
    return (ar.com.quilmes.consulta.models_eliminar_cc.Response_Execute)getRelatedModelObject("Response");
  }
  
  /** setter for 1:1 Relation Role -> Response 
   *  @param value new value for 1:1 Relation Role  Response */
  public void setResponse(ar.com.quilmes.consulta.models_eliminar_cc.Response_Execute value) {
    setRelatedModelObject("Response",value);
  }

}

