// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator.
// ---------------------------------------------------------------------------
package ar.com.quilmes.consulta.models_eliminar_cc;


/**
 * "Response_Execute" Adaptive Webservice ModelClass implementation
 * Copyright (c) 2005 - 2006. All rights reserved.
 * SAP AG
 * @author       File created by Web Dynpro code generator
 */

public final class Response_Execute extends com.sap.tc.webdynpro.model.webservice.gci.WSTypedModelClass
{
  public Response_Execute(CuentaCorriente modelInstance) {
    super(modelInstance, "Response_Execute");
  }

  public CuentaCorriente getModelInstance() {
    return (CuentaCorriente) this.associatedModel();
  }
  
  private Response_Execute(CuentaCorriente modelInstance, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
    super(modelInstance, genericModelClass);
  }

  /**
   * Returns the factory for this typed model class.
   */
  static com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory createModelClassFactory() {
    return new com.sap.tc.webdynpro.model.webservice.gci.IWSTypedModelClassFactory() {
      public com.sap.tc.cmi.model.ICMIModelClass createModelClass(com.sap.tc.webdynpro.model.webservice.gci.WSTypedModel typedModel, com.sap.tc.cmi.model.ICMIModelClass genericModelClass) {
        return new Response_Execute((CuentaCorriente)typedModel, genericModelClass);
      }
    };
  }  


  /****************************************************************************
   * 1:1 Relation -> GetCtaCteClienteExecuteResponse
   ***************************************************************************/
  /** getter for 1:1 Relation Role -> GetCtaCteClienteExecuteResponse 
   *  @return value of ModelAttribute GetCtaCteClienteExecuteResponse */
  public ar.com.quilmes.consulta.models_eliminar_cc.GetCtaCteCliente_ExecuteResponse getGetCtaCteClienteExecuteResponse() {
    return (ar.com.quilmes.consulta.models_eliminar_cc.GetCtaCteCliente_ExecuteResponse)getRelatedModelObject("GetCtaCteClienteExecuteResponse");
  }
  
  /** setter for 1:1 Relation Role -> GetCtaCteClienteExecuteResponse 
   *  @param value new value for 1:1 Relation Role  GetCtaCteClienteExecuteResponse */
  public void setGetCtaCteClienteExecuteResponse(ar.com.quilmes.consulta.models_eliminar_cc.GetCtaCteCliente_ExecuteResponse value) {
    setRelatedModelObject("GetCtaCteClienteExecuteResponse",value);
  }

}

